### PR TITLE
fix: update ai summarizeMessage-prompt to hide any introduction

### LINKED ISSUE #11278: AI email summary includes prompt
### Steps to reproduce

Let the mail app generate some mail summary.

### Expected behavior

There should only be the actual summary be shown

### Actual behavior

The AI Summary includes information from the Prompt and/or "-signs:
```main - INFO - {'output': 'Here is a helpful summary of the email message in under 160 characters:\n\n"Reminder: Review and update something by end of week."'}```

### Mail app version

5.1.3

### Nextcloud version

31.0.6

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

None

### Nextcloud memory caching

_No response_

### Web server

None

### Database

None

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by 1358**
This resolves #11278

### CODE REVIEW

File: lib/Service/AiIntegrations/AiIntegrationsService.php [hunk 1]
```diff
@@ -98,6 +98,7 @@ public function summarizeMessages(Account $account, array $messages): void {
 				$messageBody = $message->getPlainBody();
 				$prompt = "You are tasked with formulating a helpful summary of a email message. \r\n"
 						  . "The summary should be less than 160 characters. \r\n"
+					      . "Output *ONLY* the summary itself, leave out any introduction. \r\n"
```
Comment (ChristophWurst) [inline lib/Service/AiIntegrations/AiIntegrationsService.php]:
```suggestion
						  . "Output *ONLY* the summary itself, leave out any introduction. \r\n"
```

**Comment by hamza221** [comment]
Please run `composer run cs:fix` and sign the commit

**Comment by ChristophWurst** [comment]
Fixed the commit history. Now it's one commit and the email address also associated with your github account

**Comment by 1358** [comment]
> Fixed the commit history. Now it's one commit and the email address also associated with your github account

Thanks alot!

**Comment by hamza221** [comment]
> /backport to stable5.1

Can’t figure out why this is wrong ?

**Comment by ChristophWurst** [comment]
You have to say *please* :sweat_smile:

**Comment by ChristophWurst** [comment]
I think it was a bot hiccup. Your comment was fine :)
