### PR TITLE
Handle empty thread root id

### LINKED ISSUE #5774: Unexpected behaviour in Mail Rendering
### Expected behavior
This is how the mail looks like in Rainloop (inside Nextcloud) and Fairemail on my Android Phone
image
image

### Actual behavior
This is the mail in NC Mail with the "Termin buchen" Link not visible, but if you know where it is, you can click it at least 🗡️ 
image

### Mail app
**Mail app version:** 1.11
**Mailserver or service:** IMAP

### Server configuration
**Operating system**: Debian 10
**Web server:** Apache
**Database:** MariaDB
**PHP version:** 7.3
**Nextcloud Version:** 22.2.2
#### Client configuration
**Browser:** FF 94 & Edge 96.0
**Operating system:** Windows 10

HTML Code of the Mail can be shared if requested.

### PR DESCRIPTION
**Pull request by miaulalala**
Fixes #5774

### CODE REVIEW

**Comment by miaulalala** [comment]
I don't know if the frontend will handle the new 404 response correctly. Waiting for an email to test this.

File: lib/Controller/MessagesController.php [hunk 1]
```diff
@@ -307,6 +306,10 @@ public function getThread(int $id): JSONResponse {
 			return new JSONResponse([], Http::STATUS_FORBIDDEN);
 		}
 
+		if (empty($message->getThreadRootId())) {
```
Comment (ChristophWurst) [inline lib/Controller/MessagesController.php:309]: in what scenario do we allow the thread root ID to be null? shouldn't it always have a value, worst case it's own message ID, no?

Comment (miaulalala) [reply lib/Controller/MessagesController.php:309]: Is it?  didn't know. Seems like the issue is cropping up somewhere else then since the related ticket is having issues with exactly that.

Comment (ChristophWurst) [reply lib/Controller/MessagesController.php:309]: yeah. because if it's NULL, what thread does it belong to?

ref https://github.com/nextcloud/mail/issues/5747 for one of the more recent incidents where the ID was erroneously null.

Comment (miaulalala) [reply lib/Controller/MessagesController.php:309]: Right, programatically, we're currently supporting null values for the threadRootId: https://github.com/nextcloud/mail/blob/8aabd4dede1ff2f7021b018e72a9aee35595e268/lib/Db/Message.php#L175

We could change that line to use the `messageId` in case the `threadRootId` is empty? Would prevent future issues like this.

And as for fixing the old ones, a repair step that encapsulates https://github.com/nextcloud/mail/issues/5747#issuecomment-979483114 ?

Comment (ChristophWurst) [reply lib/Controller/MessagesController.php:309]: Let's do that!

**Comment by miaulalala** [comment]
@ChristophWurst is the repair step still needed for the empty thread root id's? Something's vaguely stick in my brain that we do update empty thread root ids already when we build the threads?

File: lib/Db/Message.php [hunk 2]
```diff
@@ -174,7 +174,9 @@ public function setInReplyTo(?string $inReplyTo): void {
 	}
 
 	public function setThreadRootId(?string $messageId): void {
-		$this->setMessageIdFieldIfNotEmpty('threadRootId', $messageId);
+		$threadRootId = (!empty($messageId)) ? '<' . rtrim(ltrim($messageId, '<'), '>') . '>' : $this->getMessageId();
+		$parsed = new Horde_Mail_Rfc822_Identification($threadRootId);
+		$this->threadRootId = ($parsed->ids[0] ?? null);
```
[the remark this answers is not in the document]
Comment (miaulalala) [reply lib/Db/Message.php:179]: yeah but it needs to run through the horde parser to properly format the id

Comment (ChristophWurst) [inline lib/Db/Message.php:179]:
```suggestion
		if (!empty($parsed->ids[0]) {
			$this->setter('threadRootId', $parsed->ids[0]);
		}
```

1) Does *not* set the thread root id to `null`
2) Works with the entity change detection. If you assign `$this->threadRootId` directly you bypass the call to `\OCP\AppFramework\Db\Entity::markFieldUpdated`.

**Review by ChristophWurst — APPROVED** [review]

**Comment by ChristophWurst** [comment]
> @ChristophWurst is the repair step still needed for the empty thread root id's? Something's vaguely stick in my brain that we do update empty thread root ids already when we build the threads?

I would say the repair step still makes sense because all messages with invalid headers sync'ed before this fix can potentially have a null thread root id.

**Comment by ChristophWurst** [comment]
I would leave https://github.com/nextcloud/mail/blob/main/lib/Migration/AddMissingMessageIds.php in. If all messages are correct then the job doesn't touch anything.
