### PR TITLE
Fix saving outbox drafts

### LINKED ISSUE #6330: Outbox message edits are not automatically saved
### Steps to reproduce

1. Open an existing outbox message
2. Type something else on the body or change to/cc
3. Close the modal
4. Open again and see if you see what you typed last

### Expected behavior

My new changes are shown

### Actual behavior

No changes are shown

### Mail app version

latest

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by GretaD**
fixes #6330 

needs : #6180

### CODE REVIEW

File: src/components/NewMessageModal.vue [hunk 1]
```diff
@@ -40,6 +40,7 @@ export default {
 	data() {
 		return {
 			original: undefined,
+			serializeRecipients: false,
```
Comment (ChristophWurst) [inline src/components/NewMessageModal.vue:43]: revert

**Review by ChristophWurst — APPROVED** [review]
