### PR TITLE
Disable provisioned accounts if using passwordless authentication

### LINKED ISSUE #7520: Disable provisioned accounts when logged in passwordless
### Steps to reproduce

1. Log in to Nextcloud using openid
2. Try to open Nextcloud mail
3. See the page loading 

### Expected behavior

An error message is shown to explain that the mail app doesnt work when loging in using an openid, or disable the mail app in this scenario.

### Actual behavior

The mail app loads like something is happening when actually it is not.

### Mail app version

_No response_

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by st3iny**
Fix #7520 

Best reviewed with hidden white space changes: https://github.com/nextcloud/mail/pull/7616/files?w=1

This bug can be reproduced by using WebAuthn passwordless authentication. You can set it up in `Personal Settings -> Security -> Passwordless Authentication`.

## Before

Endless spinner was showing when clicking on a mail. It can't be loaded because the provisioned account isn't able to access the password for the IMAP server.

## After

The account is disabled and a info message is shown to the user. It might be a little bit technical. Feel free to propose better phrasing.

image

### CODE REVIEW

File: src/components/NavigationAccount.vue [hunk 1]
```diff
@@ -198,9 +211,6 @@ export default {
 		bulletColor() {
 			return this.account.error ? undefined : calculateAccountColor(this.account.emailAddress)
 		},
-		iconError() {
-			return this.account.error
-		},
```
Comment (st3iny) [inline src/components/NavigationAccount.vue:203]: Not related but this code is dead.

**Review by GretaD — APPROVED** [review]
didnt test it
