### PR TITLE
Sets <p> margin to 0 for sent emails

### LINKED ISSUE #2481: Sending mail inserts newlines
Write a mail:
```
⏮ Last week:
- More 18 reviews and polishing
- Went through notifications
```

Send it, and see it formatted like this:
```
⏮ Last week:

- More 18 reviews and polishing

- Went through notifications
```

Priority cause it changes mail text unexpectedly. :)

### PR DESCRIPTION
**Pull request by StCyr**
fixes #2481 and #2513 I guess )

Signed-off-by: Cyrille Bollu <cyrpub@bollu.be>

### CODE REVIEW

File: src/components/NewMessageDetail.vue [hunk 1]
```diff
@@ -261,6 +261,7 @@ export default {
 			})
 		},
 		sendMessage(data) {
+			data.body = '<style>p{margin:0;}</style>' + data.body
```
Comment (ChristophWurst) [inline src/components/NewMessageDetail.vue]: Two remarks

1) This is problematic for plaintext messages as at this point we already have a non-hmtl version of the body AFAIK
2) The CKEditor would allow us to change the way certain elements are rendered into HTML. We could change the generated HTML there as well. Might be the cleaner approach :thinking:

Comment (StCyr) [reply src/components/NewMessageDetail.vue]: >     1. This is problematic for plaintext messages as at this point we already have a non-hmtl version of the body AFAIK

You're right. 

>     2. The CKEditor would allow us to change the way certain elements are rendered into HTML. We could change the generated HTML there as well. Might be the cleaner approach 🤔

You mean using this? https://ckeditor.com/docs/ckeditor5/latest/features/headings.html

Comment (ChristophWurst) [reply src/components/NewMessageDetail.vue]: More like this https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-extending-output.html#adding-a-css-class-to-block-elements. But the question is how to add the styles. We could either have them inline for every `<p>` or include a style block somewhere.

Comment (StCyr) [reply src/components/NewMessageDetail.vue]: I would say adding a style bock is cleaner. Isn't?

Comment (StCyr) [reply src/components/NewMessageDetail.vue]: wouldn't this be more appropriate? 

https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-preserving-custom-content.html

**Comment by StCyr** [comment]
I've tried to create a ckeditor plugin to implement this functionality.

Without success till now.

If someone @nextcloud/mail with knowledge about ckeditor's internals could review my PR to try and understand what should be done ,that would be great.

ping @ChristophWurst

**Comment by StCyr** [comment]
Hi @ChristophWurst 

This should be working properly now

Cyrille

File: src/components/NewMessageDetail.vue (hunk 1 above)
Comment (ChristophWurst) [reply src/components/NewMessageDetail.vue]: Makes sense!

File: src/components/Composer.vue [hunk 2]
```diff
@@ -342,7 +342,9 @@ export default {
 					bcc: this.selectBcc.map(this.recipientToRfc822).join(', '),
 					draftUID: uid,
 					subject: this.subjectVal,
-					body: this.editorPlainText ? htmlToText(this.bodyVal) : this.bodyVal,
+					body: this.editorPlainText
```
Comment (ChristophWurst) [inline src/components/Composer.vue]: Works, but from a logical PoV the composer shouldn't have to care about this. This should be moved to the `TextEditor.vue`

**Comment by ChristophWurst** [comment]
Can't test right now as I have my local setup migrated to #2064 but will give it a test once that PR is merged :)

File: src/components/Composer.vue (hunk 2 above)
Comment (StCyr) [reply src/components/Composer.vue]: Makes sense but I can't figure out how to implement this there.

What could probably easily be done would be to add a "style" attribute to all `<p>` elements rather than assign them a class:

`viewWriter.addClass('null-margin', conversionApi.mapper.toViewElement(data.item))`

might be changed to add an attribute rather than adding a class.

Comment (ChristophWurst) [reply src/components/Composer.vue]: > Makes sense but I can't figure out how to implement this there.

Possibly at https://github.com/nextcloud/mail/blob/1691463ecdfa207f5e470c7592196812b76ff563/src/components/TextEditor.vue#L141 but CKEditor might remove the `style` tag. I also just realized that when we only add the style element when the message is sent, the previewed message looks different than what is actually sent.



> What could probably easily be done would be to add a "style" attribute to all `<p>` elements rather than assign them a class:

If that is easy to do I'm fine with that as well :) This will also show a correct preview of what will be sent (independent of Nextcloud's paragraph styling)

**Comment by ChristophWurst** [comment]
This works fine with the rich text editing mode. But the plain text one still has line breaks for paragraphs, no?

**Comment by StCyr** [comment]
> 
> 
> This works fine with the rich text editing mode. But the plain text one still has line breaks for paragraphs, no?

I think it's fixed now
