### PR TITLE
Fix thread envelope active state background colour

### LINKED ISSUE #3665: Threading message headers background colors and feedbacks
1) Could we make the expanded message's header in the thread light primary? Like the selected conversation in talk

2) I think that we could use the a more pronounced border radius for the hover feedback, either --border-radius-large or even --border-radius-pill

ref for current state https://github.com/nextcloud/mail/pull/3651

### PR DESCRIPTION
**Pull request by GretaD**
fixes #3665

### CODE REVIEW

File: src/components/ThreadEnvelope.vue [hunk 1]
```diff
@@ -21,7 +21,8 @@
 
 <template>
 	<div class="envelope">
-		<div class="envelope--header">
+		<div class="envelope--header"
+			:class="expanded ? 'list-item-style' : ''">
```
Comment (st3iny) [inline src/components/ThreadEnvelope.vue:25]:
```suggestion
			:class="{ 'list-item-style': expanded }'">
```

**Review by st3iny — CHANGES_REQUESTED** [review]
Works for headers of expanded thread envelopes. The hover feedback is still missing a border-radius (ref 2. from the linked issue).

Bildschirmfoto von 2021-06-24 09-29-14

**Review by st3iny — APPROVED** [review]
Works :rocket:
