### PR TITLE
Fix multiple tags with same label

### LINKED ISSUE #9021: Multiple tags with same label
### Steps to reproduce

1.Press edit tags on any envelope
2.write tag name in the input
3.click on the button fast multiple times
image

### Expected behavior

Button is disabled and tag is only created once

### Actual behavior

The tag is created multiple times.
PS: after a page refresh only one copy would stay as the api call will fail for the duplicates

### Mail app version

latest main

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ScratchX98**
Fixes #9021

I figured it would be reasonable to keep using the `showSaving` ref to check that the async request finishes

### CODE REVIEW

File: src/components/TagModal.vue [hunk 1]
```diff
@@ -163,6 +163,8 @@ export default {
 		},
 		async createTag(event) {
 			this.editing = true
+			if (this.showSaving) return
```
Comment (ChristophWurst) [inline src/components/TagModal.vue:166]: It would be more elegant if the button is disabled while the previous async request is still happening. Then `createTag` can never be called while `this.showSaving` is true ;)

Comment (ScratchX98) [reply src/components/TagModal.vue:166]: Right, I added a commit disabling the input when needed, but leaving the `showSaving` condition in `createTag` for safety, or do you reckon that should be removed to simplify?

Comment (ChristophWurst) [reply src/components/TagModal.vue:166]: Fair enough. We can do both!

Comment (ChristophWurst) [inline src/components/TagModal.vue:166]:
```suggestion
			if (this.showSaving) {
				return
			}
```

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
Coding style

**Review by ChristophWurst — APPROVED** [review]
Looks good!

File: src/components/TagModal.vue [hunk 2]
```diff
@@ -172,6 +176,9 @@ export default {
 				showError(this.t('mail', 'Tag already exists'))
 				return
 			}
+			if (displayName !== null && displayName !== '') {
```
Comment (GretaD) [inline src/components/TagModal.vue:179]: we dont need both checks, right? We can just write: `if (displayName !== '')` and the result is the same

**Review by GretaD — APPROVED** [review]
nice, it works :) thank you @ScratchX98

**Comment by GretaD** [comment]
wait, i tested adding a tag not editing one. retesting

**Review by GretaD — APPROVED** [review]
