### PR TITLE
Change how charsets are detected for emails

### LINKED ISSUE #5834: Hebrew (all RTL?) Language Error
### Expected behavior
Emails should sync and appear.

### Actual behavior
Syncing is stuck indefinitely due to emails in my inbox that contain Hebrew. Folders without Hebrew sync fine.

Running occ mail:account:sync provides the following output:

```
In ImapToDbSynchronizer.php line 249:
                                                                                                                         
  Sync failed for 5:INBOX: mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding "iso-8859-8-i"  
                                                                                                                         

In String.php line 160:
                                                                                                
  mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding "iso-8859-8-i"
```

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.11.1

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Mailbox.org

### Server configuration

**Operating system**: (e.g. Debian 8)
ppenSUSE MicroOS

**Web server:** (e.g. Apache, Nginx,...)
Nginx

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0)
Whatever is in the docker image nextcloud:fpm

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
23.0.0.10

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 94.0.2

**Operating system:** (e.g. Arch Linux)
openSUSE Tumbleweed

Thanks!!

### LINKED ISSUE #5845: Loading messages fails on some folders with mb_convert_encoding() error
The setup is Nexcloud 23 beta, IMAP mailbox, centos 7 with postgres 12.8, php 8.0.3.

The specific error is:

mb_convert_encoding(): Argument #3 ($from_encoding) must specify at least one encoding

and in the logs the full stack says:

Caused by ValueError: mb_convert_encoding(): Argument #3 ($from_encoding) must specify at least one encoding
/var/www/html/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Util/Horde/String.php - line 160:

mb_convert_encoding(null, "utf-8", "")

Is there a setting I'm missing or something else I should do to my setup to fix it?

Edit: Forgot to clarify that this is due to php8 now throw a value error for incorrect encoding. It is fixable if in vendor/pear-pear.horde.org/Horde_Util/Horde/String.php from_encoding is changed to self::_mbstringCharset($from)?self::_mbstringCharset($from):null but is there a setting to specify a default encoding which I'm missing.

### PR DESCRIPTION
**Pull request by miaulalala**
Fixes #5845
Fixes #5834

### CODE REVIEW

File: lib/Model/IMAPMessage.php [hunk 1]
```diff
@@ -619,7 +619,9 @@ private function loadBodyData(Horde_Mime_Part $p, $partNo): string {
 		$p->setContents($data);
 		$data = $p->getContents();
 
-		$data = mb_convert_encoding($data, 'UTF-8', $p->getCharset());
```
Comment (ChristophWurst) [inline lib/Model/IMAPMessage.php:622]: is  `$p->getCharset()` not reliable?

Comment (miaulalala) [reply lib/Model/IMAPMessage.php:622]: No not really, it uses the 'content-type' header from the email, which can contain invalid charsets / charsets that are not valid for PHP at least.

I would like to combine these two - check for the Horde Charset first, then if that is invalid, use the mb_detect_charset function as it can lead to errors too.

**Comment by GretaD** [comment]
this looks good for me too

**Comment by xinstein** [comment]
I did 
```
git clone https://github.com/nextcloud/mail.git
cd mail
git checkout fix/detect-char-encoding
cd ..
chown -R www-data:www-data mail
```
and then I enable mail in nextcloud apps page.

Error was raised when I enter mails app, and I can't enter nextcloud settings anymore.
The nextcloud log is too huge to upload, but I can copy some seemingly relevant messages here:

```
{"reqId":"o1lBfGhQANsvDMeryCH2","level":3,"time":"2022-01-06T03:40:01+00:00","remoteAddr":"10.0.2.2","user":"xavier","app":"index","method":"GET","url":"/settings/user","message":"Class \"Horde_Imap_Client\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Exception","Message":"Class \"Horde_Imap_Client\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\PersonalSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/user"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"Error","Message":"Class \"Horde_Imap_Client\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"newInstanceArgs","class":"ReflectionClass","type":"->","args":[[{"__class__":"OCA\\Mail\\IMAP\\IMAPClientFactory"},{"__class__":"OCA\\Mail\\Db\\MailboxMapper"},{"__class__":"OCA\\Mail\\IMAP\\MailboxSync"},{"__class__":"OCA\\Mail\\IMAP\\FolderMapper"},{"__class__":"OCA\\Mail\\IMAP\\MessageMapper"},{"__class__":"OCA\\Mail\\Db\\MessageMapper"},{"__class__":"OC\\EventDispatcher\\EventDispatcher"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"},{"__class__":"OCA\\Mail\\Db\\TagMapper"},{"__class__":"OCA\\Mail\\Db\\ThreadMapper"}]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Service\\MailManager","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":56,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":182,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":160,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php","line":114,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":127,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":454,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"name":"userFolder","__class__":"ReflectionParameter"},{"name":"accountService","__class__":"ReflectionParameter"},{"name":"attachmentService","__class__":"ReflectionParameter"},"*** sensitive parameter replaced ***",{"name":"imapClientFactory","__class__":"ReflectionParameter"},{"name":"smtpClientFactory","__class__":"ReflectionParameter"},{"name":"eventDispatcher","__class__":"ReflectionParameter"},{"name":"mailboxMapper","__class__":"ReflectionParameter"},{"name":"messageMapper","__class__":"ReflectionParameter"},{"name":"logger","__class__":"ReflectionParameter"},{"name":"performanceLogger","__class__":"ReflectionParameter"}]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Service\\MailTransmission","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":56,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":182,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":160,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php","line":114,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":127,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":454,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"name":"config","__class__":"ReflectionParameter"},{"name":"messageMapper","__class__":"ReflectionParameter"},"*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Service\\AntiSpamService","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"name":"initialStateService","__class__":"ReflectionParameter"},{"name":"provisioningManager","__class__":"ReflectionParameter"},"*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Settings\\AdminSettings","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/ServerContainer.php","line":145,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/Settings/Manager.php","line":170,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/Settings/Manager.php","line":232,"function":"getSettings","class":"OC\\Settings\\Manager","type":"->","args":["admin","overview"]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":90,"function":"getAdminSettings","class":"OC\\Settings\\Manager","type":"->","args":["overview",false]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":123,"function":"formatSections","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":[{"0":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Overview"}],"1":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Server"}],"5":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Sharing"}],"10":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Security"},{"__class__":"OCA\\Files_External\\Settings\\Section"},{"__class__":"OCA\\News\\Settings\\AdminSection"}],"30":[{"__class__":"OCA\\Theming\\Settings\\Section"}],"50":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Groupware"},{"__class__":"OCA\\Passwords\\Settings\\AdminSection"}],"55":[{"__class__":"OCA\\Activity\\Settings\\AdminSection"},{"__class__":"OCA\\External\\Settings\\Section"},{"__class__":"OCA\\WorkflowEngine\\Settings\\Section"}],"70":[{"__class__":"OCA\\Talk\\Settings\\Admin\\Section"},{"__class__":"OCA\\SSEPush\\Settings\\SSEPushSection"}],"75":[{"__class__":"OCA\\Richdocuments\\Settings\\Section"}],"80":[{"__class__":"OCA\\Bookmarks\\Settings\\AdminSection"},{"__class__":"OCA\\Gitlab\\Settings\\AdminSection"},{"__class__":"OCA\\Polls\\Settings\\AdminSection"}],"90":[{"__class__":"OCA\\AppOrder\\Settings\\Section"},{"__class__":"OCA\\GroupFolders\\Settings\\Section"},{"__class__":"OCA\\LogReader\\Settings\\Section"},{"__class__":"OCA\\ServerInfo\\Settings\\AdminSection"}],"98":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Additional"}]},"personal-info","admin","personal",false]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":75,"function":"formatAdminSections","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info",false]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":147,"function":"getNavigationParameters","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/var/www/html/apps/settings/lib/Controller/PersonalSettingsController.php","line":67,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"index","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal-info"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\PersonalSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/user"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","Line":106},"CustomMessage":"--"},"id":"61d664c5080fa"}
```
```
{"reqId":"aDKQAPjpmbuz8Vz7W12x","level":3,"time":"2022-01-06T03:40:02+00:00","remoteAddr":"10.0.2.2","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/theming/image/background","message":"include_once(/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php): Failed to open stream: No such file or directory at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Error","Message":"include_once(/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php): Failed to open stream: No such file or directory at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"include_once(/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php): Failed to open stream: No such file or directory","/var/www/html/custom_apps/mail/lib/AppInfo/Application.php",76]},{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"include_once"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":480,"args":["/var/www/html/custom_apps/mail/lib/AppInfo/Application.php"],"function":"include"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":346,"function":"Composer\\Autoload\\includeFile","args":["/var/www/html/custom_apps/mail/lib//AppInfo/Application.php"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":117,"function":"class_exists","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":82,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[["files","accessibility","activity","apporder","bookmarks","breezedark","bruteforcesettings","calendar","checksum","cloud_federation_api","comments","contacts","contactsinteraction","cospend","dashboard","dav","deck","external","extract","federatedfilesharing","files_downloadactivity","files_external","files_markdown","files_mindmap","files_pdfviewer","files_rightclick","files_sharing","files_trashbin","files_versions","files_videoplayer","firstrunwizard","forms","groupfolders","integration_gitlab","logreader","lookup_server_connector","mail","maps","metadata","music","news","notes","notifications","notify_push","oauth2","ocdownloader","password_policy","passwords","phonetrack","photos","polls","privacy","provisioning_api","recommendations","richdocuments","serverinfo","settings","sharebymail","spreed","ssepush","systemtags","tasks","text","theming","twofactor_backupcodes","twofactor_nextcloud_notification","twofactor_totp","unsplash","user_status","viewer","weather_status","workflow_script","workflowengine"]]},{"file":"/var/www/html/lib/base.php","line":640,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":34,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"61d664c507e4c"}
```
```
{"reqId":"aDKQAPjpmbuz8Vz7W12x","level":3,"time":"2022-01-06T03:40:02+00:00","remoteAddr":"10.0.2.2","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/theming/image/background","message":"include_once(): Failed opening '/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Error","Message":"include_once(): Failed opening '/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"include_once(): Failed opening '/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps')","/var/www/html/custom_apps/mail/lib/AppInfo/Application.php",76]},{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"include_once"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":480,"args":["/var/www/html/custom_apps/mail/lib/AppInfo/Application.php"],"function":"include"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":346,"function":"Composer\\Autoload\\includeFile","args":["/var/www/html/custom_apps/mail/lib//AppInfo/Application.php"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":117,"function":"class_exists","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":82,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[["files","accessibility","activity","apporder","bookmarks","breezedark","bruteforcesettings","calendar","checksum","cloud_federation_api","comments","contacts","contactsinteraction","cospend","dashboard","dav","deck","external","extract","federatedfilesharing","files_downloadactivity","files_external","files_markdown","files_mindmap","files_pdfviewer","files_rightclick","files_sharing","files_trashbin","files_versions","files_videoplayer","firstrunwizard","forms","groupfolders","integration_gitlab","logreader","lookup_server_connector","mail","maps","metadata","music","news","notes","notifications","notify_push","oauth2","ocdownloader","password_policy","passwords","phonetrack","photos","polls","privacy","provisioning_api","recommendations","richdocuments","serverinfo","settings","sharebymail","spreed","ssepush","systemtags","tasks","text","theming","twofactor_backupcodes","twofactor_nextcloud_notification","twofactor_totp","unsplash","user_status","viewer","weather_status","workflow_script","workflowengine"]]},{"file":"/var/www/html/lib/base.php","line":640,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":34,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"61d664c507dbd"}
```

```
{"reqId":"aDKQAPjpmbuz8Vz7W12x","level":4,"time":"2022-01-06T03:40:02+00:00","remoteAddr":"10.0.2.2","user":"--","app":"mail","method":"GET","url":"/index.php/apps/theming/image/background","message":"Error during app service registration: Class \"Horde_Translation\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Error","Message":"Class \"Horde_Translation\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":126,"function":"register","class":"OCA\\Mail\\AppInfo\\Application","type":"->","args":[{"__class__":"OCP\\AppFramework\\Bootstrap\\IRegistrationContext@anonymous\u0000/var/www/html/lib/private/AppFramework/Bootstrap/RegistrationContext.php:106$18e"}]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":82,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[["files","accessibility","activity","apporder","bookmarks","breezedark","bruteforcesettings","calendar","checksum","cloud_federation_api","comments","contacts","contactsinteraction","cospend","dashboard","dav","deck","external","extract","federatedfilesharing","files_downloadactivity","files_external","files_markdown","files_mindmap","files_pdfviewer","files_rightclick","files_sharing","files_trashbin","files_versions","files_videoplayer","firstrunwizard","forms","groupfolders","integration_gitlab","logreader","lookup_server_connector","mail","maps","metadata","music","news","notes","notifications","notify_push","oauth2","ocdownloader","password_policy","passwords","phonetrack","photos","polls","privacy","provisioning_api","recommendations","richdocuments","serverinfo","settings","sharebymail","spreed","ssepush","systemtags","tasks","text","theming","twofactor_backupcodes","twofactor_nextcloud_notification","twofactor_totp","unsplash","user_status","viewer","weather_status","workflow_script","workflowengine"]]},{"file":"/var/www/html/lib/base.php","line":640,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":34,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","Line":126,"CustomMessage":"Error during app service registration: Class \"Horde_Translation\" not found"},"id":"61d664c507d12"}
```

**Comment by xinstein** [comment]
> I did
> 
> ```
> git clone https://github.com/nextcloud/mail.git
> cd mail
> git checkout fix/detect-char-encoding
> cd ..
> chown -R www-data:www-data mail
> ```
> 
> and then I enable mail in nextcloud apps page.
> 
> Error was raised when I enter mails app, and I can't enter nextcloud settings anymore. The nextcloud log is too huge to upload, but I can copy some seemingly relevant messages here:
> 
> ```
> {"reqId":"o1lBfGhQANsvDMeryCH2","level":3,"time":"2022-01-06T03:40:01+00:00","remoteAddr":"10.0.2.2","user":"xavier","app":"index","method":"GET","url":"/settings/user","message":"Class \"Horde_Imap_Client\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Exception","Message":"Class \"Horde_Imap_Client\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\PersonalSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/user"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"Error","Message":"Class \"Horde_Imap_Client\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"newInstanceArgs","class":"ReflectionClass","type":"->","args":[[{"__class__":"OCA\\Mail\\IMAP\\IMAPClientFactory"},{"__class__":"OCA\\Mail\\Db\\MailboxMapper"},{"__class__":"OCA\\Mail\\IMAP\\MailboxSync"},{"__class__":"OCA\\Mail\\IMAP\\FolderMapper"},{"__class__":"OCA\\Mail\\IMAP\\MessageMapper"},{"__class__":"OCA\\Mail\\Db\\MessageMapper"},{"__class__":"OC\\EventDispatcher\\EventDispatcher"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"},{"__class__":"OCA\\Mail\\Db\\TagMapper"},{"__class__":"OCA\\Mail\\Db\\ThreadMapper"}]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Service\\MailManager","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":56,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":182,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":160,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php","line":114,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":127,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":454,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"name":"userFolder","__class__":"ReflectionParameter"},{"name":"accountService","__class__":"ReflectionParameter"},{"name":"attachmentService","__class__":"ReflectionParameter"},"*** sensitive parameter replaced ***",{"name":"imapClientFactory","__class__":"ReflectionParameter"},{"name":"smtpClientFactory","__class__":"ReflectionParameter"},{"name":"eventDispatcher","__class__":"ReflectionParameter"},{"name":"mailboxMapper","__class__":"ReflectionParameter"},{"name":"messageMapper","__class__":"ReflectionParameter"},{"name":"logger","__class__":"ReflectionParameter"},{"name":"performanceLogger","__class__":"ReflectionParameter"}]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Service\\MailTransmission","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":56,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":182,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":160,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php","line":114,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":127,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":454,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"name":"config","__class__":"ReflectionParameter"},{"name":"messageMapper","__class__":"ReflectionParameter"},"*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Service\\AntiSpamService","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"name":"initialStateService","__class__":"ReflectionParameter"},{"name":"provisioningManager","__class__":"ReflectionParameter"},"*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Settings\\AdminSettings","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/ServerContainer.php","line":145,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/Settings/Manager.php","line":170,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/Settings/Manager.php","line":232,"function":"getSettings","class":"OC\\Settings\\Manager","type":"->","args":["admin","overview"]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":90,"function":"getAdminSettings","class":"OC\\Settings\\Manager","type":"->","args":["overview",false]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":123,"function":"formatSections","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":[{"0":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Overview"}],"1":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Server"}],"5":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Sharing"}],"10":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Security"},{"__class__":"OCA\\Files_External\\Settings\\Section"},{"__class__":"OCA\\News\\Settings\\AdminSection"}],"30":[{"__class__":"OCA\\Theming\\Settings\\Section"}],"50":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Groupware"},{"__class__":"OCA\\Passwords\\Settings\\AdminSection"}],"55":[{"__class__":"OCA\\Activity\\Settings\\AdminSection"},{"__class__":"OCA\\External\\Settings\\Section"},{"__class__":"OCA\\WorkflowEngine\\Settings\\Section"}],"70":[{"__class__":"OCA\\Talk\\Settings\\Admin\\Section"},{"__class__":"OCA\\SSEPush\\Settings\\SSEPushSection"}],"75":[{"__class__":"OCA\\Richdocuments\\Settings\\Section"}],"80":[{"__class__":"OCA\\Bookmarks\\Settings\\AdminSection"},{"__class__":"OCA\\Gitlab\\Settings\\AdminSection"},{"__class__":"OCA\\Polls\\Settings\\AdminSection"}],"90":[{"__class__":"OCA\\AppOrder\\Settings\\Section"},{"__class__":"OCA\\GroupFolders\\Settings\\Section"},{"__class__":"OCA\\LogReader\\Settings\\Section"},{"__class__":"OCA\\ServerInfo\\Settings\\AdminSection"}],"98":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Additional"}]},"personal-info","admin","personal",false]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":75,"function":"formatAdminSections","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info",false]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":147,"function":"getNavigationParameters","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/var/www/html/apps/settings/lib/Controller/PersonalSettingsController.php","line":67,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"index","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal-info"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\PersonalSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/user"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","Line":106},"CustomMessage":"--"},"id":"61d664c5080fa"}
> ```
> 
> ```
> {"reqId":"aDKQAPjpmbuz8Vz7W12x","level":3,"time":"2022-01-06T03:40:02+00:00","remoteAddr":"10.0.2.2","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/theming/image/background","message":"include_once(/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php): Failed to open stream: No such file or directory at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Error","Message":"include_once(/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php): Failed to open stream: No such file or directory at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"include_once(/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php): Failed to open stream: No such file or directory","/var/www/html/custom_apps/mail/lib/AppInfo/Application.php",76]},{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"include_once"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":480,"args":["/var/www/html/custom_apps/mail/lib/AppInfo/Application.php"],"function":"include"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":346,"function":"Composer\\Autoload\\includeFile","args":["/var/www/html/custom_apps/mail/lib//AppInfo/Application.php"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":117,"function":"class_exists","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":82,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[["files","accessibility","activity","apporder","bookmarks","breezedark","bruteforcesettings","calendar","checksum","cloud_federation_api","comments","contacts","contactsinteraction","cospend","dashboard","dav","deck","external","extract","federatedfilesharing","files_downloadactivity","files_external","files_markdown","files_mindmap","files_pdfviewer","files_rightclick","files_sharing","files_trashbin","files_versions","files_videoplayer","firstrunwizard","forms","groupfolders","integration_gitlab","logreader","lookup_server_connector","mail","maps","metadata","music","news","notes","notifications","notify_push","oauth2","ocdownloader","password_policy","passwords","phonetrack","photos","polls","privacy","provisioning_api","recommendations","richdocuments","serverinfo","settings","sharebymail","spreed","ssepush","systemtags","tasks","text","theming","twofactor_backupcodes","twofactor_nextcloud_notification","twofactor_totp","unsplash","user_status","viewer","weather_status","workflow_script","workflowengine"]]},{"file":"/var/www/html/lib/base.php","line":640,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":34,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"61d664c507e4c"}
> ```
> 
> ```
> {"reqId":"aDKQAPjpmbuz8Vz7W12x","level":3,"time":"2022-01-06T03:40:02+00:00","remoteAddr":"10.0.2.2","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/theming/image/background","message":"include_once(): Failed opening '/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Error","Message":"include_once(): Failed opening '/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"include_once(): Failed opening '/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps')","/var/www/html/custom_apps/mail/lib/AppInfo/Application.php",76]},{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"include_once"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":480,"args":["/var/www/html/custom_apps/mail/lib/AppInfo/Application.php"],"function":"include"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":346,"function":"Composer\\Autoload\\includeFile","args":["/var/www/html/custom_apps/mail/lib//AppInfo/Application.php"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":117,"function":"class_exists","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":82,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[["files","accessibility","activity","apporder","bookmarks","breezedark","bruteforcesettings","calendar","checksum","cloud_federation_api","comments","contacts","contactsinteraction","cospend","dashboard","dav","deck","external","extract","federatedfilesharing","files_downloadactivity","files_external","files_markdown","files_mindmap","files_pdfviewer","files_rightclick","files_sharing","files_trashbin","files_versions","files_videoplayer","firstrunwizard","forms","groupfolders","integration_gitlab","logreader","lookup_server_connector","mail","maps","metadata","music","news","notes","notifications","notify_push","oauth2","ocdownloader","password_policy","passwords","phonetrack","photos","polls","privacy","provisioning_api","recommendations","richdocuments","serverinfo","settings","sharebymail","spreed","ssepush","systemtags","tasks","text","theming","twofactor_backupcodes","twofactor_nextcloud_notification","twofactor_totp","unsplash","user_status","viewer","weather_status","workflow_script","workflowengine"]]},{"file":"/var/www/html/lib/base.php","line":640,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":34,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"61d664c507dbd"}
> ```
> 
> ```
> {"reqId":"aDKQAPjpmbuz8Vz7W12x","level":4,"time":"2022-01-06T03:40:02+00:00","remoteAddr":"10.0.2.2","user":"--","app":"mail","method":"GET","url":"/index.php/apps/theming/image/background","message":"Error during app service registration: Class \"Horde_Translation\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Error","Message":"Class \"Horde_Translation\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":126,"function":"register","class":"OCA\\Mail\\AppInfo\\Application","type":"->","args":[{"__class__":"OCP\\AppFramework\\Bootstrap\\IRegistrationContext@anonymous\u0000/var/www/html/lib/private/AppFramework/Bootstrap/RegistrationContext.php:106$18e"}]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":82,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[["files","accessibility","activity","apporder","bookmarks","breezedark","bruteforcesettings","calendar","checksum","cloud_federation_api","comments","contacts","contactsinteraction","cospend","dashboard","dav","deck","external","extract","federatedfilesharing","files_downloadactivity","files_external","files_markdown","files_mindmap","files_pdfviewer","files_rightclick","files_sharing","files_trashbin","files_versions","files_videoplayer","firstrunwizard","forms","groupfolders","integration_gitlab","logreader","lookup_server_connector","mail","maps","metadata","music","news","notes","notifications","notify_push","oauth2","ocdownloader","password_policy","passwords","phonetrack","photos","polls","privacy","provisioning_api","recommendations","richdocuments","serverinfo","settings","sharebymail","spreed","ssepush","systemtags","tasks","text","theming","twofactor_backupcodes","twofactor_nextcloud_notification","twofactor_totp","unsplash","user_status","viewer","weather_status","workflow_script","workflowengine"]]},{"file":"/var/www/html/lib/base.php","line":640,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":34,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","Line":126,"CustomMessage":"Error during app service registration: Class \"Horde_Translation\" not found"},"id":"61d664c507d12"}
> ```

Sorry, did I do sth wrong? why is this off-topic?

**Comment by miaulalala** [comment]
> > I did
> > ```
> > git clone https://github.com/nextcloud/mail.git
> > cd mail
> > git checkout fix/detect-char-encoding
> > cd ..
> > chown -R www-data:www-data mail
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then I enable mail in nextcloud apps page.
> > Error was raised when I enter mails app, and I can't enter nextcloud settings anymore. The nextcloud log is too huge to upload, but I can copy some seemingly relevant messages here:
> > ```
> > {"reqId":"o1lBfGhQANsvDMeryCH2","level":3,"time":"2022-01-06T03:40:01+00:00","remoteAddr":"10.0.2.2","user":"xavier","app":"index","method":"GET","url":"/settings/user","message":"Class \"Horde_Imap_Client\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Exception","Message":"Class \"Horde_Imap_Client\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\PersonalSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/user"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"Error","Message":"Class \"Horde_Imap_Client\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"newInstanceArgs","class":"ReflectionClass","type":"->","args":[[{"__class__":"OCA\\Mail\\IMAP\\IMAPClientFactory"},{"__class__":"OCA\\Mail\\Db\\MailboxMapper"},{"__class__":"OCA\\Mail\\IMAP\\MailboxSync"},{"__class__":"OCA\\Mail\\IMAP\\FolderMapper"},{"__class__":"OCA\\Mail\\IMAP\\MessageMapper"},{"__class__":"OCA\\Mail\\Db\\MessageMapper"},{"__class__":"OC\\EventDispatcher\\EventDispatcher"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"},{"__class__":"OCA\\Mail\\Db\\TagMapper"},{"__class__":"OCA\\Mail\\Db\\ThreadMapper"}]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Service\\MailManager","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":56,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":182,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":160,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php","line":114,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":127,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":454,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"name":"userFolder","__class__":"ReflectionParameter"},{"name":"accountService","__class__":"ReflectionParameter"},{"name":"attachmentService","__class__":"ReflectionParameter"},"*** sensitive parameter replaced ***",{"name":"imapClientFactory","__class__":"ReflectionParameter"},{"name":"smtpClientFactory","__class__":"ReflectionParameter"},{"name":"eventDispatcher","__class__":"ReflectionParameter"},{"name":"mailboxMapper","__class__":"ReflectionParameter"},{"name":"messageMapper","__class__":"ReflectionParameter"},{"name":"logger","__class__":"ReflectionParameter"},{"name":"performanceLogger","__class__":"ReflectionParameter"}]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Service\\MailTransmission","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":56,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":182,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":160,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php","line":114,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":127,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":454,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"name":"config","__class__":"ReflectionParameter"},{"name":"messageMapper","__class__":"ReflectionParameter"},"*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Service\\AntiSpamService","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"name":"initialStateService","__class__":"ReflectionParameter"},{"name":"provisioningManager","__class__":"ReflectionParameter"},"*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Settings\\AdminSettings","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/ServerContainer.php","line":145,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/Settings/Manager.php","line":170,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/Settings/Manager.php","line":232,"function":"getSettings","class":"OC\\Settings\\Manager","type":"->","args":["admin","overview"]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":90,"function":"getAdminSettings","class":"OC\\Settings\\Manager","type":"->","args":["overview",false]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":123,"function":"formatSections","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":[{"0":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Overview"}],"1":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Server"}],"5":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Sharing"}],"10":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Security"},{"__class__":"OCA\\Files_External\\Settings\\Section"},{"__class__":"OCA\\News\\Settings\\AdminSection"}],"30":[{"__class__":"OCA\\Theming\\Settings\\Section"}],"50":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Groupware"},{"__class__":"OCA\\Passwords\\Settings\\AdminSection"}],"55":[{"__class__":"OCA\\Activity\\Settings\\AdminSection"},{"__class__":"OCA\\External\\Settings\\Section"},{"__class__":"OCA\\WorkflowEngine\\Settings\\Section"}],"70":[{"__class__":"OCA\\Talk\\Settings\\Admin\\Section"},{"__class__":"OCA\\SSEPush\\Settings\\SSEPushSection"}],"75":[{"__class__":"OCA\\Richdocuments\\Settings\\Section"}],"80":[{"__class__":"OCA\\Bookmarks\\Settings\\AdminSection"},{"__class__":"OCA\\Gitlab\\Settings\\AdminSection"},{"__class__":"OCA\\Polls\\Settings\\AdminSection"}],"90":[{"__class__":"OCA\\AppOrder\\Settings\\Section"},{"__class__":"OCA\\GroupFolders\\Settings\\Section"},{"__class__":"OCA\\LogReader\\Settings\\Section"},{"__class__":"OCA\\ServerInfo\\Settings\\AdminSection"}],"98":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Additional"}]},"personal-info","admin","personal",false]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":75,"function":"formatAdminSections","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info",false]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":147,"function":"getNavigationParameters","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/var/www/html/apps/settings/lib/Controller/PersonalSettingsController.php","line":67,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"index","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal-info"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\PersonalSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/user"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","Line":106},"CustomMessage":"--"},"id":"61d664c5080fa"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > {"reqId":"aDKQAPjpmbuz8Vz7W12x","level":3,"time":"2022-01-06T03:40:02+00:00","remoteAddr":"10.0.2.2","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/theming/image/background","message":"include_once(/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php): Failed to open stream: No such file or directory at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Error","Message":"include_once(/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php): Failed to open stream: No such file or directory at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"include_once(/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php): Failed to open stream: No such file or directory","/var/www/html/custom_apps/mail/lib/AppInfo/Application.php",76]},{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"include_once"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":480,"args":["/var/www/html/custom_apps/mail/lib/AppInfo/Application.php"],"function":"include"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":346,"function":"Composer\\Autoload\\includeFile","args":["/var/www/html/custom_apps/mail/lib//AppInfo/Application.php"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":117,"function":"class_exists","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":82,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[["files","accessibility","activity","apporder","bookmarks","breezedark","bruteforcesettings","calendar","checksum","cloud_federation_api","comments","contacts","contactsinteraction","cospend","dashboard","dav","deck","external","extract","federatedfilesharing","files_downloadactivity","files_external","files_markdown","files_mindmap","files_pdfviewer","files_rightclick","files_sharing","files_trashbin","files_versions","files_videoplayer","firstrunwizard","forms","groupfolders","integration_gitlab","logreader","lookup_server_connector","mail","maps","metadata","music","news","notes","notifications","notify_push","oauth2","ocdownloader","password_policy","passwords","phonetrack","photos","polls","privacy","provisioning_api","recommendations","richdocuments","serverinfo","settings","sharebymail","spreed","ssepush","systemtags","tasks","text","theming","twofactor_backupcodes","twofactor_nextcloud_notification","twofactor_totp","unsplash","user_status","viewer","weather_status","workflow_script","workflowengine"]]},{"file":"/var/www/html/lib/base.php","line":640,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":34,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"61d664c507e4c"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > {"reqId":"aDKQAPjpmbuz8Vz7W12x","level":3,"time":"2022-01-06T03:40:02+00:00","remoteAddr":"10.0.2.2","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/theming/image/background","message":"include_once(): Failed opening '/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Error","Message":"include_once(): Failed opening '/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"include_once(): Failed opening '/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps')","/var/www/html/custom_apps/mail/lib/AppInfo/Application.php",76]},{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"include_once"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":480,"args":["/var/www/html/custom_apps/mail/lib/AppInfo/Application.php"],"function":"include"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":346,"function":"Composer\\Autoload\\includeFile","args":["/var/www/html/custom_apps/mail/lib//AppInfo/Application.php"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":117,"function":"class_exists","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":82,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[["files","accessibility","activity","apporder","bookmarks","breezedark","bruteforcesettings","calendar","checksum","cloud_federation_api","comments","contacts","contactsinteraction","cospend","dashboard","dav","deck","external","extract","federatedfilesharing","files_downloadactivity","files_external","files_markdown","files_mindmap","files_pdfviewer","files_rightclick","files_sharing","files_trashbin","files_versions","files_videoplayer","firstrunwizard","forms","groupfolders","integration_gitlab","logreader","lookup_server_connector","mail","maps","metadata","music","news","notes","notifications","notify_push","oauth2","ocdownloader","password_policy","passwords","phonetrack","photos","polls","privacy","provisioning_api","recommendations","richdocuments","serverinfo","settings","sharebymail","spreed","ssepush","systemtags","tasks","text","theming","twofactor_backupcodes","twofactor_nextcloud_notification","twofactor_totp","unsplash","user_status","viewer","weather_status","workflow_script","workflowengine"]]},{"file":"/var/www/html/lib/base.php","line":640,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":34,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"61d664c507dbd"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > {"reqId":"aDKQAPjpmbuz8Vz7W12x","level":4,"time":"2022-01-06T03:40:02+00:00","remoteAddr":"10.0.2.2","user":"--","app":"mail","method":"GET","url":"/index.php/apps/theming/image/background","message":"Error during app service registration: Class \"Horde_Translation\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Error","Message":"Class \"Horde_Translation\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":126,"function":"register","class":"OCA\\Mail\\AppInfo\\Application","type":"->","args":[{"__class__":"OCP\\AppFramework\\Bootstrap\\IRegistrationContext@anonymous\u0000/var/www/html/lib/private/AppFramework/Bootstrap/RegistrationContext.php:106$18e"}]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":82,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[["files","accessibility","activity","apporder","bookmarks","breezedark","bruteforcesettings","calendar","checksum","cloud_federation_api","comments","contacts","contactsinteraction","cospend","dashboard","dav","deck","external","extract","federatedfilesharing","files_downloadactivity","files_external","files_markdown","files_mindmap","files_pdfviewer","files_rightclick","files_sharing","files_trashbin","files_versions","files_videoplayer","firstrunwizard","forms","groupfolders","integration_gitlab","logreader","lookup_server_connector","mail","maps","metadata","music","news","notes","notifications","notify_push","oauth2","ocdownloader","password_policy","passwords","phonetrack","photos","polls","privacy","provisioning_api","recommendations","richdocuments","serverinfo","settings","sharebymail","spreed","ssepush","systemtags","tasks","text","theming","twofactor_backupcodes","twofactor_nextcloud_notification","twofactor_totp","unsplash","user_status","viewer","weather_status","workflow_script","workflowengine"]]},{"file":"/var/www/html/lib/base.php","line":640,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":34,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","Line":126,"CustomMessage":"Error during app service registration: Class \"Horde_Translation\" not found"},"id":"61d664c507d12"}
> > ```
> 
> Sorry, did I do sth wrong? why is this off-topic? With the newest code, the above error messages still appear. I can't test this pr, maybe I did sth wrong

Hey sorry, I should have been clearer. Your errors aren't actually from the fix, but you're missing dependencies. Can you run `composer install` in your mail directory please?

**Comment by xinstein** [comment]
> > > I did
> > > ```
> > > git clone https://github.com/nextcloud/mail.git
> > > cd mail
> > > git checkout fix/detect-char-encoding
> > > cd ..
> > > chown -R www-data:www-data mail
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and then I enable mail in nextcloud apps page.
> > > Error was raised when I enter mails app, and I can't enter nextcloud settings anymore. The nextcloud log is too huge to upload, but I can copy some seemingly relevant messages here:
> > > ```
> > > {"reqId":"o1lBfGhQANsvDMeryCH2","level":3,"time":"2022-01-06T03:40:01+00:00","remoteAddr":"10.0.2.2","user":"xavier","app":"index","method":"GET","url":"/settings/user","message":"Class \"Horde_Imap_Client\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Exception","Message":"Class \"Horde_Imap_Client\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\PersonalSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/user"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"Error","Message":"Class \"Horde_Imap_Client\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"newInstanceArgs","class":"ReflectionClass","type":"->","args":[[{"__class__":"OCA\\Mail\\IMAP\\IMAPClientFactory"},{"__class__":"OCA\\Mail\\Db\\MailboxMapper"},{"__class__":"OCA\\Mail\\IMAP\\MailboxSync"},{"__class__":"OCA\\Mail\\IMAP\\FolderMapper"},{"__class__":"OCA\\Mail\\IMAP\\MessageMapper"},{"__class__":"OCA\\Mail\\Db\\MessageMapper"},{"__class__":"OC\\EventDispatcher\\EventDispatcher"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"},{"__class__":"OCA\\Mail\\Db\\TagMapper"},{"__class__":"OCA\\Mail\\Db\\ThreadMapper"}]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Service\\MailManager","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":56,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":182,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":160,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php","line":114,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":127,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":454,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"name":"userFolder","__class__":"ReflectionParameter"},{"name":"accountService","__class__":"ReflectionParameter"},{"name":"attachmentService","__class__":"ReflectionParameter"},"*** sensitive parameter replaced ***",{"name":"imapClientFactory","__class__":"ReflectionParameter"},{"name":"smtpClientFactory","__class__":"ReflectionParameter"},{"name":"eventDispatcher","__class__":"ReflectionParameter"},{"name":"mailboxMapper","__class__":"ReflectionParameter"},{"name":"messageMapper","__class__":"ReflectionParameter"},{"name":"logger","__class__":"ReflectionParameter"},{"name":"performanceLogger","__class__":"ReflectionParameter"}]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Service\\MailTransmission","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":56,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":182,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":160,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php","line":114,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":127,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":454,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"name":"config","__class__":"ReflectionParameter"},{"name":"messageMapper","__class__":"ReflectionParameter"},"*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Service\\AntiSpamService","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"name":"initialStateService","__class__":"ReflectionParameter"},{"name":"provisioningManager","__class__":"ReflectionParameter"},"*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Settings\\AdminSettings","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/ServerContainer.php","line":145,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/Settings/Manager.php","line":170,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/Settings/Manager.php","line":232,"function":"getSettings","class":"OC\\Settings\\Manager","type":"->","args":["admin","overview"]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":90,"function":"getAdminSettings","class":"OC\\Settings\\Manager","type":"->","args":["overview",false]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":123,"function":"formatSections","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":[{"0":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Overview"}],"1":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Server"}],"5":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Sharing"}],"10":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Security"},{"__class__":"OCA\\Files_External\\Settings\\Section"},{"__class__":"OCA\\News\\Settings\\AdminSection"}],"30":[{"__class__":"OCA\\Theming\\Settings\\Section"}],"50":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Groupware"},{"__class__":"OCA\\Passwords\\Settings\\AdminSection"}],"55":[{"__class__":"OCA\\Activity\\Settings\\AdminSection"},{"__class__":"OCA\\External\\Settings\\Section"},{"__class__":"OCA\\WorkflowEngine\\Settings\\Section"}],"70":[{"__class__":"OCA\\Talk\\Settings\\Admin\\Section"},{"__class__":"OCA\\SSEPush\\Settings\\SSEPushSection"}],"75":[{"__class__":"OCA\\Richdocuments\\Settings\\Section"}],"80":[{"__class__":"OCA\\Bookmarks\\Settings\\AdminSection"},{"__class__":"OCA\\Gitlab\\Settings\\AdminSection"},{"__class__":"OCA\\Polls\\Settings\\AdminSection"}],"90":[{"__class__":"OCA\\AppOrder\\Settings\\Section"},{"__class__":"OCA\\GroupFolders\\Settings\\Section"},{"__class__":"OCA\\LogReader\\Settings\\Section"},{"__class__":"OCA\\ServerInfo\\Settings\\AdminSection"}],"98":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Additional"}]},"personal-info","admin","personal",false]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":75,"function":"formatAdminSections","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info",false]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":147,"function":"getNavigationParameters","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/var/www/html/apps/settings/lib/Controller/PersonalSettingsController.php","line":67,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"index","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal-info"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\PersonalSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/user"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","Line":106},"CustomMessage":"--"},"id":"61d664c5080fa"}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > {"reqId":"aDKQAPjpmbuz8Vz7W12x","level":3,"time":"2022-01-06T03:40:02+00:00","remoteAddr":"10.0.2.2","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/theming/image/background","message":"include_once(/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php): Failed to open stream: No such file or directory at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Error","Message":"include_once(/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php): Failed to open stream: No such file or directory at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"include_once(/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php): Failed to open stream: No such file or directory","/var/www/html/custom_apps/mail/lib/AppInfo/Application.php",76]},{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"include_once"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":480,"args":["/var/www/html/custom_apps/mail/lib/AppInfo/Application.php"],"function":"include"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":346,"function":"Composer\\Autoload\\includeFile","args":["/var/www/html/custom_apps/mail/lib//AppInfo/Application.php"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":117,"function":"class_exists","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":82,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[["files","accessibility","activity","apporder","bookmarks","breezedark","bruteforcesettings","calendar","checksum","cloud_federation_api","comments","contacts","contactsinteraction","cospend","dashboard","dav","deck","external","extract","federatedfilesharing","files_downloadactivity","files_external","files_markdown","files_mindmap","files_pdfviewer","files_rightclick","files_sharing","files_trashbin","files_versions","files_videoplayer","firstrunwizard","forms","groupfolders","integration_gitlab","logreader","lookup_server_connector","mail","maps","metadata","music","news","notes","notifications","notify_push","oauth2","ocdownloader","password_policy","passwords","phonetrack","photos","polls","privacy","provisioning_api","recommendations","richdocuments","serverinfo","settings","sharebymail","spreed","ssepush","systemtags","tasks","text","theming","twofactor_backupcodes","twofactor_nextcloud_notification","twofactor_totp","unsplash","user_status","viewer","weather_status","workflow_script","workflowengine"]]},{"file":"/var/www/html/lib/base.php","line":640,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":34,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"61d664c507e4c"}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > {"reqId":"aDKQAPjpmbuz8Vz7W12x","level":3,"time":"2022-01-06T03:40:02+00:00","remoteAddr":"10.0.2.2","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/theming/image/background","message":"include_once(): Failed opening '/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Error","Message":"include_once(): Failed opening '/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"include_once(): Failed opening '/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps')","/var/www/html/custom_apps/mail/lib/AppInfo/Application.php",76]},{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"include_once"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":480,"args":["/var/www/html/custom_apps/mail/lib/AppInfo/Application.php"],"function":"include"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":346,"function":"Composer\\Autoload\\includeFile","args":["/var/www/html/custom_apps/mail/lib//AppInfo/Application.php"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":117,"function":"class_exists","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":82,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[["files","accessibility","activity","apporder","bookmarks","breezedark","bruteforcesettings","calendar","checksum","cloud_federation_api","comments","contacts","contactsinteraction","cospend","dashboard","dav","deck","external","extract","federatedfilesharing","files_downloadactivity","files_external","files_markdown","files_mindmap","files_pdfviewer","files_rightclick","files_sharing","files_trashbin","files_versions","files_videoplayer","firstrunwizard","forms","groupfolders","integration_gitlab","logreader","lookup_server_connector","mail","maps","metadata","music","news","notes","notifications","notify_push","oauth2","ocdownloader","password_policy","passwords","phonetrack","photos","polls","privacy","provisioning_api","recommendations","richdocuments","serverinfo","settings","sharebymail","spreed","ssepush","systemtags","tasks","text","theming","twofactor_backupcodes","twofactor_nextcloud_notification","twofactor_totp","unsplash","user_status","viewer","weather_status","workflow_script","workflowengine"]]},{"file":"/var/www/html/lib/base.php","line":640,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":34,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"61d664c507dbd"}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > {"reqId":"aDKQAPjpmbuz8Vz7W12x","level":4,"time":"2022-01-06T03:40:02+00:00","remoteAddr":"10.0.2.2","user":"--","app":"mail","method":"GET","url":"/index.php/apps/theming/image/background","message":"Error during app service registration: Class \"Horde_Translation\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Error","Message":"Class \"Horde_Translation\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":126,"function":"register","class":"OCA\\Mail\\AppInfo\\Application","type":"->","args":[{"__class__":"OCP\\AppFramework\\Bootstrap\\IRegistrationContext@anonymous\u0000/var/www/html/lib/private/AppFramework/Bootstrap/RegistrationContext.php:106$18e"}]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":82,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[["files","accessibility","activity","apporder","bookmarks","breezedark","bruteforcesettings","calendar","checksum","cloud_federation_api","comments","contacts","contactsinteraction","cospend","dashboard","dav","deck","external","extract","federatedfilesharing","files_downloadactivity","files_external","files_markdown","files_mindmap","files_pdfviewer","files_rightclick","files_sharing","files_trashbin","files_versions","files_videoplayer","firstrunwizard","forms","groupfolders","integration_gitlab","logreader","lookup_server_connector","mail","maps","metadata","music","news","notes","notifications","notify_push","oauth2","ocdownloader","password_policy","passwords","phonetrack","photos","polls","privacy","provisioning_api","recommendations","richdocuments","serverinfo","settings","sharebymail","spreed","ssepush","systemtags","tasks","text","theming","twofactor_backupcodes","twofactor_nextcloud_notification","twofactor_totp","unsplash","user_status","viewer","weather_status","workflow_script","workflowengine"]]},{"file":"/var/www/html/lib/base.php","line":640,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":34,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","Line":126,"CustomMessage":"Error during app service registration: Class \"Horde_Translation\" not found"},"id":"61d664c507d12"}
> > > ```
> > 
> > 
> > Sorry, did I do sth wrong? why is this off-topic? With the newest code, the above error messages still appear. I can't test this pr, maybe I did sth wrong
> 
> Hey sorry, I should have been clearer. Your errors aren't actually from the fix, but you're missing dependencies. Can you run `composer install` in your mail directory please?

Thank you, my nextcloud instance is a docker container, I can't find a composer executable inside the container.  I usually use occ app:install to install apps, is `compose install` called as a post-install hook in this case? 

Sorry for my unfamiliarity with php

**Review by st3iny — COMMENTED** [review]
Throws an error `Could not detect charset for message` on a harmless message that worked fined before.


[Test email](https://steinmetz.cloud/s/2YCm5XLiYPo93mT) as sent from Thunderbird. It contains an image from Unsplash. I could reproduce it using other images too so this seems to be an issue with attached images.

<details>
  <summary>Error from the console</summary>

```json
{
  "app": "mail",
  "uid": "admin",
  "error": {
    "isError": true,
    "debug": true,
    "type": "OCA\\Mail\\Exception\\ServiceException",
    "code": 0,
    "message": "Could not detect charset for message",
    "trace": [
      {
        "file": "/srv/http/dev_apps/mail/lib/Model/IMAPMessage.php",
        "line": 566,
        "function": "loadBodyData",
        "class": "OCA\\Mail\\Model\\IMAPMessage"
      },
      {
        "file": "/srv/http/dev_apps/mail/lib/Model/IMAPMessage.php",
        "line": 437,
        "function": "handleTextMessage",
        "class": "OCA\\Mail\\Model\\IMAPMessage"
      },
      {
        "file": "/srv/http/dev_apps/mail/lib/Model/IMAPMessage.php",
        "line": 377,
        "function": "getPart",
        "class": "OCA\\Mail\\Model\\IMAPMessage"
      },
      {
        "file": "/srv/http/dev_apps/mail/lib/Model/IMAPMessage.php",
        "line": 102,
        "function": "loadMessageBodies",
        "class": "OCA\\Mail\\Model\\IMAPMessage"
      },
      {
        "file": "/srv/http/dev_apps/mail/lib/IMAP/MessageMapper.php",
        "line": 242,
        "function": "__construct",
        "class": "OCA\\Mail\\Model\\IMAPMessage"
      },
      {
        "function": "OCA\\Mail\\IMAP\\{closure}",
        "class": "OCA\\Mail\\IMAP\\MessageMapper"
      },
      {
        "file": "/srv/http/dev_apps/mail/lib/IMAP/MessageMapper.php",
        "line": 256,
        "function": "array_map"
      },
      {
        "file": "/srv/http/dev_apps/mail/lib/IMAP/MessageMapper.php",
        "line": 69,
        "function": "findByIds",
        "class": "OCA\\Mail\\IMAP\\MessageMapper"
      },
      {
        "file": "/srv/http/dev_apps/mail/lib/Service/MailManager.php",
        "line": 180,
        "function": "find",
        "class": "OCA\\Mail\\IMAP\\MessageMapper"
      },
      {
        "file": "/srv/http/dev_apps/mail/lib/Controller/MessagesController.php",
        "line": 249,
        "function": "getImapMessage",
        "class": "OCA\\Mail\\Service\\MailManager"
      },
      {
        "file": "/srv/http/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 217,
        "function": "getBody",
        "class": "OCA\\Mail\\Controller\\MessagesController"
      },
      {
        "file": "/srv/http/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 126,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher"
      },
      {
        "file": "/srv/http/lib/private/AppFramework/App.php",
        "line": 157,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher"
      },
      {
        "file": "/srv/http/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App"
      },
      {
        "file": "/srv/http/lib/base.php",
        "line": 1006,
        "function": "match",
        "class": "OC\\Route\\Router"
      },
      {
        "file": "/srv/http/index.php",
        "line": 36,
        "function": "handleRequest",
        "class": "OC"
      }
    ]
  }
}
```

</details>

**Comment by miaulalala** [comment]
> > > > I did
> > > > ```
> > > > git clone https://github.com/nextcloud/mail.git
> > > > cd mail
> > > > git checkout fix/detect-char-encoding
> > > > cd ..
> > > > chown -R www-data:www-data mail
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > and then I enable mail in nextcloud apps page.
> > > > Error was raised when I enter mails app, and I can't enter nextcloud settings anymore. The nextcloud log is too huge to upload, but I can copy some seemingly relevant messages here:
> > > > ```
> > > > {"reqId":"o1lBfGhQANsvDMeryCH2","level":3,"time":"2022-01-06T03:40:01+00:00","remoteAddr":"10.0.2.2","user":"xavier","app":"index","method":"GET","url":"/settings/user","message":"Class \"Horde_Imap_Client\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Exception","Message":"Class \"Horde_Imap_Client\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\PersonalSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/user"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"Error","Message":"Class \"Horde_Imap_Client\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"newInstanceArgs","class":"ReflectionClass","type":"->","args":[[{"__class__":"OCA\\Mail\\IMAP\\IMAPClientFactory"},{"__class__":"OCA\\Mail\\Db\\MailboxMapper"},{"__class__":"OCA\\Mail\\IMAP\\MailboxSync"},{"__class__":"OCA\\Mail\\IMAP\\FolderMapper"},{"__class__":"OCA\\Mail\\IMAP\\MessageMapper"},{"__class__":"OCA\\Mail\\Db\\MessageMapper"},{"__class__":"OC\\EventDispatcher\\EventDispatcher"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"},{"__class__":"OCA\\Mail\\Db\\TagMapper"},{"__class__":"OCA\\Mail\\Db\\ThreadMapper"}]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Service\\MailManager","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":56,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":182,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":160,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php","line":114,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":127,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":454,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailManager",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"name":"userFolder","__class__":"ReflectionParameter"},{"name":"accountService","__class__":"ReflectionParameter"},{"name":"attachmentService","__class__":"ReflectionParameter"},"*** sensitive parameter replaced ***",{"name":"imapClientFactory","__class__":"ReflectionParameter"},{"name":"smtpClientFactory","__class__":"ReflectionParameter"},{"name":"eventDispatcher","__class__":"ReflectionParameter"},{"name":"mailboxMapper","__class__":"ReflectionParameter"},{"name":"messageMapper","__class__":"ReflectionParameter"},{"name":"logger","__class__":"ReflectionParameter"},{"name":"performanceLogger","__class__":"ReflectionParameter"}]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Service\\MailTransmission","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":56,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":182,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\MailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":160,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php","line":114,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":127,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":454,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Contracts\\IMailTransmission",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"name":"config","__class__":"ReflectionParameter"},{"name":"messageMapper","__class__":"ReflectionParameter"},"*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Service\\AntiSpamService","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":432,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Service\\AntiSpamService",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"name":"initialStateService","__class__":"ReflectionParameter"},{"name":"provisioningManager","__class__":"ReflectionParameter"},"*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Mail\\Settings\\AdminSettings","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/ServerContainer.php","line":145,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/Settings/Manager.php","line":170,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCA\\Mail\\Settings\\AdminSettings"]},{"file":"/var/www/html/lib/private/Settings/Manager.php","line":232,"function":"getSettings","class":"OC\\Settings\\Manager","type":"->","args":["admin","overview"]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":90,"function":"getAdminSettings","class":"OC\\Settings\\Manager","type":"->","args":["overview",false]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":123,"function":"formatSections","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":[{"0":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Overview"}],"1":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Server"}],"5":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Sharing"}],"10":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Security"},{"__class__":"OCA\\Files_External\\Settings\\Section"},{"__class__":"OCA\\News\\Settings\\AdminSection"}],"30":[{"__class__":"OCA\\Theming\\Settings\\Section"}],"50":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Groupware"},{"__class__":"OCA\\Passwords\\Settings\\AdminSection"}],"55":[{"__class__":"OCA\\Activity\\Settings\\AdminSection"},{"__class__":"OCA\\External\\Settings\\Section"},{"__class__":"OCA\\WorkflowEngine\\Settings\\Section"}],"70":[{"__class__":"OCA\\Talk\\Settings\\Admin\\Section"},{"__class__":"OCA\\SSEPush\\Settings\\SSEPushSection"}],"75":[{"__class__":"OCA\\Richdocuments\\Settings\\Section"}],"80":[{"__class__":"OCA\\Bookmarks\\Settings\\AdminSection"},{"__class__":"OCA\\Gitlab\\Settings\\AdminSection"},{"__class__":"OCA\\Polls\\Settings\\AdminSection"}],"90":[{"__class__":"OCA\\AppOrder\\Settings\\Section"},{"__class__":"OCA\\GroupFolders\\Settings\\Section"},{"__class__":"OCA\\LogReader\\Settings\\Section"},{"__class__":"OCA\\ServerInfo\\Settings\\AdminSection"}],"98":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Additional"}]},"personal-info","admin","personal",false]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":75,"function":"formatAdminSections","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info",false]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":147,"function":"getNavigationParameters","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/var/www/html/apps/settings/lib/Controller/PersonalSettingsController.php","line":67,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"index","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal-info"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\PersonalSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/user"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","Line":106},"CustomMessage":"--"},"id":"61d664c5080fa"}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ```
> > > > {"reqId":"aDKQAPjpmbuz8Vz7W12x","level":3,"time":"2022-01-06T03:40:02+00:00","remoteAddr":"10.0.2.2","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/theming/image/background","message":"include_once(/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php): Failed to open stream: No such file or directory at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Error","Message":"include_once(/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php): Failed to open stream: No such file or directory at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"include_once(/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php): Failed to open stream: No such file or directory","/var/www/html/custom_apps/mail/lib/AppInfo/Application.php",76]},{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"include_once"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":480,"args":["/var/www/html/custom_apps/mail/lib/AppInfo/Application.php"],"function":"include"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":346,"function":"Composer\\Autoload\\includeFile","args":["/var/www/html/custom_apps/mail/lib//AppInfo/Application.php"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":117,"function":"class_exists","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":82,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[["files","accessibility","activity","apporder","bookmarks","breezedark","bruteforcesettings","calendar","checksum","cloud_federation_api","comments","contacts","contactsinteraction","cospend","dashboard","dav","deck","external","extract","federatedfilesharing","files_downloadactivity","files_external","files_markdown","files_mindmap","files_pdfviewer","files_rightclick","files_sharing","files_trashbin","files_versions","files_videoplayer","firstrunwizard","forms","groupfolders","integration_gitlab","logreader","lookup_server_connector","mail","maps","metadata","music","news","notes","notifications","notify_push","oauth2","ocdownloader","password_policy","passwords","phonetrack","photos","polls","privacy","provisioning_api","recommendations","richdocuments","serverinfo","settings","sharebymail","spreed","ssepush","systemtags","tasks","text","theming","twofactor_backupcodes","twofactor_nextcloud_notification","twofactor_totp","unsplash","user_status","viewer","weather_status","workflow_script","workflowengine"]]},{"file":"/var/www/html/lib/base.php","line":640,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":34,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"61d664c507e4c"}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ```
> > > > {"reqId":"aDKQAPjpmbuz8Vz7W12x","level":3,"time":"2022-01-06T03:40:02+00:00","remoteAddr":"10.0.2.2","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/theming/image/background","message":"include_once(): Failed opening '/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Error","Message":"include_once(): Failed opening '/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') at /var/www/html/custom_apps/mail/lib/AppInfo/Application.php#76","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"include_once(): Failed opening '/var/www/html/custom_apps/mail/lib/AppInfo/../../vendor/autoload.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps')","/var/www/html/custom_apps/mail/lib/AppInfo/Application.php",76]},{"file":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","line":76,"function":"include_once"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":480,"args":["/var/www/html/custom_apps/mail/lib/AppInfo/Application.php"],"function":"include"},{"file":"/var/www/html/lib/composer/composer/ClassLoader.php","line":346,"function":"Composer\\Autoload\\includeFile","args":["/var/www/html/custom_apps/mail/lib//AppInfo/Application.php"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":117,"function":"class_exists","args":["OCA\\Mail\\AppInfo\\Application"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":82,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[["files","accessibility","activity","apporder","bookmarks","breezedark","bruteforcesettings","calendar","checksum","cloud_federation_api","comments","contacts","contactsinteraction","cospend","dashboard","dav","deck","external","extract","federatedfilesharing","files_downloadactivity","files_external","files_markdown","files_mindmap","files_pdfviewer","files_rightclick","files_sharing","files_trashbin","files_versions","files_videoplayer","firstrunwizard","forms","groupfolders","integration_gitlab","logreader","lookup_server_connector","mail","maps","metadata","music","news","notes","notifications","notify_push","oauth2","ocdownloader","password_policy","passwords","phonetrack","photos","polls","privacy","provisioning_api","recommendations","richdocuments","serverinfo","settings","sharebymail","spreed","ssepush","systemtags","tasks","text","theming","twofactor_backupcodes","twofactor_nextcloud_notification","twofactor_totp","unsplash","user_status","viewer","weather_status","workflow_script","workflowengine"]]},{"file":"/var/www/html/lib/base.php","line":640,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":34,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"61d664c507dbd"}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ```
> > > > {"reqId":"aDKQAPjpmbuz8Vz7W12x","level":4,"time":"2022-01-06T03:40:02+00:00","remoteAddr":"10.0.2.2","user":"--","app":"mail","method":"GET","url":"/index.php/apps/theming/image/background","message":"Error during app service registration: Class \"Horde_Translation\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0","exception":{"Exception":"Error","Message":"Class \"Horde_Translation\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":126,"function":"register","class":"OCA\\Mail\\AppInfo\\Application","type":"->","args":[{"__class__":"OCP\\AppFramework\\Bootstrap\\IRegistrationContext@anonymous\u0000/var/www/html/lib/private/AppFramework/Bootstrap/RegistrationContext.php:106$18e"}]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":82,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[["files","accessibility","activity","apporder","bookmarks","breezedark","bruteforcesettings","calendar","checksum","cloud_federation_api","comments","contacts","contactsinteraction","cospend","dashboard","dav","deck","external","extract","federatedfilesharing","files_downloadactivity","files_external","files_markdown","files_mindmap","files_pdfviewer","files_rightclick","files_sharing","files_trashbin","files_versions","files_videoplayer","firstrunwizard","forms","groupfolders","integration_gitlab","logreader","lookup_server_connector","mail","maps","metadata","music","news","notes","notifications","notify_push","oauth2","ocdownloader","password_policy","passwords","phonetrack","photos","polls","privacy","provisioning_api","recommendations","richdocuments","serverinfo","settings","sharebymail","spreed","ssepush","systemtags","tasks","text","theming","twofactor_backupcodes","twofactor_nextcloud_notification","twofactor_totp","unsplash","user_status","viewer","weather_status","workflow_script","workflowengine"]]},{"file":"/var/www/html/lib/base.php","line":640,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":34,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/custom_apps/mail/lib/AppInfo/Application.php","Line":126,"CustomMessage":"Error during app service registration: Class \"Horde_Translation\" not found"},"id":"61d664c507d12"}
> > > > ```
> > > 
> > > 
> > > Sorry, did I do sth wrong? why is this off-topic? With the newest code, the above error messages still appear. I can't test this pr, maybe I did sth wrong
> > 
> > 
> > Hey sorry, I should have been clearer. Your errors aren't actually from the fix, but you're missing dependencies. Can you run `composer install` in your mail directory please?
> 
> Thank you, my nextcloud instance is a docker container, I can't find a composer executable inside the container. I usually use occ app:install to install apps, is `compose install` called as a post-install hook in this case?
> 
> Sorry for my unfamiliarity with php

No worries, just open a ticket please and don't comment here as it's got nothing to do with this PR :)

**Comment by miaulalala** [comment]
> Throws an error `Could not detect charset for message` on a harmless message that worked fined before.
> 
> [Test email](https://steinmetz.cloud/s/2YCm5XLiYPo93mT) as sent from Thunderbird. It contains an image from Unsplash. I could reproduce it using other images too so this seems to be an issue with attached images.
> 
> Error from the console

Ah interesting. Attached, not embedded as base64?

**Comment by st3iny** [comment]
> > Throws an error `Could not detect charset for message` on a harmless message that worked fined before.
> > [Test email](https://steinmetz.cloud/s/2YCm5XLiYPo93mT) as sent from Thunderbird. It contains an image from Unsplash. I could reproduce it using other images too so this seems to be an issue with attached images.
> > Error from the console
> 
> Ah interesting. Attached, not embedded as base64?

I added the image as a regular attachment. At least in Thunderbird it detected as an attachment and is not shown inline.

Here is the relevant excerpt from the `.eml`:
```
--------------LrBOmGA0xhgKeGGopkJKdw1w
Content-Type: image/jpeg; name="ilya-bronskiy-__Z8VvhbIZ4-unsplash.jpg"
Content-Disposition: attachment;
 filename="ilya-bronskiy-__Z8VvhbIZ4-unsplash.jpg"
Content-Transfer-Encoding: base64
```

**Comment by miaulalala** [comment]
#1037 is also related

**Comment by miaulalala** [comment]
> > > Throws an error `Could not detect charset for message` on a harmless message that worked fined before.
> > > [Test email](https://steinmetz.cloud/s/2YCm5XLiYPo93mT) as sent from Thunderbird. It contains an image from Unsplash. I could reproduce it using other images too so this seems to be an issue with attached images.
> > > Error from the console
> > 
> > 
> > Ah interesting. Attached, not embedded as base64?
> 
> I added the image as a regular attachment. At least in Thunderbird it is detected as an attachment and is not shown inline.
> 
> Here is the relevant excerpt from the `.eml`:
> 
> ```
> --------------LrBOmGA0xhgKeGGopkJKdw1w
> Content-Type: image/jpeg; name="ilya-bronskiy-__Z8VvhbIZ4-unsplash.jpg"
> Content-Disposition: attachment;
>  filename="ilya-bronskiy-__Z8VvhbIZ4-unsplash.jpg"
> Content-Transfer-Encoding: base64
> ```

Figured it out. PHP implicit bools were fooling me. As the content is `$data = ""` - i. e. an empty string, my boolean check on `!$data` returned a false value even though  `$data` is correct as `""`. Early returns FTW here.

**Comment by roukmoute** [comment]
Would it be possible to use [symfony/unicode](https://symfony.com/doc/current/components/string.html) or [hoa/ustring](https://github.com/hoaproject/Ustring) to avoid encoding problems?

**Review by ChristophWurst — COMMENTED** [review]
This is a bit scary. Let's add tests to cover the edge cases.

:+1: otherwise

**Comment by miaulalala** [comment]
> This is a bit scary. Let's add tests to cover the edge cases.
> 
> 👍 otherwise

Not quite sure how to test this as the complete function chain is private.

**Comment by ChristophWurst** [comment]
> Not quite sure how to test

Move the charset logic into a new class, add unit tests for it and use it in the other complex class.

File: tests/Unit/IMAP/Charset/ConverterTest.php [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+
+	public function dataProviderMimeParts(): array {
+		// UTF8
+		$utfMimePart = new Horde_Mime_Part();
+		$utfMimePart->setType('text/plain');
+		$utfMimePart->setCharset('UTF-8');
+		$utfMimePart->setContents('😊');
+		// Hebrew
+		$iso88591MimePart = new Horde_Mime_Part();
+		$iso88591MimePart->setType('text/plain');
```
Comment (ChristophWurst) [inline tests/Unit/IMAP/Charset/ConverterTest.php:74]: the parts have to be text/* so horde even considers the charset when read back. default parts are application and have no charset

File: lib/IMAP/Charset/Converter.php [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+		// No charset specified
+		$charset = mb_detect_encoding($data, 'UTF-8', true);
+		if (!$charset) {
+			// Fallback
+			$charset = mb_detect_encoding($data, null, true);
+		}
+
+		// Still UTF8, no need to convert
+		if($charset !== null && strtoupper($charset) === 'UTF-8') {
+			return $data;
```
Comment (ChristophWurst) [inline lib/IMAP/Charset/Converter.php:59]: none of the tests is able to reach a line

File: lib/IMAP/Charset/Converter.php [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+
+		// Only convert encoding if it is explicitly specified in the header because text/calendar
+		// data is utf-8 by default.
+		$charset = $p->getCharset();
+		if($charset !== null && strtoupper($charset) === 'UTF-8') {
+			return $data;
+		}
+
+		// No charset specified
+		$charset = mb_detect_encoding($data, 'UTF-8', true);
```
Comment (ChristophWurst) [inline lib/IMAP/Charset/Converter.php:51]: it's because the part's charset is overwritten here except for the case of UTF-8. "No charset specified" is possibly wrong here. The charset might be set but differ from "utf-8".

File: tests/Unit/IMAP/Charset/ConverterTest.php [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+		$iso88591MimePart->setCharset('ISO-8859-1');
+		$iso88591MimePart->setContents(mb_convert_encoding('Ümlaut', 'ISO-8859-1', 'UTF-8'));
```
Comment (ChristophWurst) [inline tests/Unit/IMAP/Charset/ConverterTest.php:61]: test data had to be converted here, or it's always UTF-8

File: tests/Unit/IMAP/Charset/ConverterTest.php [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+		$iso88591MimePart_noCharset->setContents('בה בדף לחבר ממונרכיה, בקר בגרסה ואמנות דת');
+		// Japanese
+		$iso2022jpMimePart = new Horde_Mime_Part();
+		$iso2022jpMimePart->setType('text/plain');
+		$iso2022jpMimePart->setCharset('ISO-2022-JP');
+		$iso2022jpMimePart->setContents(mb_convert_encoding('外せ園査リツハワ題', 'ISO-2022-JP', 'UTF-8'));
+		$iso2022jpMimePart_noCharset = new Horde_Mime_Part();
+		$iso2022jpMimePart_noCharset->setContents('外せ園査リツハワ題');
+		// Korean - not in mb nor iconv
+		// $iso106461MimePart = new Horde_Mime_Part();
```
Comment (ChristophWurst) [inline tests/Unit/IMAP/Charset/ConverterTest.php:72]: ISO 10646-1 is impossible to get working for me. The coding is not mentioned in any report. Can we skip this?

File: lib/IMAP/Charset/Converter.php (hunk 3 above)
Comment (ChristophWurst) [reply lib/IMAP/Charset/Converter.php:72]: this is still the case. either the charset parameter is set and used, or mb detects the string as UTF-8

File: lib/IMAP/Charset/Converter.php [hunk 7]
```diff
@@ -0,0 +1,86 @@
+<?php
+/*
+ * *
+ *  *
+ *  * @copyright 2023 Anna Larch <anna.larch@gmx.net>
```
Comment (ChristophWurst) [inline lib/IMAP/Charset/Converter.php:5]: license header is invalid

**Review by ChristophWurst — COMMENTED** [review]
:+1: we can get this in

**Review by ChristophWurst — APPROVED** [review]
