### PR TITLE
fix(Composer): rtl support

### LINKED ISSUE #10224: [RTL] Buttons should go to the left
### Steps to reproduce

Image

### Expected behavior

Bad design

### Actual behavior

bad ux 

### Mail app version

_No response_

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by hamza221**
fix #10224
Screenshot includes changes at #10337
| b | a |
|--------|--------|
| image | image |

### CODE REVIEW

File: src/components/TextEditor.vue [hunk 1]
```diff
@@ -292,10 +293,7 @@ export default {
 			try {
 				logger.debug(`loading ${language} translations for CKEditor`)
 				await import(
-					/* webpackMode: "lazy-once" */
-					/* webpackPrefetch: true */
-					/* webpackPreload: true */
-					`@ckeditor/ckeditor5-build-decoupled-document/build/translations/${language}`
+					`../../node_modules/@ckeditor/ckeditor5-build-decoupled-document/build/translations/${language}.js`
```
Comment (st3iny) [inline src/components/TextEditor.vue:296]: Revert?

Or was this changed on purpose?

**Review by st3iny — CHANGES_REQUESTED** [review]

File: src/components/TextEditor.vue (hunk 1 above)
Comment (hamza221) [reply src/components/TextEditor.vue:296]: On purpose, for some reason vite is unable to find  `@ckeditor/`

Comment (ChristophWurst) [reply src/components/TextEditor.vue:296]: this should be a separate PR at least. If composer translations are broken we have to backport the fix

Comment (hamza221) [reply src/components/TextEditor.vue:296]: I'll split it
