### PR TITLE
Hide subscribed / unsubscribed checkbox for Infox, Favorites and Sent

### LINKED ISSUE #6296: Unsubscribe option for "Favourites" folder should be hidden
### Steps to reproduce

1. Try unsubscribing from mailbox "Favourites"
2. Frontend gets confused and throws an error

### Expected behavior

No unsubscribe option is offered as it's not a real mailbox.

### Actual behavior

The unsubscribe option is offered and errors out.

### Mail app version

1.11.6

### Mailserver or service

no info

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
fixes #6296

### CODE REVIEW

**Comment by JuliaKirschenheuter** [comment]
Should we also hide subscribed / unsubscribed checkbox for "Inbox" and "Sent" folders? Because it is actually not possible to unsubscribe them, they are always "subscribed".

**Comment by ChristophWurst** [comment]
> Should we also hide subscribed / unsubscribed checkbox for "Inbox" and "Sent" folders? Because it is actually not possible to unsubscribe them, they are always "subscribed".

I'd says yes.

File: src/components/NavigationMailbox.vue [hunk 1]
```diff
@@ -92,7 +92,7 @@
 			</ActionButton>
 
 			<ActionCheckbox
-				v-if="notVirtual"
+				v-if="notVirtual && filter !== 'starred' "
```
Comment (ChristophWurst) [inline src/components/NavigationMailbox.vue:95]: you could also check if `filter` is not undefined. Then this will still work for any other kind of filtered mailbox.

Comment (ChristophWurst) [reply src/components/NavigationMailbox.vue:95]: and you could move the logic into `notVirtual`

The part ``this.mailbox.specialRole !== 'flagged'`` seems to actually target the case you are fixing here. Did we lose the specialRole=flagged on the favorites mailbox?

Comment (JuliaKirschenheuter) [reply src/components/NavigationMailbox.vue]: > you could also check if filter is not undefined. Then this will still work for any other kind of filtered mailbox.

unfortunately it is not working this way

> and you could move the logic into notVirtual

done

> Did we lose the specialRole=flagged on the favorites mailbox?

i think not, or what do you mean? 

new pushed version works

File: src/components/NavigationMailbox.vue [hunk 2]
```diff
@@ -206,7 +206,8 @@ export default {
 			return this.mailbox.name.toLowerCase() !== 'inbox'
 		},
 		notVirtual() {
-			return !this.account.isUnified && this.mailbox.specialRole !== 'flagged'
+			return !this.account.isUnified && this.mailbox.specialRole !== 'flagged' && this.filter !== 'starred'
```
Comment (ChristophWurst) [inline src/components/NavigationMailbox.vue:209]:
```suggestion
			return !this.account.isUnified && this.mailbox.specialRole !== 'flagged' && !!this.filter
```

**Review by ChristophWurst — COMMENTED** [review]
Then this condition will work with any kind of filtered mailbox

File: src/components/NavigationMailbox.vue (hunk 1 above)
Comment (ChristophWurst) [reply src/components/NavigationMailbox.vue]: See https://github.com/nextcloud/mail/pull/6411#pullrequestreview-974926360

**Review by ChristophWurst — APPROVED** [review]
Works right now
