### PR TITLE
Fix PGP/MIME sending and viewing

### LINKED ISSUE #3833: Incoming encrypted mail treated as attachment rather than decrypted.
I have installed and configured mailveloped, authorized the nextcloud domain  and enabled the API. On one of my computers yesterday, I saw it working as expected, on the other, I see that incoming PGP encrypted mail (created with Mailvelope) is always displayed only as an attachment, rather than decrypted. 

### Expected behavior
Tell us what should happen
It should just work™

### Actual behavior

Unbenannt

### Mail app

**Mail app version:** (see apps admin page, e.g. 1.50)

**Mailserver or service:** self-hosted dovecot

### Server configuration

**Operating system**: (e.g. Ubuntu 20.04)

**Web server:** Ningx

**Database:** mariadb

**PHP version:** 7.4

**Nextcloud Version:** 20.0.0

#### Client configuration
**Browser:** Firefox 81

**Operating system:** Debian GNU/Linux Bullseye

### PR DESCRIPTION
**Pull request by pabzm**
This fixes sending and viewing PGP/MIME encrypted emails (as produced and consumed by Mailvelope in API-mode).

Previously, sent messages were viewable in Mailvelope, too, but all other email programs showed the enclosed mime-headers, because the ciphertext was not properly encapsulated.

Closes #3833 and #9862

### CODE REVIEW

**Comment by pabzm** [comment]
This is now ready for review. I don't know if some changes could be done more elegantly, please give me a hint if so.

File: lib/Db/LocalMessage.php [hunk 1]
```diff
@@ -110,6 +112,9 @@ class LocalMessage extends Entity implements JsonSerializable {
 	/** @var int|null */
 	protected $updatedAt;
 
+	/** @var bool */
```
Comment (st3iny) [inline lib/Db/LocalMessage.php:115]:
```suggestion
	/** @var bool|null */
```

**Review by st3iny — APPROVED** [review]
Tested with Mailvelope and Thunderbird and works. Very nice, thanks!

Please bump the version in `appinfo/info.xml` to trigger the migration, e.g. `4.1.0-alpha.1`.
