### PR TITLE
Fix double scrollbar in thread view

### LINKED ISSUE #7521: Double-scrollbar in certain screenresolutions and threads
### Steps to reproduce

1. Open mail
2. open mail with threading
3.

### Expected behavior

Should not show double-scrollbar

### Actual behavior

Shows it

### Mail app version

Latest (dont know, is on c.nc.c)

### Mailserver or service

?

### Operating system

?

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### PR DESCRIPTION
**Pull request by st3iny**
Fix #7521

## Before
before

## After 
[after.webm](https://user-images.githubusercontent.com/1479486/200020022-49352356-3b00-4745-b66e-384d7182b6e7.webm)

### CODE REVIEW

**Comment by st3iny** [comment]
CI failure is not related.

File: src/components/Thread.vue [hunk 1]
```diff
@@ -256,10 +256,7 @@ export default {
 
 <style lang="scss">
 #mail-message {
-	flex-grow: 1;
-	max-height: calc(100vh - 50px);
 	margin-bottom: 30vh;
```
Comment (szaimen) [inline src/components/Thread.vue:259]: why is this needed?

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

File: src/components/Thread.vue (hunk 1 above)
Comment (st3iny) [reply src/components/Thread.vue:259]: The margin was added deliberately to be able to scroll past the last thread. I don't remember anymore but I guess it was feedback from a design review.
