### PR TITLE
Collect `simpexml_load_string` errors and log them to debug

### LINKED ISSUE #5763: simplexml_load_string(): ^ at /apps/mail/lib/Service/AutoConfig/IspDb.php#73
On nextcloud 22.2.3 with Mail 1.11.0.

```
{
  "reqId": "4Rqkk36qpfbe25zO92b6",
  "level": 3,
  "time": "2021-12-01T10:30:57+01:00",
  "user": "cia-example",
  "app": "PHP",
  "method": "POST",
  "url": "/apps/mail/api/accounts",
  "message": "simplexml_load_string(): ^ at /apps/mail/lib/Service/AutoConfig/IspDb.php#73",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "version": "22.2.3.0",
  "exception": {
    "Exception": "Error",
    "Message": "simplexml_load_string(): ^ at /apps/mail/lib/Service/AutoConfig/IspDb.php#73",
    "Code": 0,
    "Trace": [
      {
        "function": "onError",
        "class": "OC\\Log\\ErrorHandler",
        "type": "::",
        "args": [
          2,
          "simplexml_load_string(): ^",
          "/apps/mail/lib/Service/AutoConfig/IspDb.php",
          73
        ]
      },
      {
        "file": "/apps/mail/lib/Service/AutoConfig/IspDb.php",
        "line": 73,
        "function": "simplexml_load_string",
        "args": [
          "<!DOCTYPE html>\n<html class=\"no-js\" lang=\"fr\">\n    <head>\n        <title>Nouvelle expérience en santé citoyenne</title>\n        <meta name=\"description\" content=\"L&#039;exp&eacute;rience sant&eacute;, personnelle, durable et plus autonome\">\n        <meta name=\"keywords\" content=\"Sant&eacute;, Maladies, traitements, douleurs, patients, antidouleur, naturel, Parcours de soin, am&eacute;lioration des prises en charges, d&eacute;lais diagnostic, retard de diagnostic\">\n        <meta charset=\"utf-8\">\n        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n        <meta name=\"robots\" content=\"index, follow\" />\n        <meta property=\"og:title\" content=\"La sant&eacute; ne s&rsquo;improvise pas, elle se pr&eacute;pare\" />\n        <meta property=\"og:description\" content=\"parcours de soin optimis&eacute;, satisfaction de la prise en charge\" />\n        <meta property=\"og:image\" content=\"https://www.example.info/img/sd_main_logo.jpg\" />\n        <meta property=\"og:type\" content=\"website\" />\n        <meta property=\"og:url\" content=\"https://www.example.info\" />\n        <meta name=\"twitter:card\" content=\"summary\" />\n        <meta name=\"twitter:title\" content=\"Bienvenue au Dispensaire\" />\n        <meta name=\"twitter:description\" content=\"parcours de soin optimis&eacute;, satisfaction de la prise en charge\" />\n        <meta name=\"twitter:image\" content=\"\" />\n        \n        \n            <script type=\"application/ld+json\">\n                {\n                    \"@context\": \"https://schema.org\",\n                    \"@type\": \"Corporation\",\n                    \"name\": \"example\",\n                    \"address\": {\n                        \"@type\": \"PostalAddress\",\n                        \"streetAddress\": \"2 rue Raymond Greban\",\n                        \"addressLocality\": \"St Germain en Laye\",\n                        \"addressCountry\": \"France\",\n                        \"postalCode\": \"78100\"\n                    },\n                    \"url\": \"https://www.example.info\",\n                    \"logo\": \"https://www.example.info/images/public/sd_5f634178dab62.png\",\n                    \"telephone\": \"0970995927\"\n                }\n            </script>\n        <link rel=\"canonical\" href=\"https://www.example.info\">\n        <link rel=\"shortcut icon\" href=\"/img/preset/favicon_publish/favicon_000.ico?no_cache=60d738b989db3\" >\n        <link rel=\"alternate\" href=\"https://www.example.info\" hreflang=\"fr\" />\n        <!-- Google Font or other font -->\n        <link href=\"https://fonts.googleapis.com/css?family=Cormorant+Garamond:700|Crimson+Text:700|Droid+Serif:700|Lora:700\" rel=\"stylesheet\">\n        <!-- Javascript libraly -->\n        <script src=\"/js/vendor/jquery-1.12.4.min.js\"></script>\n        <script src=\"/js/vendor/jquery-ui-1.12.1/jquery-ui.min.js\"></script>\n        <link rel=\"stylesheet\" href=\"/js/vendor/jquery-ui-1.12.1/jquery-ui.min.css\">\n        <!-- Simdif v2 script -->\n        <script src=\"/js/main.js\"></script>\n        <!-- 3rd party script -->\n        <script src=\"/js/plugins.js\"></script>\n        <script src=\"/js/vendor/imagelightbox.min.js\"></script>\n        <script src=\"/js/vendor/validator.min.js\"></script>\n        \n        \n        <script type=\"text/javascript\" src=\"/js/vendor/jquery.onoff.js\"></script>\n        <link rel=\"stylesheet\" href=\"/css/jquery.onoff.css\" type=\"text/css\" />\n        <!-- CSS -->\n        <link rel=\"stylesheet\" href=\"/css/normalize.css\">\n        <link rel=\"stylesheet\" href=\"/css/imagelightbox.css\">\n        <link rel=\"stylesheet\" href=\"/css/sd_main.css\">\n        <link rel=\"stylesheet\" href=\"/css/sd_icon.css\">\n        <link rel=\"stylesheet\" href=\"/css/sd_color.css\">\n        <link rel=\"stylesheet\" href=\"/css/sd_shapes.css\">\n        <link rel=\"stylesheet\" href=\"/css/sd_header.css\">\n        <link rel=\"stylesheet\" href=\"/css/sd_footer.css\">\n        <link rel=\"stylesheet\" href=\"/css/sd_media.css\">\n        <style>\n            \n        </style>\n        <link rel=\"stylesheet\" href=\"css/sd_style.css\">\n                \n    </head>\n    <body>\n        <!--[if lt IE 8]>\n            <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browser</a> to improve your experience.</p>\n        <![endif]-->\n        <div class=\"sd-home-page\">\n            <div id=\"sd-wrapper\" class=\"sd-publish-site sd-header-page-type-tagline\">\n                <div class=\"sd-bg-wrapper sd-header-image\"></div>\n                <div class=\"sd-bg-wrapper-texture\"></div>\n                <div id=\"sd-wrap-content\" class=\"sd-container\">\n                    <div class=\"sd-top-panel\"> <span class=\"sd-top-panel-view-cart sd-top-panel-view-cart-top\"></span>\n                        \n                    </div>\n                                            <header id=\"sd-header\">\n                            <div id=\"sd-strip-bar-main-wrapper\">\n    <div id=\"sd-strip-bar\" class=\"sticky\">\n        <div id=\"sd-strip-bar-wrap-container\">\n                            <div id=\"sd-site-logo\" class=\"sd-site-logo-png\">\n                                                                        <a href=\"/\"><img src=\"images/public/sd_5f7d6b86db611.png?nocache=1624717497\" alt=\"Logo example\"></a>\n                                                            </div>\n                        <div id=\"sd-strip-bar-wrap\" >\n                                    <h1 id=\"sd-site-title\" class=\"logo-show\"><b>example</b></h1>\n                    <div class=\"sd-site-contact\">\n                        <a href=\"contact.html\" class=\"sd-button sd-contact-btn\">Contact</a>\n                    </div>\n                                <div id=\"sd-strip-bar-background\"></div>\n            </div>\n        </div>\n    </div>\n    <div id=\"sd-strip-bar\" class=\"sd-strip-bar-main full-height\">\n                    <div id=\"sd-site-logo\" class=\"sd-site-logo-png\">\n                                                            <a href=\"/\"><img src=\"images/public/sd_5f7d6b86db611.png?nocache=1624717497\" alt=\"Logo example\"></a>\n                                                </div>\n                <div id=\"sd-strip-bar-wrap-container\">\n            <div id=\"sd-strip-bar-wrap\" >\n                                    <h1 id=\"sd-site-title\" class=\"logo-show\"><b>example</b></h1>\n                                <div id=\"sd-strip-bar-background\"></div>\n            </div>\n        </div>\n    </div>\n</div>\n<a href=\"#\" class=\"sd-button sd-mobnav-btn\">\n    <span class=\"sd-nav-icon\">\n        <span class=\"sd-icon-bar1\"></span>\n        <span class=\"sd-icon-bar2\"></span>\n        <span class=\"sd-icon-bar3\"></span>\n    </span><span id=\"phone_menu_button\" name=\"phone_menu_button\" class=\"sd-nav-menu\">Menu</span><span class=\"menu-triangle\">&#9662;</span>\n</a>\n<div class=\"sd-header-image\">\n                </div>\n<div id=\"sd-header-gradient\"></div>\n<!--  -->\n                        </header>\n                                        <div id=\"sd-main-wrap\">\n                                                <div id=\"sd-overlay\"></div>\n    \n                        <main id=\"sd-main\" class=\"clearfix\">\n                            <div id=\"sd-column-nav\">\n                                <nav class=\"sd-main-nav\">\n                                    <ul class=\"sd-tab\" >\n            \n        \n                                    <li class=\"sd-tab-item sd-tab-item-active\" ><a href=\"/\"><div class=\"\">Ce que nous faisons pour la santé</div></a></li>\n                        \n                        \n                    \n        \n                                    <li class=\"sd-tab-item\" ><a href=\"Commencer_mon_parcours.html\"><div class=\"\">M'inscrire au programme</div></a></li>\n                                            \n        \n                                    <li class=\"sd-tab-item\" ><a href=\"e-sant&eacute;.html\"><div class=\"\">Médicinal, et vous?</div></a></li>\n                                            \n        \n                     <li class=\"sd-tab-item sd-tab-item-space\" ></li>\n        \n                    \n        \n                                    <li class=\"sd-tab-item\" ><a href=\"Proche_de_vous.html\"><div class=\"\">Proximité</div></a></li>\n                                            \n        \n                                    <li class=\"sd-tab-item\" ><a href=\"intervenants.html\"><div class=\"\">Qui sommes nous ?</div></a></li>\n                                            \n        \n                     <li class=\"sd-tab-item sd-tab-item-space\" ></li>\n        \n                    \n        \n                                    <li class=\"sd-tab-item\" ><a href=\"du-sens-et-des-rep&egrave;res.html\"><div class=\"\">Ecologique</div></a></li>\n                                            \n        \n                                    <li class=\"sd-tab-item\" ><a href=\"Ce_qu_il_se_passe_en_ce_moment_en_coulisses....html\"><div class=\"\">En coulisse...</div></a></li>\n                                            \n        \n                     <li class=\"sd-tab-item sd-tab-item-space\" ></li>\n        \n                    \n        \n                                    <li class=\"sd-tab-item\" ><a href=\"contact.html\"><div class=\"\">Contact</div></a></li>\n                                            \n        \n                     <li class=\"sd-tab-item sd-tab-item-space\" ></li>\n        \n                    \n        \n                                    <li class=\"sd-tab-item\" ><a href=\"mentions-l&eacute;gales.html\"><div class=\"\">+</div></a></li>\n                                            \n            \n    </ul>\n                                </nav>\n                            </div>\n    \n                            <section id=\"sd-column-page\" class=\"sd-content-border sd-page-content\">\n                                <div class=\"sd-column-page-content\">\n                                    <h1 class=\"sd-page-title\">Plateforme médicinale partagée</h1>\n    \n<div id=\"sd-block-content\">\n        \n    <div class=\"sd-block sd-block-text clearfix\" >\n            \n        \n        <div class=\"sd-block-title-div\">\n                            <h2 class=\"sd-block-title\" >Découvrez ce que example peut faire</h2>\n                    </div>\n        \n                    <div class=\"sd-block-text-desc\" ><p><span style=\"font-size: 1em;\">example est une entreprise du domaine de la Biotech, qui commercialise des biens et services pour la santé. </span></p><p>En collaboration avec les acteurs de la santé et organismes de recherche publique, nous concevons des outils pour améliorer la santé à chaque étape de la vie<b>.</b><span style=\"font-size: 1em;\"><br></span></p><p><span style=\"font-size: 1em;\">Le PMP® est une innovation qui permet aux citoyens d’avoir accès à un produit personnalisé : sous la forme d'une boite nominative réutilisable qui contient des unidoses </span>spécialement<span style=\"font-size: 1em;\"> formulées à base d’extraits de plantes et de champignons supérieurs. Pour que leur expérience en santé soit synonyme de moins d'effets collatéraux, plus d'écologie et d'autonomie.</span></p><p><b>Nous avons également créé une plateforme participative avec un accès dédié pour les professionnels de la santé afin qu'ils puissent accompagner l'autonomisation et la prise en charge au sein du parcours principal</b><b style=\"font-size: 1em;\"> des patients chroniques :</b></p><ul><li><b>réductions des effets secondaires des traitements, </b></li><li><b>diminution de la surmédication (overtreatment),</b></li><li><b>amélioration de la qualité de vie, </b></li><li><b>diminution des douleurs</b></li><li><b>amélioration du fardeau des patients ...</b></li></ul></div>\n            </div>\n    \n<div class=\"sd-block sd-block-readmore-div clearfix\" >\n    \n    \n            <div class=\"sd-block-readmore-cover\" sd-data-readmore-id=\"1207784\"></div>\n        <div class=\"sd-block-readmore sd-shadow-2\">\n            <div class=\"sd-page-title-div\">\n                                    <h2 class=\"sd-page-title\">Une plateforme pour tous</h2>\n                                <div class=\"sd-block sd-block-text clearfix\" >\n            \n        \n        <div class=\"sd-block-title-div\">\n                            <h2 class=\"sd-block-title\" >Au service de la santé des citoyens</h2>\n                    </div>\n        \n                    <div class=\"sd-block-text-desc\" ><p>quelles interventions non médicamenteuses à associer pour améliorer la situation médicale rencontrée : <b>C'est par ici</b><br></p></div>\n            </div>\n    \n            </div>\n            <a href=\"e-sant&eacute;.html\">\n                <div class=\"sd-readmore-gradient\">\n                    <div class=\"sd-readmore-link\">Cliquez pour lire la suite...</div>\n                </div>\n            </a>\n        </div>\n    </div>\n    <div class=\"sd-block sd-block-gallery clearfix\" >\n            \n        \n        <div class=\"img-3-col-wrap clearfix\">\n            <div class=\"sd-block-image sd-img-3-col\">\n                <div class=\"sd-img-3-col-div\">\n                                            <a href=\"images/public/sd_5dca70e0af659.jpg?nocache=1624717497\" target=\"_blank\"  data-imagelightbox=show>\n                                                        <div class=\"sd-img-3-col-thumb\">\n                                <div class=\"sd-img-thumb sd-img-square\">\n                                                                <img class=\"\" src=\"images/th/sd_5dca70e0af659.jpg?nocache=1624717497\" alt=\"Services d&eacute;di&eacute;s aux pharmacies de ville\" />\n                                </div>\n                            </div>\n                        </a>\n                                    </div>\n                                    <div class=\"sd-image-desc\">Services d&eacute;di&eacute;s aux pharmacies de ville</div>\n                            </div>\n            <div class=\"sd-block-image sd-img-3-col\">\n                <div class=\"sd-img-3-col-div\">\n                                            <a href=\"images/public/sd_5f490a49c024b.png?nocache=1624717497\" target=\"_blank\"  data-imagelightbox=show>\n                                                        <div class=\"sd-img-3-col-thumb\">\n                                <div class=\"sd-img-thumb sd-img-square\">\n                                                                <img class=\"\" src=\"images/th/sd_5f490a49c024b.png?nocache=1624717497\" alt=\"Faciliter l&#039;intervention du pharmacien correspondant et le bilan de m&eacute;dication\" />\n                                </div>\n                            </div>\n                        </a>\n                                    </div>\n                                    <div class=\"sd-image-desc\">Faciliter l&#039;intervention du pharmacien correspondant et le bilan de m&eacute;dication</div>\n                            </div>\n            <div class=\"sd-block-image sd-img-3-col\">\n                <div class=\"sd-img-3-col-div\">\n                                            <a href=\"images/public/sd_5dca76fb2a2da.jpg?nocache=1624717497\" target=\"_blank\"  data-imagelightbox=show>\n                                                        <div class=\"sd-img-3-col-thumb\">\n                                <div class=\"sd-img-thumb sd-img-square\">\n                                                                <img class=\"\" src=\"images/th/sd_5dca76fb2a2da.jpg?nocache=1624717497\" alt=\"Optimisation de la gal&eacute;nique pour une approche vraiment personnalis&eacute;e\" />\n                                </div>\n                            </div>\n                        </a>\n                                    </div>\n                                    <div class=\"sd-image-desc\">Optimisation de la gal&eacute;nique pour une approche vraiment personnalis&eacute;e</div>\n                            </div>\n        </div>\n    </div>\n    \n<div class=\"sd-block sd-block-gallery clearfix\" >\n            \n        \n        <div class=\"img-3-col-wrap clearfix\">\n            <div class=\"sd-block-image sd-img-3-col\">\n                <div class=\"sd-img-3-col-div\">\n                                            <a href=\"images/public/sd_5cdec370aa00d.jpg?nocache=1624717497\" target=\"_blank\"  data-imagelightbox=show>\n                                                        <div class=\"sd-img-3-col-thumb\">\n                                <div class=\"sd-img-thumb sd-img-square\">\n                                                                <img class=\"\" src=\"images/th/sd_5cdec370aa00d.jpg?nocache=1624717497\" alt=\"Mesures d&#039;efficacit&eacute;, lutte contre les r&eacute;sistances bact&eacute;riennes\" />\n                                </div>\n                            </div>\n                        </a>\n                                    </div>\n                                    <div class=\"sd-image-desc\">Mesures d&#039;efficacit&eacute;, lutte contre les r&eacute;sistances bact&eacute;riennes</div>\n                            </div>\n            <div class=\"sd-block-image sd-img-3-col\">\n                <div class=\"sd-img-3-col-div\">\n                                            <a href=\"images/public/sd_5dca6c873b6bc.jpg?nocache=1624717497\" target=\"_blank\"  data-imagelightbox=show>\n                                                        <div class=\"sd-img-3-col-thumb\">\n                                <div class=\"sd-img-thumb sd-img-square\">\n                                                                <img class=\"\" src=\"images/th/sd_5dca6c873b6bc.jpg?nocache=1624717497\" alt=\"Ingr&eacute;dients de haute qualit&eacute; dont l&#039;utilit&eacute; est document&eacute;e dans de nombreux domaines m&eacute;dicaux\" />\n                                </div>\n                            </div>\n                        </a>\n                                    </div>\n                                    <div class=\"sd-image-desc\">Ingr&eacute;dients de haute qualit&eacute; dont l&#039;utilit&eacute; est document&eacute;e dans de nombreux domaines m&eacute;dicaux</div>\n                            </div>\n            <div class=\"sd-block-image sd-img-3-col\">\n                <div class=\"sd-img-3-col-div\">\n                                            <a href=\"images/public/sd_5cdec370b4195.jpg?nocache=1624717497\" target=\"_blank\"  data-imagelightbox=show>\n                                                        <div class=\"sd-img-3-col-thumb\">\n                                <div class=\"sd-img-thumb sd-img-square\">\n                                                                <img class=\"\" src=\"images/th/sd_5cdec370b4195.jpg?nocache=1624717497\" alt=\"Aide d&eacute;cisionnelle au diagnostic et &agrave; la prescription\" />\n                                </div>\n                            </div>\n                        </a>\n                                    </div>\n                                    <div class=\"sd-image-desc\">Aide d&eacute;cisionnelle au diagnostic et &agrave; la prescription</div>\n                            </div>\n        </div>\n    </div>\n    \n<div class=\"sd-block clearfix\" >\n            \n        \n        <div class=\"sd-block-image sd-img-align-center sd-img-full\">\n                            <a href=\"images/public/sd_5facea5a85315.png?nocache=1624717497\" target=\"_blank\" data-imagelightbox=show>\n                    <img class=\"\" src=\"images/th/sd_5facea5a85315.png?nocache=1624717497\" alt=\"Le PMP favorise les interactions entre les acteurs de sant&eacute; au service d&#039;une recherche orient&eacute;e par le patient\" />\n                </a>\n                                        <div class=\"sd-image-desc\">Le PMP favorise les interactions entre les acteurs de sant&eacute; au service d&#039;une recherche orient&eacute;e par le patient</div>\n                    </div>\n    </div>\n    \n    </div>\n    \n                                </div>\n                            </section>\n                        </main>\n    \n                        <footer id=\"sd-footer\">\n                            <div id=\"sd-footer-content\" class=\"sd-footer-border sd-footer-content\">\n                <div><div style=\"text-align: center;\"><br></div><div style=\"text-align: center;\">La version du présent site est donnée provisoirement à titre d'information </div><div style=\"text-align: center;\"><br></div><div style=\"text-align: center;\">Le site officiel de example, et de la plateforme Medicinall sont cours de développement avec des patients, des chercheurs et des pros de santé : nous avons hâte de vous les présenter</div><div style=\"text-align: center;\"><br></div><div style=\"text-align: center;\"><a target=\"_self\" href=\"mentions-légales.html\">Mentions légales ici</a></div></div>\n        </div>\n    \n                        </footer>\n    \n                    </div>\n                    <div id=\"sd-bottom\" class=\"clear\">\n                        <div id=\"sd-bottom-icon\" class=\"sd-bottom-style\">\n                  </div>\n<div id=\"sd-credit\" class=\"sd-bottom-style\">\n    </div>\n                    </div>\n                </div>\n            </div>\n        </div>\n        <div id=\"sd-publish-loader-icon\"><img src=\"/img/loader.gif\"></div>\n        <!-- Image lightbox wrapper content -->\n        <div class=\"imagelightbox-wrap\"></div>\n                \n                \n                \n    </body>\n</html>\n"
        ]
      },
      {
        "file": "/apps/mail/lib/Service/AutoConfig/IspDb.php",
        "line": 133,
        "function": "queryUrl",
        "class": "OCA\\Mail\\Service\\AutoConfig\\IspDb",
        "type": "->",
        "args": [
          "http://example.info/.well-known/autoconfig/mail/config-v1.1.xml?emailaddress=cia@example.info"
        ]
      },
      {
        "file": "/apps/mail/lib/Service/AutoConfig/IspDbConfigurationDetector.php",
        "line": 94,
        "function": "query",
        "class": "OCA\\Mail\\Service\\AutoConfig\\IspDb",
        "type": "->",
        "args": [
          "example.info",
          "cia@example.info"
        ]
      },
      {
        "file": "/apps/mail/lib/Service/AutoConfig/AutoConfig.php",
        "line": 53,
        "function": "detectImapAndSmtp",
        "class": "OCA\\Mail\\Service\\AutoConfig\\IspDbConfigurationDetector",
        "type": "->",
        "args": [
          "cia@example.info",
          "Sol-Eil-1",
          "Camille"
        ]
      },
      {
        "file": "/apps/mail/lib/Service/SetupService.php",
        "line": 92,
        "function": "createAutoDetected",
        "class": "OCA\\Mail\\Service\\AutoConfig\\AutoConfig",
        "type": "->",
        "args": [
          "cia@example.info",
          "Sol-Eil-1",
          "Camille"
        ]
      },
      {
        "file": "/apps/mail/lib/Controller/AccountsController.php",
        "line": 346,
        "function": "createNewAutoConfiguredAccount",
        "class": "OCA\\Mail\\Service\\SetupService",
        "type": "->",
        "args": [
          "Camille",
          "cia@example.info",
          "Sol-Eil-1"
        ]
      },
      {
        "file": "/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 217,
        "function": "create",
        "class": "OCA\\Mail\\Controller\\AccountsController",
        "type": "->",
        "args": [
          "Camille",
          "cia@example.info",
          "Sol-Eil-1",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          true
        ]
      },
      {
        "file": "/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 126,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Mail\\Controller\\AccountsController"
          },
          "create"
        ]
      },
      {
        "file": "/lib/private/AppFramework/App.php",
        "line": 156,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Mail\\Controller\\AccountsController"
          },
          "create"
        ]
      },
      {
        "file": "/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\Mail\\Controller\\AccountsController",
          "create",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "_route": "mail.accounts.create"
          }
        ]
      },
      {
        "file": "/lib/base.php",
        "line": 1006,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/apps/mail/api/accounts"
        ]
      },
      {
        "file": "/index.php",
        "line": 36,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/lib/private/Log/ErrorHandler.php",
    "Line": 92,
    "CustomMessage": "--"
  },
  "id": "61a748226b98a"
}
```

### PR DESCRIPTION
**Pull request by miaulalala**
Fixes #5763

### CODE REVIEW

File: lib/Service/AutoConfig/IspDb.php [hunk 1]
```diff
@@ -70,8 +70,14 @@ private function queryUrl(string $url): array {
 			return [];
 		}
 
+		libxml_use_internal_errors(true);
 		$data = simplexml_load_string($xml);
+
 		if ($data === false || !isset($data->emailProvider)) {
+			$errors = libxml_get_errors();
+			foreach($errors as $error) {
+				$this->logger->debug($error->message);
```
Comment (ChristophWurst) [inline lib/Service/AutoConfig/IspDb.php:79]:
```suggestion
				$this->logger->debug("ISP DB returned an erroneous XML: " . $error->message);
```

**Review by ChristophWurst — APPROVED** [review]
