### PR TITLE
Add key property to dashboard messages and fix misc errors for emails with empty from array

### LINKED ISSUE #4580: wrong avatars on the widget "Wichtige E-Mail"
### Expected behavior

the displayed avatar on the email in the widget should be correct.

### Actual behavior
on the widget "Wichtige E-Mail" i see wrong avatars which are not related to the email/thread.
when i inspect the html i  can see the following in the src of the img: "https://../remote.php/dav/addressbooks/system/system/system/Database:XYZ.vcf?photo"
(XYZ is not part on this e-mail)

pressing F5 on the dashboard also shows different not related avatars on the same email.
seams like a random display behavior.

### Mail app

**Mail app version:** 1.8.3

### PR DESCRIPTION
**Pull request by IchbinkeinReh**
fixes #4580
this is because DashboardWidget uses field id as key for the v-for and the messages do not have an id field (see https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/NcDashboardWidget/NcDashboardWidget.vue#L190 )

### CODE REVIEW

**Comment by IchbinkeinReh** [comment]
@ChristophWurst sry for asking. Do i have to do anything to get this PR reviewed or did you have no time yet to review the PR?

File: src/components/Dashboard.vue [hunk 1]
```diff
@@ -128,6 +128,7 @@ export default {
 
 		await Promise.all(inboxes.map(async (mailbox) => {
 			const messages = await fetchEnvelopes(mailbox.accountId, mailbox.databaseId, this.query, undefined, 10)
+			messages.forEach(message => { message.id = message.databaseId })
```
Comment (ChristophWurst) [inline src/components/Dashboard.vue:131]: I don't comprehend why this is necessary. Could you elaborate?
