### PR TITLE
fix: show indication that translation modal uses AI

### LINKED ISSUE #12395: Translation modal misses indication about generated content
### Steps to reproduce

1. Open an email
2. Click *Translate*

### Expected behavior

The opened modal tells me that AI is used for translation.

This has been developed already be the integrations team. We might be using an old/wrong version of the modal.

### Actual behavior

No hint

### Mail app version

_No response_

### Nextcloud version

_No response_

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

None

### Nextcloud memory caching

_No response_

### Web server

None

### Database

None

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by GretaD**
fixes #12395

Screenshot from 2026-02-23 16-21-07

### CODE REVIEW

File: src/components/TranslationModal.vue [hunk 1]
```diff
@@ -228,4 +236,9 @@ export default {
 		}
 	}
 }
+.translate-dialog__ai-note {
```
Comment (ChristophWurst) [inline src/components/TranslationModal.vue]: we already have a `.translate-dialog {` block. move this one inside and use `&__ai-note`

File: src/components/TranslationModal.vue [hunk 2]
```diff
@@ -46,6 +46,12 @@
 					{{ isLoading ? t('mail', 'Translating') : t('mail', 'Translate') }}
 				</NcButton>
 			</div>
+			<div class="translate-dialog__ai-note">
+				<WarningIcon class="translate-dialog__ai-note-icon" />
+				<span>
+					{{ t('mail', 'This translation is generated using AI and may contain inaccuracies') }}
+	</span>
```
Comment (ChristophWurst) [inline src/components/TranslationModal.vue]: indentation
