### PR TITLE
fix: flip email open and email icon in evelope actions

### LINKED ISSUE #11725: Mark as read icon opposite
### Steps to reproduce

Hover on the email preview and within the opened mail.

### Expected behavior

The mark as read icon should be both the same in the mail and on the popup.

### Actual behavior

The mark as read/unread icon is the opposite within the opened mail and the new popup on the mail preview. Should be the same as the icon in the mail.

Image 

Image

### Mail app version

_No response_

### Nextcloud version

_No response_

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

None

### Nextcloud memory caching

_No response_

### Web server

None

### Database

None

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by kesselb**
Fix #11725

To align with the message header

### CODE REVIEW

File: src/components/EnvelopeSingleClickActions.vue [hunk 1]
```diff
@@ -40,8 +40,8 @@
 <script>
 
 import ImportantOutlineIcon from 'vue-material-design-icons/LabelVariantOutline.vue'
-import EmailUnread from 'vue-material-design-icons/EmailOutline.vue'
-import EmailRead from 'vue-material-design-icons/EmailOpenOutline.vue'
+import EmailUnread from 'vue-material-design-icons/EmailOpenOutline.vue'
+import EmailRead from 'vue-material-design-icons/EmailOutline.vue'
```
Comment (ChristophWurst) [inline src/components/EnvelopeSingleClickActions.vue]: naming is very confusing. maybe swap the icons in the template instead?
