### PR TITLE
Show account color indicator only if several mailboxId's are present

### LINKED ISSUE #6191: Account color indicator shows in priority inbox even if only 1 account is configured
### Steps to reproduce

1. Have only 1 account in Mail
2. Check the Priority inbox
3. Notice a color line on the left (and the color line also shows for the "load more" action entry which seems off)

### Expected behavior

No color line on the left since it’s only 1 account.

### Actual behavior

This color line is shown on the left:
image

cc @ChristophWurst @karlitschek as we saw in the call. :)

### Mail app version

Current on cloud.nc.com

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
fixes #6191

### CODE REVIEW

File: src/components/Envelope.vue [hunk 1]
```diff
@@ -16,7 +16,7 @@
 		@click="onClick">
 		<template #icon>
 			<div
-				v-if="mailbox.isUnified"
```
Comment (ChristophWurst) [inline src/components/Envelope.vue:19]: now it will also show in individual mailboxes like *Draft* and *Sent*. This should only be there in any *unified* mailbox like *All inboxes*, *Priority inbox* and *Outbox*.

File: src/components/Envelope.vue [hunk 2]
```diff
@@ -236,6 +236,10 @@ export default {
 			required: false,
 			default: () => [],
 		},
+		isSeveralMailboxIdsPresent: {
```
Comment (ChristophWurst) [inline src/components/Envelope.vue:239]: `hasMultipleAccounts`?

**Review by ChristophWurst — CHANGES_REQUESTED** [review]

File: src/components/EnvelopeList.vue [hunk 3]
```diff
@@ -272,6 +273,10 @@ export default {
 		selectedEnvelopes() {
 			return this.envelopes.filter((env) => this.selection.includes(env.databaseId))
 		},
+		hasMultipleAccounts() {
+			const mailboxIds = this.envelopes.map(envelope => envelope.mailboxId)
+			return Array.from(new Set(mailboxIds)).length > 1
```
Comment (ChristophWurst) [inline src/components/EnvelopeList.vue:278]: It would hurt to comment such code. I get that the conversion from array to set to array is to remove duplicates but it's not obvious :)

**Review by ChristophWurst — APPROVED** [review]
Looks good
