### PR TITLE
Handle error when thread id is unknown

### LINKED ISSUE #7608: Inexistent thread loads forever due to lacking error handling
### Steps to reproduce

1. Set up an account
2. Open `/apps/mail/box/priority/thread/12345678987654321`

### Expected behavior

The loading ends once the app sees that the thread does not exist (HTTP 403) and shows a nice info that the thread doesn't exist or was deleted

### Actual behavior

The thread loads forever

### Mail app version

2.2

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by GretaD**
fixes #7608 

- [x] needs #7643

### CODE REVIEW

File: src/components/Thread.vue [hunk 1]
```diff
@@ -247,8 +248,8 @@ export default {
 				this.loading = false
 			} catch (error) {
 				logger.error('could not load envelope thread', { threadId, error })
-				if (error.isError) {
-					this.errorMessage = t('mail', 'Could not load your message thread')
+				if (error?.response?.status === 403) {
+					showError(t('mail', 'Could not load your message thread, it doesnt exist or is deleted'))
```
Comment (ChristophWurst) [inline src/components/Thread.vue:252]:
```suggestion
					showError(t('mail', 'Could not load your message thread because it doesn't exist or has been deleted'))
```

File: src/components/Thread.vue [hunk 2]
```diff
@@ -247,8 +248,8 @@ export default {
...
 					this.error = error
 					this.loading = false
 				}
```
Comment (ChristophWurst) [inline src/components/Thread.vue:255]: add an `else` for any other error and show *Could not load your message thread*

that could happen if the network is down, etc.

**Review by ChristophWurst — CHANGES_REQUESTED** [review]

**Review by ChristophWurst — COMMENTED** [review]
Why did you go for `showError` instead of `this.errorMessage`?

Your toast will be temporary and the loading is still infinite, isn't it?

**Comment by GretaD** [comment]
> Why did you go for `showError` instead of `this.errorMessage`?
> 
> Your toast will be temporary ~and the loading is still infinite, isn't it?~ loading stops.

Just so i could have a feedback on the UI which is the toast.

**Comment by ChristophWurst** [comment]
You are right. `errorMessage` is no longer used in the template. Let me see why.

**Comment by ChristophWurst** [comment]
> Let me see why.

It was the usual suspects: https://github.com/nextcloud/mail/pull/3540

**Comment by ChristophWurst** [comment]
Can we revive the old error empty content to show instead of the loading view when the thread can't be loaded? This makes the error show in place and permanent. Toasts vanish.

**Comment by GretaD** [comment]
yes, done. Theres only one problem. I cannot click an envelope now, i can scroll and click mailboxes but not envelopes.

Screenshot from 2022-11-17 11-58-22

**Comment by ChristophWurst** [comment]
I think Vue recycles the `Thread` component. The component has no input props but relies on the *route*. See the `$route` watcher. It calls `resetThread` for every route change. Reset `this.error` and `this.errorMessage` in that method.

**Comment by GretaD** [comment]
after resetting `this.error ` and  `this.errorMessage` the envelope list is not responsive anymore

**Comment by ChristophWurst** [comment]
It is repsonsive but the custom .emtpycontent div of the error overlaps the list. Use your browser inspection on top of the evenlope list. 
Bildschirmfoto vom 2022-11-17 18-21-03

**Comment by GretaD** [comment]
> after resetting `this.error ` and `this.errorMessage` the envelope list is not responsive anymore

now it is :)

File: src/components/Thread.vue [hunk 3]
```diff
@@ -247,10 +256,12 @@ export default {
 				this.loading = false
 			} catch (error) {
 				logger.error('could not load envelope thread', { threadId, error })
-				if (error.isError) {
-					this.errorMessage = t('mail', 'Could not load your message thread')
+				if (error?.response?.status === 403) {
+					this.errorMessage = t('mail', 'Could not load your message thread, because it doesn\'t exist or has been deleted')
 					this.error = error
```
Comment (ChristophWurst) [inline src/components/Thread.vue:261]:
```suggestion
					this.error = t('mail', 'Could not load your message thread')
					this.errorMessage = t('mail', 'The thread doesn\'t exist or has been deleted')
```

**Review by ChristophWurst — COMMENTED** [review]
Less technical, more human

File: src/components/Thread.vue (hunk 3 above)
Comment (GretaD) [reply src/components/Thread.vue]: :robot:

**Review by ChristophWurst — APPROVED** [review]
An icon would make it perfect
