### PR TITLE
Better error message for null mailbox stats

### LINKED ISSUE #8813: TypeError thrown by cron background job
### Steps to reproduce

Open nextcloud log
error message is shown

```
[mail] Fehler: TypeError: OCA\Mail\IMAP\MailboxStats::__construct(): Argument #1 ($total) must be of type int, null given, called in /var/www/nextcloud/apps/mail/lib/IMAP/FolderMapper.php on line 147 at <<closure>>

0. /var/www/nextcloud/apps/mail/lib/IMAP/FolderMapper.php line 147
   OCA\Mail\IMAP\MailboxStats->__construct()
1. /var/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php line 294
   OCA\Mail\IMAP\FolderMapper->getFoldersStatusAsObject()
2. /var/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php line 145
   OCA\Mail\IMAP\MailboxSync->syncMailboxStatus("*** sensitive parameters replaced ***")
3. /var/www/nextcloud/apps/mail/lib/BackgroundJob/SyncJob.php line 110
   OCA\Mail\IMAP\MailboxSync->sync("*** sensitive parameters replaced ***")
4. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 81
   OCA\Mail\BackgroundJob\SyncJob->run()
5. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
   OCP\BackgroundJob\Job->start()
6. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
   OCP\BackgroundJob\TimedJob->start()
7. /var/www/nextcloud/cron.php line 152
   OCP\BackgroundJob\TimedJob->execute()

at 2023-08-25T18:05:07+00:00
```

message is shown around 14 times per day

### Expected behavior

no error message is shown or a hint why this error occurs

### Actual behavior

error message is shown with unknown reason

### Mail app version

3.3.1

### Mailserver or service

imap on debian

### Operating system

Raspbian bullseye 64bit (Linux 6.1.21-v8+ aarch64)

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

MariaDB

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by hamza221**
Fix #8813

### CODE REVIEW

File: lib/IMAP/FolderMapper.php [hunk 1]
```diff
@@ -142,10 +150,17 @@ public function getFoldersStatusAsObject(Horde_Imap_Client_Socket $client,
 
 		$statuses = [];
 		foreach ($multiStatus as $mailbox => $status) {
-			$statuses[$mailbox] = new MailboxStats(
-				$status['messages'],
-				$status['unseen'],
-			);
+			try {
+				if(!isset($status['messages']) && !isset($status['unseen'])) {
```
Comment (ChristophWurst) [inline lib/IMAP/FolderMapper.php:154]:
```suggestion
				if (!isset($status['messages'], $status['unseen'])) {
```

coding style and simplification

https://www.php.net/manual/en/function.isset.php

**Review by ChristophWurst — APPROVED** [review]
