### PR TITLE
Fix to update counter on message delete

### LINKED ISSUE #596: Draft counter doesn't update when you delete a draft
Happens on NC 12.0.3 (on the Cloud of Nextcloud staff):

I had 4 drafts, I deleted 2 of them via the trashcan icon of the draft. The counter on the left doesn't update but stays at 4.

The counter only updates when I reload the page entirely.

screenshot from 2017-11-05 11-28-39

### PR DESCRIPTION
**Pull request by sagorika1996**
Fixes #596

### CODE REVIEW

File: js/controller/foldercontroller.js [hunk 1]
```diff
@@ -196,9 +196,11 @@ define(function(require) {
 
 		applyOnFolders(folders, function(folder) {
 			// Update total counter and prevent negative values
-			folder.set('total', Math.max(0, folder.get('total')));
+			folder.set('total', Math.max(0, folder.get('total')-1));
 		});
 
+		Radio.message.trigger('flag', message, 'unseen', false);
```
Comment (ChristophWurst) [inline js/controller/foldercontroller.js]: Why is this line necessary? This will easily result in a race condition because the flag and delete requests are sent almost at the same time.

Comment (sagorika1996) [reply js/controller/foldercontroller.js]: Oh I see, yes this is not necessary. I'll remove it.

**Comment by ChristophWurst** [comment]
Code looks great now! Thanks a lot!

@jancborchardt please help testing

**Comment by ChristophWurst** [comment]
Btw, @sagorika1996, I've added you as collaborator of this repository, so please feel free to push your branches directly to this repository instead of your fork. This makes checking out your pull request branches a lot easier.

**Comment by jancborchardt** [comment]
@ChristophWurst please call all @nextcloud/mail contributors for testing :) I have plenty of backlog already
