### PR TITLE
Fix: multi-select while holding shift key

### LINKED ISSUE #10954: Multi-select no longer working after new UI rework
### Steps to reproduce

1. Select first message.
2. Press and hold shift.
3. Select last message.

### Expected behavior

All the messages in between first and last message should be selected.

### Actual behavior

Only the 2 messages you selected get marked.

### Mail app version

4.3.4

### Nextcloud version

_No response_

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

None

### Nextcloud memory caching

_No response_

### Web server

None

### Database

None

### Additional info

You can no longer select multiple messages by selecting the first message, pressing and holding "Shift" and then selecting the last message.
I would always prefer function over design and that was a very useful function.

### PR DESCRIPTION
**Pull request by GretaD**
fix #10954

### CODE REVIEW

**Comment by ChristophWurst** [comment]
There seems to be an unrelated commit

File: src/components/Envelope.vue [hunk 1]
```diff
@@ -47,7 +47,8 @@
 				:class="{ 'hover-active': hoveringAvatar && !selected }"
 				@mouseenter="hoveringAvatar = true"
 				@mouseleave="hoveringAvatar = false"
-				@click.stop.prevent="toggleSelected">
+				@click.stop.exact.prevent="toggleSelected"
```
Comment (ChristophWurst) [inline src/components/Envelope.vue:50]: just curious, what difference does the `.exact` make here?

**Review by ChristophWurst — APPROVED** [review]
