### PR TITLE
fix: allow syncing of mailboxes with a trailing space

### LINKED ISSUE #5200: Mailbox names with different number of trailing whitespace considered identical
### Expected behavior

Mailboxes can be named with and differentiated by whitespace characters at the end.

### Actual behavior

Unique Constrain Violation when trying to sync and write mailboxes. 

The reason being that text values are whitespace padded (at least in MySQL):
https://stackoverflow.com/questions/59504215/how-to-add-white-space-at-the-end-of-word-while-inserting-data-into-mysql

### PR DESCRIPTION
**Pull request by kesselb**
Fix #5200 

The unique index considers "Test " and "Test" identical when using a padspace collation. 
Adding a new column "name_hash" with a hashed version of the name as a workaround.

### CODE REVIEW

File: lib/Migration/Version3500Date20231115182612.php [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+		}
+
+		$this->connection->commit();
+
+		// Round 2: Hash everything else
+
+		$qb = $this->connection->getQueryBuilder();
+		$qb->select(['id', 'name'])
+			->from('mail_mailboxes')
+			->where($qb->expr()->emptyString('name_hash'));
```
[the remark this answers is not in the document]
Comment (kesselb) [reply lib/Migration/Version3500Date20231115182612.php:86]: Our Query Builder has everything you need https://github.com/nextcloud/server/blob/1cd4d4e018687513fa6e14d3d1af5a88d18a4760/lib/private/DB/QueryBuilder/ExpressionBuilder/OCIExpressionBuilder.php#L149-L158 :partying_face:

**Review by ChristophWurst — APPROVED** [review]
Tested & works

File: lib/Migration/Version3500Date20231115182612.php [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+		$updateQb->update('mail_mailboxes')
+			->set('name_hash', $updateQb->createParameter('name_hash'))
+			->where($updateQb->expr()->eq('id', $updateQb->createParameter('id')));
+
+		$this->connection->beginTransaction();
+
+		while (($row = $mailboxes->fetch()) !== false) {
+			$updateQb->setParameter('id', $row['id']);
+			$updateQb->setParameter('name_hash', md5($row['name']));
+			$updateQb->executeStatement();
```
Comment (ChristophWurst) [inline lib/Migration/Version3500Date20231115182612.php:99]: nit: for very large installations it could be beneficial if the transaction is broken up every x thousand queries

Comment (kesselb) [reply lib/Migration/Version3500Date20231115182612.php:99]: Sure, do you have a number in mind? 

The default size for the innodb log file size https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_log_file_size seems 48mb. I guess that should be enough for a couple of queries ;)

Also interesting: 

https://stackoverflow.com/questions/17555757/transaction-size-limit-in-sql-server
https://stackoverflow.com/questions/709708/maximum-transaction-size-in-postgresql
https://forums.mysql.com/read.php?22,137157,137348#msg-137348

Comment (ChristophWurst) [reply lib/Migration/Version3500Date20231115182612.php:99]: for message bulk insertion I did some benchmarks. I think the sweetspot on my local environment was somewhere around 10k entries. this UPDATE here has less data so it's probably capable of more changes in one transaction. 50k?

Comment (kesselb) [reply lib/Migration/Version3500Date20231115182612.php:99]:
```
I have no name!@7363db6e2186:/var/www/html$ time php occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <mail> ...
Restore default tags that are missing

 Done
 5/5 [============================] 100%
Purify and migrate collected mail addresses
 Done
 2/2 [============================] 100%
Insert background jobs for all accounts
 Done
 5/5 [============================] 100%
Updated <mail> to 3.5.0-beta.6
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level

real	0m59.172s
user	0m22.325s
sys	0m8.321s

```

Looks good with 50k batches :+1:

**Review by ChristophWurst — APPROVED** [review]
