### PR TITLE
Fix "post-message deletion"-navigation

### LINKED ISSUE #2154: Delete key shortcut behaves differently than action menu "Delete" action
1. Open the very first mail in a mailbox
2. Hit the delete key on your keyboard
3. Current message gets deleted as expected, but:

### Expected behavior
It should switch to the next most recent message below as the active one. (Only when you are at the very top of course. When you are in any other message below, it will move to the next newer message, as intended.)

This works fine when you use "Delete" from the action menu.

### Actual behavior
When you use the delete key shortcut, the already deleted mail keeps being active and shown in the content view.

### Mail app

**Mail app version:** current master

### LINKED ISSUE #2492: Add 'cancel' button to discard draft
Subject says it all - right now you have to go to the drafts folder and delete the draft every time you started a reply but decided to drop it ;-)

Good first issue if you already know vue.js according to @ChristophWurst who will of course help anyone who needs help with it!

### PR DESCRIPTION
**Pull request by ahstro**
This PR contains two adjacent but ultimately disconnected bugs. Sorry! If y'all prefer harder separation in the future let me know.

This fixes 1) navigating to the wrong message (one step too far down in the list) after deleting a message, and 2) not navigating at all.

I also threw in some minor clean-up for good measure/bad GitHub etiquette. At least the commits are separate 😇

Edit: I'm not sure if there's an issue related to this. I stumbled upon the bugs when trying to understand enough to fix #2492 (getting there). I tried finding a related issue, but couldn't..

Edit 2:
Fixes #2154

### CODE REVIEW

**Comment by jancborchardt** [comment]
Hi @ahstro, good stuff! :) Is it correct that this aims to fix **Delete key shortcut behaves differently than action menu "Delete" action #2154**? Or what is the expected before/after behavior?

File: src/components/Mailbox.vue [hunk 1]
```diff
@@ -329,13 +328,7 @@ export default {
...
 			}
 
-			let next
-			if (idx === 0) {
-				next = envelopes[idx + 1]
-			} else {
-				next = envelopes[idx - 1]
-			}
-
+			const next = this.envelopes[idx === 0 ? idx : idx - 1]
```
Comment (ChristophWurst) [inline src/components/Mailbox.vue]: should it be `idx === 0 ? idx + 1 : idx - 1` here?

Comment (ChristophWurst) [reply src/components/Mailbox.vue]: or just `1` instead of `idx + 1`

Comment (ahstro) [reply src/components/Mailbox.vue]: No, that was one of the bugs I found 😊 Since we removed the 0th item of the array, the new 0th item would be the desired message, while the 1st would be one down the list. Not sure if that sentence made sense to anyone other than me 😅

**Comment by ahstro** [comment]
@jancborchardt Ah, there ya' go, that's a related issue! That's one of the two bugs this fixes 😊 The other is the one I'm crudely trying to describe in @ChristophWurst's review. Sorry if my communication skills are off...
