### PR TITLE
Change sender position to be centered with the avatar and timestamps

### LINKED ISSUE #6621: Sender of thread message not vertically centered
### Steps to reproduce

1. Open a thread (can be one message only)
2. Look at the avatar/sender

### Expected behavior

Avatar and sender are on one line

### Actual behavior

Sender floats above the avatar base line.

Bildschirmfoto vom 2022-06-01 09-14-43

### Mail app version

1.13

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### Additional info

@GretaD you worked on the thread subject logic. Can you tell why the sender isn't centered (anymore)?

### PR DESCRIPTION
**Pull request by GretaD**
**before**
before-nosubject-notag

**after**
no subjet no tag
nosubjetc

the last 2 are the same as before, this pr fixes only when theres no subject or tags the sender should be centered.
subject+tag
subject-tag-
tag, no subject
nosubject tag

fixes #6621

### CODE REVIEW

**Comment by ChristophWurst** [comment]
1) I *think* that the avatar and sender should be on one line if there is no changing subject.
2) If the subject changes (and is shown) *or* there are tags assigned to a message, I would not move the sender down anymore.

In other words, I see the sender/subject/tags as one *block*. and that block should be aligned with the avatar. Does that make sense?

**Comment by GretaD** [comment]
yeah, sounds good, also i think this is not a bug, its the same design as envelope list, we just removed the subject for threads and didn't change the position.

**Comment by ChristophWurst** [comment]
could you please add before/after screenshots

**Review by ChristophWurst — APPROVED** [review]
Linter should complain about the indentation

File: src/components/ThreadEnvelope.vue [hunk 1]
```diff
@@ -198,6 +199,9 @@ export default {
 		cleanSubject() {
 			return this.envelope.subject.replace(/((?:[\t ]*(?:R|RE|F|FW|FWD):[\t ]*)*)/i, '')
 		},
+		centeredSender() {
+			  return (!this.hasChangedSubject || this.cleanSubject.length === 0) && this.tags.length === 0
+				 },
```
Comment (ChristophWurst) [inline src/components/ThreadEnvelope.vue:204]: something looks odd here

Comment (GretaD) [reply src/components/ThreadEnvelope.vue:204]: yes? i dont see it :(

this was the only way how i could make it work for all the scenarios. Am i missing something, or the way how i wrote the conditions is wrong?

Comment (ChristophWurst) [reply src/components/ThreadEnvelope.vue:204]: The indentation

**Review by ChristophWurst — APPROVED** [review]
