### PR TITLE
fix(phishing): strip exactly 1 character from the end of a link strin…

### LINKED ISSUE #11028: Incorrect suspicious links warning when a content link contains a "-"
### Steps to reproduce

If the domain part of an email link in an email contains a "-" (e.g. joe@ex-ample.com), Nextcloud gives an incorrect suspicious warning like this:

Image

The following example email generates the problem:

```
Return-Path: <jill@ex-ample.com>
Message-ID: <6a7327f4-0d7e-4d82-92ab-1a553d235739@ex-ample.com>
Date: Thu, 24 Apr 2025 21:46:31 +0200
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
From: Jill <jill@ex-ample.com>
Subject: Example
To: Ben <ben@ex-ample.com>
Content-Language: en-US
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  </head>
  <body>
    From: Joe <a class="moz-txt-link-rfc2396E" href="mailto:joe@ex-ample.com">&lt;joe@ex-ample.com&gt;</a><br>
    Sent: 24 April 2025 08:22<br>
    To: Maria <a class="moz-txt-link-rfc2396E" href="mailto:maria@ex-ample.com">&lt;maria@ex-ample.com&gt;</a><br>
    Subject: Forwarded example message
  </body>
</html>
```

### Expected behavior

Do not show a suspicious link warning

### Actual behavior

suspicious link warnings

### Mail app version

5.0.2

### Nextcloud version

30.0.10

### Mailserver or service

Sendmail

### Operating system

Ubuntu Linux 24.04

### PHP engine version

PHP 8.3

### Nextcloud memory caching

Redis

### Web server

Apache (supported)

### Database

MySQL

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by hamza221**
fix #11028

### CODE REVIEW

**Review by st3iny — COMMENTED** [review]
Please leave the comment. It is the u flag (see the end of the regex) and I added the part in parentheses as an explanation.

File: lib/Service/PhishingDetection/LinkCheck.php [hunk 1]
```diff
@@ -65,9 +65,9 @@ public function run(string $htmlMessage) : PhishingDetectionResult {
 			}
 
 			// Handle links that are wrapped in brackets, quotes, etc.
-			// Need to use preg_match with the u(nicode) flag to properly match multibyte chars.
+			// Need to use preg_match with the (unicode) flag to properly match multibyte chars.
```
Comment (st3iny) [inline lib/Service/PhishingDetection/LinkCheck.php:68]: ... the comment here

Comment (hamza221) [reply lib/Service/PhishingDetection/LinkCheck.php:68]: mb
