### PR TITLE
Catch duplicate inserts of tags

### LINKED ISSUE #4814: Unique constraint violation during mailbox sync
### Expected behavior

Tag constraint violations are checked (avoided) or handled.

### Actual behavior

Tags cause a sync error for my work email account

```
[debug] Running initial sync for 79
[debug] Initial sync 1965:INBOX - fetch all messages from IMAP took 11s
[debug] Unlocking mailbox 79 from vanished messages sync
[debug] Unlocking mailbox 79 from changed messages sync
[debug] Unlocking mailbox 79 from new messages sync

In ImapToDbSynchronizer.php line 242:
                                                                                                                                                                                                                                       
  Sync failed for 1965:INBOX: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '<6821bb5a61ec6310b400bc815e6323e9@cloud.nextcloud.com>-6' for key 'mail_msg_tag_i  
  d_idx'                                                                                                                                                                                                                               
                                                                                                                                                                                                                                       

In ExceptionConverter.php line 60:
                                                                                                                                                                                                                 
  An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '<6821bb5a61ec6310b400bc815e6323e9@cloud.nextcloud.com>-6' for key 'mail_msg_tag_id_idx'  
                                                                                                                                                                                                                 

In Exception.php line 26:
                                                                                                                                                                  
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '<6821bb5a61ec6310b400bc815e6323e9@cloud.nextcloud.com>-6' for key 'mail_msg_tag_id_idx'  
                                                                                                                                                                  

In Statement.php line 82:
                                                                                                                                                                  
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '<6821bb5a61ec6310b400bc815e6323e9@cloud.nextcloud.com>-6' for key 'mail_msg_tag_id_idx'  
                                                                                                                                                                  

mail:account:sync [-f|--force] [--] <account-id>
```

### Mail app

**Mail app version:** latest master

### PR DESCRIPTION
**Pull request by miaulalala**
Fixes #4814

### CODE REVIEW

File: lib/Db/TagMapper.php [hunk 1]
```diff
@@ -115,10 +117,15 @@ public function tagMessage(Tag $tag, string $messageId, string $userId): void {
...
-		$qb->setValue('imap_message_id', $qb->createNamedParameter($messageId));
-		$qb->setValue('tag_id', $qb->createNamedParameter($tag->getId(), IQueryBuilder::PARAM_INT));
-		$qb->execute();
+		$qb->insert('mail_message_tags')
+		   ->setValue('imap_message_id', $qb->createNamedParameter($messageId))
+		   ->setValue('tag_id', $qb->createNamedParameter($tag->getId(), IQueryBuilder::PARAM_INT));
+		try {
+			$qb->execute();
+		} catch( Exception $e ) {
+			// ? check for type of exception here?
```
Comment (ChristophWurst) [inline lib/Db/TagMapper.php:126]: ugly code ahead, please protect your eyes

```php
<?php

use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use OCP\DB\Exception;

try {
    // ...
} catch (\Exception $e) {
    if (class_exists(Exception::class) && ($e instanceof Exception) && $e->getReason() === Exception::REASON_UNIQUE_CONSTRAINT_VIOLATION) {
        // OK -> ignore
    } else if (class_exists(UniqueConstraintViolationException::class) && ($e instanceof UniqueConstraintViolationException)) {
        // OK -> ignore
    }
    
    // oh no -> panic
    throw $e;
}
``

**Review by ChristophWurst — APPROVED** [review]
Works when combined with https://github.com/nextcloud/mail/pull/4822
