### PR TITLE
Change the timeout value to fit the dialogs

### LINKED ISSUE #6428: Undo timeout on mail doesnt match the dialogs toast timeout
### Steps to reproduce

our timeout: https://github.com/nextcloud/mail/blob/main/src/store/outbox/actions.js#L159
https://github.com/nextcloud/mail/blob/main/src/store/constants.js

dialogs timeout: https://github.com/nextcloud/nextcloud-dialogs/blob/master/lib/toast.ts#L182-L183)

### Expected behavior

The timeout matches

### Actual behavior

It doesnt match

### Mail app version

_No response_

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by GretaD**
fixes #6428

### CODE REVIEW

File: src/store/constants.js [hunk 1]
```diff
@@ -23,4 +23,4 @@ export const UNIFIED_ACCOUNT_ID = 0
 export const UNIFIED_INBOX_ID = 'unified'
 export const PRIORITY_INBOX_ID = 'priority'
 export const PAGE_SIZE = 20
-export const UNDO_DELAY = 7 * 1000
+export const UNDO_DELAY = 10 * 1000
```
Comment (ChristophWurst) [inline src/store/constants.js:26]: yes but no. This now *matches* the value of the dialogs package, but there is no guarantee that they will stay in sync. See https://github.com/nextcloud/nextcloud-dialogs/pull/210. The constant is exposed. Let's get the value from the lib. If the value ever changes there, it wouldn't break our code.

File: src/components/NewMessageModal.vue [hunk 2]
```diff
@@ -137,9 +136,9 @@ export default {
 				})
 			}
 
-			if (!data.sendAt || data.sendAt < Math.floor((now + UNDO_DELAY) / 1000)) {
+			if (!data.sendAt || data.sendAt < Math.floor((now + TOAST_UNDO_TIMEOUT) / 1000)) {
 				// Awaiting here would keep the modal open for a long time and thus block the user
-				this.$store.dispatch('outbox/sendMessageWithUndo', { id: this.composerData.id })
+				await this.$store.dispatch('outbox/sendMessageWithUndo', { id: this.composerData.id })
```
Comment (st3iny) [inline src/components/NewMessageModal.vue:141]: Are you sure to await here? See the comment one line above.

Comment (GretaD) [reply src/components/NewMessageModal.vue:141]: i dont remember adding that, maybe phpstorm lint did that?

File: src/store/constants.js [hunk 3]
```diff
@@ -23,4 +23,3 @@ export const UNIFIED_ACCOUNT_ID = 0
 export const UNIFIED_INBOX_ID = 'unified'
 export const PRIORITY_INBOX_ID = 'priority'
 export const PAGE_SIZE = 20
-export const UNDO_DELAY = 7 * 1000
```
Comment (ChristophWurst) [inline src/store/constants.js:26]: you can leave the constant for better readability and assign the value of `TOAST_UNDO_TIMEOUT` here.

Comment (GretaD) [reply src/store/constants.js:26]: but then it will not be used anywhere, you mean - export const UNDO_DELAY = TOAST_UNDO_TIMEOUT, and then use UNDO _DELAY, instead of using directly TOAST_UNDO_TIMEOUT on our actions?

Comment (ChristophWurst) [reply src/store/constants.js:26]: > then use UNDO _DELAY, instead of using directly TOAST_UNDO_TIMEOUT on our actions

yes.

File: src/components/NewMessageModal.vue [hunk 4]
```diff
@@ -139,7 +139,7 @@ export default {
 
 			if (!data.sendAt || data.sendAt < Math.floor((now + UNDO_DELAY) / 1000)) {
 				// Awaiting here would keep the modal open for a long time and thus block the user
-				this.$store.dispatch('outbox/sendMessageWithUndo', { id: this.composerData.id })
+				 this.$store.dispatch('outbox/sendMessageWithUndo', { id: this.composerData.id })
```
Comment (ChristophWurst) [inline src/components/NewMessageModal.vue:142]: revert

**Review by ChristophWurst — CHANGES_REQUESTED** [review]

**Review by ChristophWurst — APPROVED** [review]
