### PR TITLE
fix: list layout height

### LINKED ISSUE #11197: List layout is not using the full height
### Steps to reproduce

1. Switch to the list layout: Mail settings -> General -> Layout -> Choose "List"
2. Open your inbox.
3. Observe, that the list is cut off and not using the available height fully.

Image

### Expected behavior

The list should use the full height.

### Actual behavior

It is not using the full height and is instead cut off.

### Mail app version

c.nc.c

### Nextcloud version

c.nc.c

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

None

### Nextcloud memory caching

_No response_

### Web server

None

### Database

None

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by GretaD**
fixes #11197

sorry, i have a personal account with sensitive data, so i cannot take a screenshot.

### CODE REVIEW

File: src/components/MailboxThread.vue [hunk 1]
```diff
@@ -429,7 +430,18 @@ export default {
 		margin: 0 !important;
 	}
 }
-
+:deep(.app-content-list) {
```
Comment (ChristophWurst) [inline src/components/MailboxThread.vue:433]: there are now two deep selectors for the same element. would it make sense to consolidate?

File: src/components/MailboxThread.vue [hunk 2]
```diff
@@ -477,15 +488,23 @@ export default {
...
 }
  // temporary fix
 :deep(.app-content-list) {
 	min-height: 0;
+	position: absolute;
+	overflow: scroll;
+	width: 100% !important;
+	top: 52px;
+}
+:deep(.app-content-wrapper.app-content-wrapper--no-split.app-content-wrapper--show-details) {
```
Comment (st3iny) [inline src/components/MailboxThread.vue:507]: This will break as soon as the component is changed upstream.

However, I didn't dig into the problem and have no other solution.

Comment (GretaD) [reply src/components/MailboxThread.vue:507]: we run in the same problem over and over again. If i dont add this, we will have 2 scroll bars. I dont have any other idea either without breaking something else.
