### PR TITLE
Fix automatic email signature on the composer

### LINKED ISSUE #6361: The new compose modal does not seem to add the email signature
### Steps to reproduce

1. Set a mail signature in the mail account settings
2. Click on "new message" or on "reply" in a received mail

### Expected behavior

The signature should be shown at the bottom of the message.

### Actual behavior

No signature appear. **However**, selecting another account (if you have multiple set) will change the signature to the one of the corresponding account. Switching back to the original account also put the correct signature.

### Mail app version

1.12.0

### Mailserver or service

Not relevant

### Operating system

Fedora

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Fixes #6361

### CODE REVIEW

**Review by st3iny — COMMENTED** [review]
It works fine when composing a new mail. However, when editing messages in outbox there are 2 problems.

## HTML-Editor
The signature "jumps" when editing existing messages.

Peek 2022-05-06 10-29

## Plain-Editor
The Signature is added multiple times. Each time I edit the message a new copy is appended. That is possibly unrelated because it is caused by the forced selection of the HTML-Editor by default (ref https://github.com/nextcloud/mail/issues/6264).

Peek 2022-05-06 10-35

**Comment by JuliaKirschenheuter** [comment]
@st3iny @ChristophWurst @nimishavijay I've tested actual behavior. First of all: if signature should be in a message, then it needs a "place" in a composer body, like ``` <p></p>```. This was already implemented. 
Signature needs ``` <p></p>``` to be placed in a message. If signature is there - body of composer is not empty, and saving process will be triggered. Right now i don't know how to exclude a signature from other things in message body. 

Now it works like: if there is no signature, and all other stuff is empty or was not changed - saving process will not be triggered. If there is a signature - saving process will be triggered.

**Comment by ChristophWurst** [comment]
I'm not sure I can follow.

Does the signature work now? Is there anything left to do?

**Comment by nimishavijay** [comment]
Ideally if there is no other text other than signature, it should not be saved, otherwise there would be a lot of drafts saved with just the signature. But if it is not possible, then no worries :)

**Comment by ChristophWurst** [comment]
* [ ] BUG

1) Configure one account
2) Set a signature
3) Write a new message
4) Click *Undo*

Expected: signature is there like before
Actual: signature is there twice

Bildschirmfoto vom 2022-05-20 08-55-02

**Comment by ChristophWurst** [comment]
This still happens.

Bildschirmfoto vom 2022-05-20 13-19-22

I'm using plain text mode.

Bildschirmfoto vom 2022-05-20 13-19-36

**Comment by JuliaKirschenheuter** [comment]
> This still happens.
> I'm using plain text mode.

Yes, this problem is only in a plain text mode. We are trying to solve this problem

**Comment by ChristophWurst** [comment]
Right now the front-end converts the editor input to html/plain text before it is sent to the server. How about we always store the HTML and let the backend convert to plain if necessary? Would that help with the signature detection @kesselb?

**Comment by kesselb** [comment]
> Would that help with the signature detection @kesselb?

Yep. If we keep the message in html the existing logic works (that should be already the case when you switch the html). If possible I would always store html and the version to sent. If the users open the message again from the outbox we use the stored html for the editor and update the version to sent.

**Comment by ChristophWurst** [comment]
Then let's add a migration for this new column and attribute, shall we?

**Comment by ChristophWurst** [comment]
To update myself on the current status: the signature is still inserted twice.

Let's add the column then.

**Comment by ChristophWurst** [comment]
Outbox messages now have a nullable `editorBody`.

New todo
1) Fill it with the editor contents when saving an outbox message
2) Load the contents for the editor. Beware of the possible null value. You have to use `text` as a fallback if `bodyText` is not there (upgraded from an older app version).

**Comment by ChristophWurst** [comment]
Info.xml needs a bump so the migration runs

**Comment by ChristophWurst** [comment]
@GretaD the bump is here. Go to main. Run `occ upgrade`. Then switch to this branch and run upgrade again. Then your `oc_loca_messages` will have a `editor_body` column

**Review by GretaD — APPROVED** [review]

File: src/components/NewMessageModal.vue [hunk 1]
```diff
@@ -11,6 +11,7 @@
 			:subject="composerData.subject"
 			:attachments-data="composerData.attachments"
 			:body="composerData.body"
+			:editor-body="composerData.editorBody"
```
Comment (ChristophWurst) [inline src/components/NewMessageModal.vue:14]: what happens if `editorBody` is null? Every installation with existing outbox messages will run into this.

Comment (ChristophWurst) [reply src/components/NewMessageModal.vue:14]: https://github.com/nextcloud/mail/pull/6372#issuecomment-1143325891

**Comment by kesselb** [comment]
> @GretaD the bump is here. Go to main. Run `occ upgrade`. Then switch to this branch and run upgrade again. Then your `oc_loca_messages` will have a `editor_body` column

I don't see the migration anymore.

**Comment by ChristophWurst** [comment]
And this, friends, is why we don't force push.

**Comment by ChristophWurst** [comment]
I've pushed the previous state to `fix/fix-6361-composer-email-signature-restored`.

**Comment by kesselb** [comment]
- [ ] **Losing formatting when clicking outside the modal**

- Write a **plain** text message (more than one word, multiple lines, newlines, ...)
- Select send later
- Open the message again
- Click outside the composer window (=> this will close the message
- Open the message again
- Newlines are gone

https://user-images.githubusercontent.com/3902676/171648216-c6ab7dd0-48ff-429b-8b42-376e1a047f84.mp4

File: src/components/NewMessageModal.vue (hunk 1 above)
Comment (JuliaKirschenheuter) [reply src/components/NewMessageModal.vue]: i would say this is solved

**Comment by JuliaKirschenheuter** [comment]
> - [ ] **Losing formatting when clicking outside the modal**

@ChristophWurst @kesselb should we fix this in a separate bug? it is still very important, but would be great to fix this signatures first

File: src/components/NewMessageModal.vue [hunk 2]
```diff
@@ -99,6 +102,7 @@ export default {
 				accountId: data.account,
 				subject: data.subject,
 				body: data.isHtml ? data.body.value : toPlain(data.body).value,
+				editorBody: data.body.value,
```
Comment (ChristophWurst) [inline src/components/NewMessageModal.vue:105]: unused

**Review by ChristophWurst — APPROVED** [review]
Does the trick

**Comment by ChristophWurst** [comment]
Be careful with your final rebase. You have "fixups" that aren't following the git fixup conventions. Git rebase will *not* be able to reorder your commits and squash them automatically. You will have to order them yourself. Right now the second from last commit will probably be a fixup of the merge and therefore potentially dropped.

If the IDE can't do it please do fixup commits via CLI and use the `--fixup=<sha1>` switch.

File: src/components/NewMessageModal.vue (hunk 2 above)
Comment (JuliaKirschenheuter) [reply src/components/NewMessageModal.vue:105]: this one is needed, because action "updateMessage" needs editorBody. If i would remove this, it would be impossible to open again the undo-sendet-message

File: src/components/NewMessageModal.vue [hunk 3]
```diff
@@ -181,6 +185,19 @@ export default {
...
 		},
+		convertEditorBody(composerData) {
+			if (composerData.editorBody !== null) {
+				return composerData.editorBody
+			}
+			if (composerData.body === null) {
+				return ''
+			}
+			if (composerData.body.format !== 'html') {
+				return toHtml(composerData.body).value
```
[the remark this answers is not in the document]
Comment (ChristophWurst) [reply src/components/NewMessageModal.vue:196]: https://github.com/nextcloud/mail/blob/213c25884ed2162e8d25e8ca3b6a6c6255170ea1/src/util/text.js#L199-L201 returns the identical object.

[the remark this answers is not in the document]
Comment (JuliaKirschenheuter) [reply src/components/NewMessageModal.vue:196]: ah, thank you

[the remark this answers is not in the document]
Comment (JuliaKirschenheuter) [reply src/components/NewMessageModal.vue:196]: But, i still cannot remove it. This is still needed, if backend give a plain text, this should be explicitly converted to html. Otherwise we would run into problem described here https://github.com/nextcloud/mail/pull/6372#issuecomment-1144910893

File: src/components/NewMessageModal.vue [hunk 4]
```diff
@@ -181,6 +185,19 @@ export default {
...
+			} else {
+				 return composerData.body.value
+			}
```
Comment (ChristophWurst) [inline src/components/NewMessageModal.vue:199]:
```suggestion
			toHtml(composerData.body).value
```

This is the change I suggested.

Leave it as is if it doesn't make sense. It's just a nitpick.

File: src/components/NewMessageModal.vue (hunk 3 above)
[the remark this answers is not in the document]
Comment (ChristophWurst) [reply src/components/NewMessageModal.vue:196]: I think my intent was not clear. I did not suggest dropping the conversion, only your if-else condition.

```js
			if (composerData.body.format !== 'html') {
				return toHtml(composerData.body).value
			} else {
				 return composerData.body.value
			}
```

should be

```js
			return toHtml(composerData.body).value
```

If this doesn't make sense then leave the code as is.

**Review by ChristophWurst — DISMISSED** [review]
Works

I've pushed a fixup for the now outdated version in the migration and allow the migration to run more than once.

**Comment by ChristophWurst** [comment]
> Losing formatting when clicking outside the modal

The problem already occurs when the modal is *opened*, when we "stop" the message. The `showMessageComposer` action uses `data.body.value` for `editorBody`, the plain text version.

File: src/store/actions.js [hunk 5]
```diff
@@ -368,6 +368,7 @@ export default {
 			originalSendAt = data.sendAt
 			const message = {
 				...data,
+				editorBody: data.body.value,
```
Comment (ChristophWurst) [inline src/store/actions.js:371]: drop this line to fix https://github.com/nextcloud/mail/pull/6372#issuecomment-1144910893

`data` has a `editorBody` property with the correct value, the HTML markup

In its current state the plain text is saved as editor body:
Bildschirmfoto vom 2022-06-08 12-44-26

File: src/store/actions.js [hunk 6]
```diff
@@ -391,6 +392,7 @@ export default {
 				message: {
 					...message.data,
 					body: message.data.isHtml ? body.value : toPlain(body).value,
+					editorBody: body.value,
```
Comment (ChristophWurst) [inline src/store/actions.js:395]: this is also wrong and causes https://github.com/nextcloud/mail/pull/6372#issuecomment-1144910893

File: src/store/actions.js (hunk 5 above)
Comment (JuliaKirschenheuter) [reply src/store/actions.js]: Thanks, fixed.

File: src/components/OutboxMessageListItem.vue [hunk 7]
```diff
@@ -145,6 +145,7 @@ export default {
 			const message = {
 				...this.message,
 				failed: false,
+				editorBody: this.message.body.value,
```
[the remark this answers is not in the document]
Comment (ChristophWurst) [reply src/components/OutboxMessageListItem.vue:148]: Delete the line to fix *Send now* :)

File: src/components/Composer.vue [hunk 8]
```diff
@@ -926,6 +942,9 @@ export default {
 		},
 		onInputChanged() {
 			this.callSaveDraft(true, this.getMessageData)
+			this.editorPlainTextInputReady = true
```
Comment (ChristophWurst) [inline src/components/Composer.vue:945]: this attribute does not exist

**Comment by ChristophWurst** [comment]
:warning: I will push fixups for the linter and test failure

File: src/components/Composer.vue (hunk 8 above)
Comment (JuliaKirschenheuter) [reply src/components/Composer.vue]: removed onInputChanged

**Review by ChristophWurst — APPROVED** [review]
Works

The only thing I noticed is that if you have two accounts, editing an outbox message always has the first account selected in the alias picker. So even if your message is sent from the second alias, the first one is shown. To switch to the first you need to click the second and then the first. This is very likely an issue with the outbox/composer, unrelated to this change. I'll create a ticket.
