### PR TITLE
Duplicity validation

### LINKED ISSUE #6024: Possible to create tags with same name while in the modal
### Expected behavior

People shouldn’t be able to create tags with the exact same name.

### Actual behavior

Currently it’s possible to create tags with the exactly same name, which makes little sense. After a refresh, the duplicates are gone though, making it look like a bug that they are visible in the first place:
image

### Steps to reproduce

1. Edit tags of a mail
2. Create some tags with the same name
3. Then to confirm they are gone, refresh and check that the duplicate tags are gone again

### Mail app version

_No response_

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Zivangu9**
Fix #6024

Here is my solution to the [issue](https://github.com/nextcloud/mail/issues/6024)

Add a validation when trying to create a new tag, in case the imapLabel already exists in the list of tags it is rejected

### CODE REVIEW

File: src/components/TagModal.vue [hunk 1]
```diff
@@ -173,7 +173,10 @@ export default {
 		async createTag(event) {
 			this.editing = true
 			const displayName = event.target.querySelector('input[type=text]').value
-
+			if(this.$store.getters.getTags.some(tag=>tag.imapLabel === "$"+displayName)){
+				showError(this.t('mail', 'Duplicity error, unable to create the tag.'))
```
Comment (st3iny) [inline src/components/TagModal.vue:177]:
```suggestion
				showError(this.t('mail', 'Tag already exists'))
```

A little bit more specificity for the users.

File: src/components/TagModal.vue [hunk 2]
```diff
@@ -173,7 +173,10 @@ export default {
 		async createTag(event) {
 			this.editing = true
 			const displayName = event.target.querySelector('input[type=text]').value
-
+			if(this.$store.getters.getTags.some(tag=>tag.imapLabel === "$"+displayName)){
```
Comment (st3iny) [inline src/components/TagModal.vue:176]:
```suggestion
			if(this.$store.getters.getTags.some(tag => tag.displayName === displayName)){
```
Tags have a display name already so you can omit the conversion. This also fixes linter issues.

**Review by st3iny — APPROVED** [review]
Thanks a lot for your contribution. I left some feedback on the code.

Please sign-off your commits to make our DCO bot happy. To add your Signed-off-by line to every commit in this branch:

1. Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
2. In your local branch, run: `git rebase HEAD~1 --signoff`
3. Force push your changes to overwrite the branch: `git push --force-with-lease origin main`

Taken from https://github.com/nextcloud/mail/pull/6560/checks?check_run_id=6602375158
Ref https://github.com/apps/dco

**Comment by st3iny** [comment]
Awesome! Now please squash all commits into one and sing it off.

**Comment by Zivangu9** [comment]
I think I did something wrong because more commits appeared than before.
Is it normal, or should I fix something?

**Review by st3iny — APPROVED** [review]

**Comment by ChristophWurst** [comment]
Thanks a lot @Zivangu9! :)
