### PR TITLE
Stop message from sending while editing

### LINKED ISSUE #6156: Outbox message is sent while it's edited
### Steps to reproduce

1. Compose a new message but introduce an error, e.g. an invalid email for the recipient
2. Send the message
3. Find the message in the outbox
4. Edit the message to fix the recipient
5. Wait for the draft to save
6. Change the message another time

### Expected behavior

The message isn't sent until I'm done with my modifications.

### Actual behavior

The message might be found by the background job and sent while I'm editing it.

### Mail app version

v1.12

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### Additional info

This was originally discovered in https://github.com/nextcloud/mail/pull/5970#issuecomment-1075326555 and is a theoretical problem until we have https://github.com/nextcloud/mail/issues/5886.

I've discussed the problem with @st3iny and there are two possible solutions:

1) The frontend updates the message timestamp before any editing happens. The background job will therefore not attempt to send the message. Once editing is done (close modal) the current timestamp is assigned and either frontend or backend will send the message.
2) When the frontend migrates the outbox message to a draft. The modal operates on that draft and when the editing ends, the message is migrated back. This requires https://github.com/nextcloud/mail/issues/4768.

It looks like 1) is simpler to do right now so I'd go with that. Once we have https://github.com/nextcloud/mail/issues/4768 we revisit and see if 2) makes the experience any smoother.

### PR DESCRIPTION
**Pull request by GretaD**
fixes #6156

### CODE REVIEW

File: src/components/NewMessageModal.vue [hunk 1]
```diff
@@ -17,8 +17,7 @@
 			:draft="saveDraft"
 			:send="sendMessage"
 			:forwarded-messages="forwardedMessages"
-			@discard-draft="discardDraft"
-			@close="$emit('close')" />
+			@discard-draft="discardDraft" />
```
Comment (st3iny) [inline src/components/NewMessageModal.vue:20]: This change is not related but Composer never emits `close`.

## Proof
```js
$ grep -n '\$emit' src/components/Composer.vue
872:                            this.bus.$emit('insertSignature', signatureValue, this.selectedAlias.signatureAboveQuote)
904:                    this.bus.$emit('onAddLocalAttachment')
908:                    this.bus.$emit('onAddCloudAttachment')
912:                    this.bus.$emit('onAddCloudAttachmentLink')
1055:                   this.$emit('discard-draft', id)
```

Comment (JuliaKirschenheuter) [reply src/components/NewMessageModal.vue:20]: Could we rename a outbox mutation "stopMessage" to something like "deleteScheduledValue" ? it will be a bit clearer

**Review by JuliaKirschenheuter — APPROVED** [review]

File: src/components/NewMessageModal.vue (hunk 1 above)
Comment (ChristophWurst) [reply src/components/NewMessageModal.vue:20]: I'm the original author of the name so take this with caution but I still think the name makes sense. The action name describes *what* it does, not *how*.

We also have *sendMessage* and not *postMessageToServer* and similar. It's a always a bit abstract.

*deleteScheduledValue* is too specific to the implementation IMO.

**Comment by st3iny** [comment]
@ChristophWurst Backport to 1.12.1 or wait for 1.13.0?

**Comment by ChristophWurst** [comment]
because I don't have an ETA for the v1.13

File: src/store/actions.js [hunk 2]
```diff
@@ -357,14 +357,40 @@ export default {
...
 			data,
 			forwardedMessages,
 			templateMessageId,
+			originalSendAt,
 		})
 	},
-	async closeMessageComposer({ commit }) {
+	async closeMessageComposer({ commit, dispatch, getters }, { restoreOriginalSendAt }) {
+		// Restore original sendAt timestamp when requested
+		const message = getters.composerMessage
```
Comment (ChristophWurst) [inline src/store/actions.js:381]: The Vuex `composerMessage` holds the *initial value* of the composer when it opens. This operation would override all modifications done before closing the modal.

* Write a new message
* Schedule it
* Reopen
* Make changes
* Close the modal

-> edits are lost

Comment (ChristophWurst) [reply src/store/actions.js:381]: https://github.com/nextcloud/mail/issues/6470
