### PR TITLE
fix: phishing detection fixes

### LINKED ISSUE #10423: URLs in angle brackes trigger phishing detection
### Steps to reproduce

1. Receive an email with a URL that is in angle backets

### Expected behavior

Phishing detection is okay with it

### Actual behavior

Image

Phishing detection alarms me

### Mail app version

v4.1.0-beta2

### Nextcloud version

_No response_

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

None

### Nextcloud memory caching

_No response_

### Web server

None

### Database

None

### Additional info

_No response_

### LINKED ISSUE #10452: Bug: [mail] Error: Failed to parse time string
### Steps to reproduce

When reading mails, under Nextcloud 30.0.3 with mail app version 4.0.7, I get following lines in the log file;

[mail] Error: Failed to parse time string (Fri, 06 Dec 2024 00:49:10 +0600 (+06)) at position 32
((): Unexpected character - GET /apps/mail/api/messages/22/body
from 78.xx.xx.xx by admin at Dec 7, 2024, 8:55:01 AM

Any clue on this?

Regards.

### Actual behavior

[mail] Error: Failed to parse time string (Fri, 06 Dec 2024 00:49:10 +0600 (+06)) at position 32 ((): Unexpected character
	GET /apps/mail/api/messages/22/body
	from 78.xx.xx.xx by admin at Dec 7, 2024, 8:55:01 AM

### Mail app version

4.0.7

### Nextcloud version

30.0.3

### PHP engine version

PHP 8.2

### Nextcloud memory caching

ocache - memcache & redis

### Web server

Nginx

### Database

MariaDB

### Additional info

```
  "reqId": "9BqqWNX132fLnYN7LARY",
  "level": 3,
  "time": "2024-12-07T05:55:01+00:00",
  "remoteAddr": "78.xx",
  "user": "cloudadmin",
  "app": "mail",
  "method": "GET",
  "url": "/apps/mail/api/messages/22/body",
  "message": "Failed to parse time string (Fri, 06 Dec 2024 00:49:10 +0600 (+06)) at position 32 ((): Unexpected character",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
  "version": "30.0.3.2",
  "exception": {
    "Exception": "Exception",
    "Message": "Failed to parse time string (Fri, 06 Dec 2024 00:49:10 +0600 (+06)) at position 32 ((): Unexpected character",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/TimeFactory.php",
        "line": 44,
        "function": "__construct",
        "class": "DateTime",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/mail/lib/Service/PhishingDetection/DateCheck.php",
        "line": 27,
        "function": "getDateTime",
        "class": "OC\\AppFramework\\Utility\\TimeFactory",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/mail/lib/Service/PhishingDetection/PhishingDetectionService.php",
        "line": 40,
        "function": "run",
        "class": "OCA\\Mail\\Service\\PhishingDetection\\DateCheck",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php",
        "line": 520,
        "function": "checkHeadersForPhishing",
        "class": "OCA\\Mail\\Service\\PhishingDetection\\PhishingDetectionService",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php",
        "line": 237,
        "function": "parseHeaders",
        "class": "OCA\\Mail\\IMAP\\ImapMessageFetcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php",
        "line": 308,
        "function": "fetchMessage",
        "class": "OCA\\Mail\\IMAP\\ImapMessageFetcher",
        "type": "->"
      },
      {
        "function": "OCA\\Mail\\IMAP\\{closure}",
        "class": "OCA\\Mail\\IMAP\\MessageMapper",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php",
        "line": 298,
        "function": "array_map"
      },
      {
        "file": "/var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php",
        "line": 71,
        "function": "findByIds",
        "class": "OCA\\Mail\\IMAP\\MessageMapper",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/mail/lib/Service/MailManager.php",
        "line": 185,
        "function": "find",
        "class": "OCA\\Mail\\IMAP\\MessageMapper",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/mail/lib/Controller/MessagesController.php",
        "line": 211,
        "function": "getImapMessage",
        "class": "OCA\\Mail\\Service\\MailManager",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 208,
        "function": "getBody",
        "class": "OCA\\Mail\\Controller\\MessagesController",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 114,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
        "line": 161,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/var/www/nextcloud/lib/base.php",
        "line": 1003,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/index.php",
        "line": 24,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/var/www/nextcloud/lib/private/AppFramework/Utility/TimeFactory.php",
    "Line": 44,
    "message": "Failed to parse time string (Fri, 06 Dec 2024 00:49:10 +0600 (+06)) at position 32 ((): Unexpected character",
    "exception": [],
    "CustomMessage": "Failed to parse time string (Fri, 06 Dec 2024 00:49:10 +0600 (+06)) at position 32 ((): Unexpected character"
  },
  "id": "6753e4a7ee248"
```

### PR DESCRIPTION
**Pull request by hamza221**
fix #10452
fix #10423

### CODE REVIEW

**Review by ChristophWurst — COMMENTED** [review]
Would it be possible to cover the two cases with unit tests?

File: tests/Unit/Service/Phishing/DateCheckTest.php [hunk 1]
```diff
@@ -65,4 +65,24 @@ public function testInTheFuture(): void {
...
+			->withConsecutive(
+				['now'],
+				['invalid date']
+			)
+			->will(
+				$this->onConsecutiveCalls(
+					$this->returnValue(new \DateTime('now')),
+					$this->throwException(new \DateException())
+				)
+			);
```
Comment (ChristophWurst) [inline tests/Unit/Service/Phishing/DateCheckTest.php:81]: PHPUnit is removing withConsecutive

See https://stackoverflow.com/questions/75389000/replace-phpunit-method-withconsecutive-abandoned-in-phpunit-10 for a similar alternative approach

**Review by ChristophWurst — COMMENTED** [review]
Small nitpick to prevent new technical debt

File: tests/Unit/Service/Phishing/DateCheckTest.php [hunk 2]
```diff
@@ -65,4 +65,23 @@ public function testInTheFuture(): void {
...
+		$this->time->expects($this->exactly(2))
+			->method('getDateTime')
+			->willReturnCallback(function ($argument): DateTime {
+				static $callCount = 0;
+				$callCount++;
+
+				if ($callCount === 1) {
+					return new \DateTime('now');
+				}
+				throw new \DateException();
```
Comment (ChristophWurst) [inline tests/Unit/Service/Phishing/DateCheckTest.php:79]: use `match` of `if` on the argument. then you make the mock dependent on the input, not the order of calls. This is also the reason why the consecutive method in phpunit was removed.

**Review by ChristophWurst — APPROVED** [review]
