### PR TITLE
Fix the overlapping of primary menu with recipient

### LINKED ISSUE #8191: Primary action menu overlaps with recipient on small screen
### Steps to reproduce

1. Open mail on small screen
2. Look at one thread header
3.

### Expected behavior

Nice design

### Actual behavior

I cannot read the recipient

### Mail app version

3.0.0-beta

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

Screenshot from 2023-03-03 09-57-49

### PR DESCRIPTION
**Pull request by GretaD**
fixes #8191

Im trying to adapt text logic for mail: https://github.com/nextcloud/text/blob/8a17046aa440df841fe9182205d80ce937068c1a/src/components/Menu/MenuBar.vue

and also using inline prop that `NcActions` uses

[Screencast from 08.05.2023 19:06:28.webm](https://user-images.githubusercontent.com/12728974/236886363-2937e7fa-2f8a-4c17-b9d2-3050b7c77c23.webm)

### CODE REVIEW

File: src/components/ThreadEnvelope.vue [hunk 1]
```diff
@@ -98,72 +99,75 @@
...
+						</NcActionButton>
+						<MenuEnvelope class="app-content-list-item-menu"
+							:envelope="envelope"
+							:mailbox="mailbox"
+							:with-reply="false"
+							:with-select="false"
+							:with-show-source="true"
+							@delete="$emit('delete',envelope.databaseId)" />
+						<NcActions />
+					</ncactions>
```
Comment (skjnldsv) [inline src/components/ThreadEnvelope.vue:170]:
```suggestion
							@delete="$emit('delete',envelope.databaseId)" />
					</NcActions>
```

File: src/components/MenuEnvelope.vue [hunk 2]
```diff
@@ -1,178 +1,173 @@
...
-					{{ t('mail', 'Move message') }}
-				</ActionButton>
-				<ActionButton :close-after-click="false"
-					@click="moreActionsOpen=true">
-					<template #icon>
-						<DotsHorizontalIcon
-							:title="t('mail', 'More actions')"
-							:size="20" />
-					</template>
+	<Fragment></Fragment>
```
Comment (skjnldsv) [inline src/components/MenuEnvelope.vue:3]:
```suggestion
	<Fragment>
```

File: src/components/MenuEnvelope.vue [hunk 3]
```diff
@@ -1,187 +1,183 @@
...
-				</ActionButton>
-				<ActionButton :close-after-click="false"
-					@click="moreActionsOpen=true">
-					<template #icon>
-						<DotsHorizontalIcon
-							:title="t('mail', 'More actions')"
-							:size="20" />
-					</template>
+	<Fragment>
+		<template v-if="!moreActionsOpen">
```
Comment (marcoambrosini) [inline src/components/MenuEnvelope.vue:4]: You still need the actions component wrapping the action items!

File: src/components/MenuEnvelope.vue [hunk 4]
```diff
@@ -1,187 +1,183 @@
 <!-- Standard Actions menu for Envelopes -->
 <template>
-	<div>
-		<Actions
```
Comment (marcoambrosini) [inline src/components/MenuEnvelope.vue:4]: I mean this one

File: src/components/MenuEnvelope.vue (hunk 3 above)
Comment (GretaD) [reply src/components/MenuEnvelope.vue:4]: this will just duplicate the primary actions outside the action menu, i have the actions on threadenvelope. And it was working fine, till i did the rebase and pulled on server.

**Comment by JohannesGGE** [comment]
I would remove at least one more action, particularly if there is an "unsubscribe" option.

|current calculation| (current calculation) -1 action |
|--|--|
|Screenshot from 2023-05-11 21-05-25|Screenshot from 2023-05-11 21-08-22|
|Screenshot from 2023-05-11 21-07-12|Screenshot from 2023-05-11 21-07-43|
|image|Screenshot from 2023-05-11 21-09-26|

**Comment by GretaD** [comment]
> I would remove at least one more action, particularly if there is an "unsubscribe" option.

Changed it, please have another look :)

**Review by JohannesGGE — APPROVED** [review]
:+1:
