### PR TITLE
Fix: Keep formatting after minimizing

### LINKED ISSUE #11286: All formatting disappears when you minimize the message pop-up
### Steps to reproduce

1. Write a mail message with formatting with html lists for example.
2. Minimize the pop-up and click around a little in your email inboxes.
3. Maximize the pop-up window at the bottom right again.

### Expected behavior

That the written text, including formatting, is exactly the same as before.

### Actual behavior

All formatting of the text has disappeared.

### Mail app version

5.1.4

### Nextcloud version

31.0.5

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

PHP 8.3

### Nextcloud memory caching

_No response_

### Web server

Apache (supported)

### Database

None

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by max65482**
Fixes #11286

### CODE REVIEW

File: src/components/NewMessageModal.vue [hunk 1]
```diff
@@ -610,7 +610,7 @@ export default {
 		async patchComposerData(data) {
 			this.changed = true
 			this.updateCookedComposerData()
-			await this.mainStore.patchComposerData(data)
+			await this.mainStore.patchComposerData({...data, isHtml: this.cookedComposerData.isHtml})
```
Comment (ChristophWurst) [inline src/components/NewMessageModal.vue]: Makes sense! I'll give this a test asap

**Review by ChristophWurst — APPROVED** [review]
Tested, works :clap: :sunglasses: 

The linter wants a space after `{` and before `}`
