### PR TITLE
Change `mail_accounts.provisioned` column to allow null

### LINKED ISSUE #4897: Column "oc_mail_accounts"."provisioned" is type Bool and also NotNull, so it can not store "false".
Installs have been failing because ~~the column `provisioned` in `mail_accounts` is not correctly created.~~ a few columns of different tables are oracle incompatible.

This bug is related to: https://github.com/nextcloud/server/pull/24055

Create a new migration that rewrites ~~the provisioned column to allow null.~~ these columns.

### PR DESCRIPTION
**Pull request by miaulalala**
Fixes #4897

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

File: lib/Db/MailAccount.php [hunk 1]
```diff
@@ -186,7 +186,7 @@ public function __construct(array $params = []) {
 		$this->addType('inboundPort', 'integer');
 		$this->addType('outboundPort', 'integer');
 		$this->addType('lastMailboxSync', 'integer');
-		$this->addType('provisioned', 'bool');
+		$this->addType('provisioned', 'boolean');
```
Comment (kesselb) [inline lib/Db/MailAccount.php:189]: fyi `bool` and `boolean` should work: https://www.php.net/manual/en/function.settype.php

Comment (ChristophWurst) [reply lib/Db/MailAccount.php:189]: Yes, we discussed this and concluded some consistency would be nice :)

Comment (kesselb) [reply lib/Db/MailAccount.php:189]: fine by me but weird to use boolean because for method signatures we need bool ;)
