### PR TITLE
Reroute to priority mailbox when a mailbox is deleted

### LINKED ISSUE #7406: Deleting a folder / mailbox clears the entire right content area including background
### Steps to reproduce

1. Delete a mailbox / folder via the left navigation
2. Observe the interface break

### Expected behavior

When deleting a folder / deleting a mailbox, Mail could automatically jump to open the Inbox of the same account? That would be similar to how we do it for deleting mails.

### Actual behavior

The content area gets wiped including background container:
image

### Mail app version

Current on cloud.nc.com

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by GretaD**
fixes #7406

### CODE REVIEW

File: src/components/NavigationMailbox.vue [hunk 1]
```diff
@@ -579,6 +579,12 @@ export default {
 							.dispatch('deleteMailbox', { mailbox: this.mailbox })
 							.then(() => {
 								logger.info(`mailbox ${id} deleted`)
+								this.$router.push({
```
Comment (ChristophWurst) [inline src/components/NavigationMailbox.vue:582]: the reroute should only happen if the *current mailbox* is deleted

**Review by ChristophWurst — CHANGES_REQUESTED** [review]

**Review by JuliaKirschenheuter — APPROVED** [review]
looks good, but haven't tested

File: src/components/NavigationMailbox.vue [hunk 2]
```diff
@@ -579,6 +579,14 @@ export default {
 							.dispatch('deleteMailbox', { mailbox: this.mailbox })
 							.then(() => {
 								logger.info(`mailbox ${id} deleted`)
+								if (this.$route.params.mailboxId) {
```
Comment (ChristophWurst) [inline src/components/NavigationMailbox.vue:582]:
```suggestion
								if (this.$route.params.mailboxId == this.mailbox.databaseId) {
```

**Review by ChristophWurst — CHANGES_REQUESTED** [review]

File: src/components/NavigationMailbox.vue [hunk 3]
```diff
@@ -579,6 +579,14 @@ export default {
 							.dispatch('deleteMailbox', { mailbox: this.mailbox })
 							.then(() => {
 								logger.info(`mailbox ${id} deleted`)
+								if (this.$route.params.mailboxId === this.mailbox.databaseId) {
```
Comment (ChristophWurst) [inline src/components/NavigationMailbox.vue:582]: This can never be truthy. `this.$route.params.mailboxId` is a string, `this.mailbox.databaseId` is a Number.

**Review by ChristophWurst — CHANGES_REQUESTED** [review]

File: src/components/NavigationMailbox.vue (hunk 3 above)
Comment (ChristophWurst) [reply src/components/NavigationMailbox.vue:582]: It is an int before the page load. After a page load it becomes a string.

**Comment by ChristophWurst** [comment]
@GretaD give this a final test but I think this is mergeable now

**Review by ChristophWurst — APPROVED** [review]
