### PR TITLE
Fix/filter forwarded and nonjunk tag

### LINKED ISSUE #4951: nonjunk and forwarded should not show as tags
### Expected behavior
It is shown as flag and not tag

### Actual behavior
database

### Mail app

**Mail app version:** master

cc @miaulalala

### PR DESCRIPTION
**Pull request by miaulalala**
Thunderbird sets a non- standard flag `nonjunk` on messages that are not junk. Additionally, some standard flags like `$forwarded` are missing.

Fixes #4951

### CODE REVIEW

**Review by GretaD — APPROVED** [review]
tested it and it works just good

File: lib/Model/IMAPMessage.php [hunk 1]
```diff
@@ -761,7 +765,7 @@ private function generateTagEntites(array $tags, string $userId): array {
 		$t = [];
 		foreach ($tags as $keyword) {
 			// Map the old $important to $label1 until we have caught them all
-			if ($keyword === '$important') {
+			if ($keyword === '$important' || $keyword === 'important') {
```
Comment (ChristophWurst) [inline lib/Model/IMAPMessage.php:768]: didn't we want to leave that one out for now until we know *important* is just a remnant from an earlier test?

Comment (miaulalala) [reply lib/Model/IMAPMessage.php:768]: I understood it as the other way around!

**Review by ChristophWurst — APPROVED** [review]
