### PR TITLE
fix: thread padding

### LINKED ISSUE #9786: Mail header has too much top and bottom padding
on list layout it looks like this:
Screenshot from 2024-07-01 11-09-54

### PR DESCRIPTION
**Pull request by GretaD**
in different layouts
before
Screenshot from 2024-07-24 12-06-25
Screenshot from 2024-07-24 12-05-59

after

Screenshot from 2024-07-24 12-02-07
Screenshot from 2024-07-24 12-01-52

fixes #9786

### CODE REVIEW

File: src/components/Thread.vue [hunk 1]
```diff
@@ -360,13 +360,16 @@ export default {
...
-	padding-left: 70px;
+	// while scrolling, the back button overlaps with subject on small screen
+	padding-left: 86px;
 	// grow and try to fill 100%
 	flex: 1 1 auto;
 	h2,
 	p {
 		padding-bottom: 7px;
 		margin-bottom: 0;
+		//some h2 styling coming from server add some space on top
```
Comment (ChristophWurst) [inline src/components/Thread.vue:371]:
```suggestion
		// some h2 styling coming from server add some space on top
```

**Review by ChristophWurst — APPROVED** [review]
