### PR TITLE
fix: align reply and attachment icon with subject

### LINKED ISSUE #9716: Attachment and reply icon does not alight with sender and subject in all mail layouts
### Steps to reproduce

1. Switch to list view
2. Receive a message with an attachment

### Expected behavior

Center-aligned items

### Actual behavior

image

### Mail app version

v3.7.0

### Mailserver or service

_No response_

### Operating system

_No response_

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by GretaD**
after
Screenshot from 2024-06-24 16-58-06

fixes #9716

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by st3iny — CHANGES_REQUESTED** [review]
Breaks preview texts.

| This PR | Without this PR |
| --- | --- |
| Bildschirmfoto_20240625_075343 | Bildschirmfoto_20240625_075337 |

File: src/components/Envelope.vue [hunk 1]
```diff
@@ -1053,6 +1060,10 @@ export default {
 	display: flex;
 	width: 200px;
 }
+.line-two {
+	display: flex;
+	align-items: center;
+}
```
Comment (st3iny) [inline src/components/Envelope.vue:1066]:
```suggestion
```

Without those styles the preview texts work again and the original issue still seems to be fixed.

Comment (GretaD) [reply src/components/Envelope.vue]: this is needed for the list layout, fixing it now

**Review by st3iny — APPROVED** [review]
Looks good now. Please squash.
