### PR TITLE
Chunking `in` statements for Oracle Compliance

### LINKED ISSUE #4941: Error: More than 1000 expressions in a list are not allowed on Oracle
### Expected behavior
Don't know. Saw the error below...

Follow-up of #4911
### Actual behavior

Error message: "More than 1000 expressions in a list are not allowed on Oracle."
```
{"reqId":"xbBp071iU3q7z6zx7mlc","level":3,"time":"2021-04-10T10:17:25+00:00","remoteAddr":"","user":"","app":"core","method":"POST","url":"/apps/mail/api/mailboxes/147/sync","message":{"Exception":"Doctrine\\DBAL\\Query\\QueryException","Message":"More than 1000 expressions in a list are not allowed on Oracle.","Code":0,"Trace":[{"file":"/srv/www/htdocs/nextcloud/lib/public/AppFramework/Db/QBMapper.php","line":320,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/srv/www/htdocs/nextcloud/apps/mail/lib/Db/MessageMapper.php","line":592,"function":"findEntities","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/srv/www/htdocs/nextcloud/apps/mail/lib/Service/Sync/SyncService.php","line":156,"function":"findIdsByQuery","class":"OCA\\Mail\\Db\\MessageMapper","type":"->"},{"file":"/srv/www/htdocs/nextcloud/apps/mail/lib/Service/Sync/SyncService.php","line":126,"function":"getDatabaseSyncChanges","class":"OCA\\Mail\\Service\\Sync\\SyncService","type":"->"},{"file":"/srv/www/htdocs/nextcloud/apps/mail/lib/Controller/MailboxesController.php","line":161,"function":"syncMailbox","class":"OCA\\Mail\\Service\\Sync\\SyncService","type":"->"},{"file":"/srv/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"sync","class":"OCA\\Mail\\Controller\\MailboxesController","type":"->"},{"file":"/srv/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/srv/www/htdocs/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/srv/www/htdocs/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/srv/www/htdocs/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/srv/www/htdocs/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/srv/www/htdocs/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","Line":268,"CustomMessage":"More than 1000 expressions in a list are not allowed on Oracle."},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","version":"21.0.1.1"}
```

### Mail app

**Mail app version:** 1.9.5

**Mailserver or service:** Mailbox.org

### Server configuration

**Operating system**: Ubunut 18.04

**Web server:** Apache 2.4

**Database:** MariaDB 10.3

**PHP version:** 8.0

**Nextcloud Version:** 21.0.1.1

#### Client configuration
**Browser:** (e.g. Firefox 48) Firefox 78

**Operating system:** OpenSuSE 15.2

### PR DESCRIPTION
**Pull request by miaulalala**
Oracle can't deal with more than 1000 values in an expression list for `in` queries.

Chunk all `in` queries so they'll use a max of 1000 values.

Fixes #4941

### CODE REVIEW

**Comment by miaulalala** [comment]
> /backport to stable1.9

Have you backported the array_flat_map function?

File: lib/Db/MessageMapper.php [hunk 1]
```diff
@@ -508,22 +508,26 @@ public function deleteByUid(Mailbox $mailbox, int ...$uids): void {
...
+				->where($deleteRecipientsQuery->expr()->in('message_id', $messageIdQuery->createFunction($messageIdQuery->getSQL()), IQueryBuilder::PARAM_INT_ARRAY));
+			$deleteRecipientsQuery->execute();
+		}
 
 		$query = $this->db->getQueryBuilder();
 
-		$query->delete($this->getTableName())
+		foreach (array_chunk($uids, 1000) as $chunk) {
+			$query->delete($this->getTableName())
 			->where(
```
Comment (ChristophWurst) [inline lib/Db/MessageMapper.php:525]: nit: indentation

File: lib/Db/MessageMapper.php [hunk 2]
```diff
@@ -911,22 +939,44 @@ public function findNewIds(Mailbox $mailbox, array $ids): array {
 		$qb = $this->db->getQueryBuilder();
 		$sub = $this->db->getQueryBuilder();
 
+		// $subSelect = $sub
```
Comment (ChristophWurst) [inline lib/Db/MessageMapper.php:942]: dead code?

File: lib/Db/MessageMapper.php [hunk 3]
```diff
@@ -654,6 +659,16 @@ public function findIdsByQuery(Mailbox $mailbox, SearchQuery $query, ?int $limit
 			$select = $select->setMaxResults($limit);
 		}
 
+		if ($uids !== null) {
+			$result = array_flat_map(function (array $chunk) use ($qb, $select) {
```
Comment (ChristophWurst) [inline lib/Db/MessageMapper.php:663]: nit: `return` right away instead of storing into a variable ``$result``

**Review by ChristophWurst — COMMENTED** [review]
Code looks good, didn't test though

**Review by ChristophWurst — APPROVED** [review]

File: lib/Db/MessageMapper.php [hunk 4]
```diff
@@ -508,22 +508,26 @@ public function deleteByUid(Mailbox $mailbox, int ...$uids): void {
...
 				$messageIdQuery->expr()->eq('mailbox_id', $deleteRecipientsQuery->createNamedParameter($mailbox->getId())),
-				$messageIdQuery->expr()->in('uid', $deleteRecipientsQuery->createNamedParameter($uids, IQueryBuilder::PARAM_INT_ARRAY))
+				$messageIdQuery->expr()->in('uid', $deleteRecipientsQuery->createParameter('uids'))
 			);
-		// delete all related recipient entries
-		$deleteRecipientsQuery->delete('mail_recipients')
-			->where($deleteRecipientsQuery->expr()->in('message_id', $messageIdQuery->createFunction($messageIdQuery->getSQL()), IQueryBuilder::PARAM_INT_ARRAY));
-		$deleteRecipientsQuery->execute();
+		foreach (array_chunk($uids, 1000) as $chunk) {
+			$messageIdQuery->setParameter('uids', $chunk, IQueryBuilder::PARAM_INT_ARRAY);
```
Comment (kesselb) [inline lib/Db/MessageMapper.php:514]: Is going to conflict with: https://github.com/nextcloud/mail/pull/4932

File: lib/Db/MessageMapper.php [hunk 5]
```diff
@@ -752,6 +766,16 @@ public function findIdsGloballyByQuery(IUser $user, SearchQuery $query, ?int $li
 			$select = $select->setMaxResults($limit);
 		}
 
+		if ($uids !== null) {
+			$result = array_flat_map(function (array $chunk) use ($qb, $select) {
```
Comment (kesselb) [inline lib/Db/MessageMapper.php:770]:
```suggestion
			return array_flat_map(function (array $chunk) use ($qb, $select) {
```

File: lib/Db/MessageMapper.php [hunk 6]
```diff
@@ -752,6 +766,16 @@ public function findIdsGloballyByQuery(IUser $user, SearchQuery $query, ?int $li
...
+				$qb->setParameter('uids', $chunk, IQueryBuilder::PARAM_INT_ARRAY);
+				return array_map(function (Message $message) {
+					return $message->getId();
+				}, $this->findEntities($select));
+			}, array_chunk($uids, 1000));
+			return $result;
```
Comment (kesselb) [inline lib/Db/MessageMapper.php:776]:
```suggestion
```

File: lib/Db/MessageMapper.php [hunk 7]
```diff
@@ -824,16 +848,19 @@ public function findByIds(string $userId, array $ids): array {
...
-		$select = $qb
-			->select('*')
-			->from($this->getTableName())
-			->where(
-				$qb->expr()->in('id', $qb->createNamedParameter($ids, IQueryBuilder::PARAM_INT_ARRAY), IQueryBuilder::PARAM_INT_ARRAY)
-			)
-			->orderBy('sent_at', 'desc');
-
-		return $this->findRelatedData($this->findEntities($select), $userId);
+			$results = array_merge($results, $this->findRelatedData($this->findEntities($select), $userId));
```
Comment (kesselb) [inline lib/Db/MessageMapper.php:861]: array_merge inside loops is not recommended: https://github.com/kalessil/phpinspectionsea/blob/master/docs/performance.md#slow-array-function-used-in-loop

**Review by kesselb — CHANGES_REQUESTED** [review]
Blocking until https://github.com/nextcloud/mail/pull/4932 is merged

File: lib/Db/MessageMapper.php (hunk 7 above)
Comment (miaulalala) [reply lib/Db/MessageMapper.php:861]: Very interesting, good to know!

File: lib/Db/MessageMapper.php (hunk 4 above)
Comment (miaulalala) [reply lib/Db/MessageMapper.php:523]: 4932 is merged

File: lib/Db/CollectedAddressMapper.php [hunk 8]
```diff
@@ -119,9 +119,11 @@ public function deleteOrphans(): void {
 		$result->closeCursor();
 
 		$qb2 = $this->db->getQueryBuilder();
-		$query = $qb2
-			->delete($this->getTableName())
-			->where($qb2->expr()->in('id', $qb2->createNamedParameter($ids, IQueryBuilder::PARAM_INT_ARRAY), IQueryBuilder::PARAM_INT_ARRAY));
-		$query->execute();
+		foreach (array_chunk($ids, 1000) as $chunk) {
+			$query = $qb2
```
Comment (kesselb) [inline lib/Db/CollectedAddressMapper.php:123]: Suggestion: Can we move the query builder outside the foreach and use createParameter and setParameter like in MessageMapper?

**Review by kesselb — COMMENTED** [review]
Looks good. Some smaller nitpicks :see_no_evil:

**Review by kesselb — COMMENTED** [review]
Some more nitpicks :see_no_evil:

File: lib/Db/MessageMapper.php [hunk 9]
```diff
@@ -932,17 +962,23 @@ public function findNewIds(Mailbox $mailbox, array $ids): array {
...
 			->from($this->getTableName())
 			->where(
-				$qb->expr()->eq('mailbox_id', $qb->createNamedParameter($mailbox->getId(), IQueryBuilder::PARAM_INT)),
-				$qb->expr()->gt('uid', $qb->createFunction('(' . $subSelect->getSQL() . ')'), IQueryBuilder::PARAM_INT)
+				$qb->expr()->eq('mailbox_id', $qb->createNamedParameter($mailbox->getId(), IQueryBuilder::PARAM_INT))
 			);
 
-		return $this->findIds($select);
+		return array_flat_map(function (array $chunk) use ($qb, $subSelect) {
+			$qb->setParameter('ids', $chunk, IQueryBuilder::PARAM_INT_ARRAY);
```
[the remark this answers is not in the document]
Comment (miaulalala) [reply lib/Db/MessageMapper.php]: nope, that was correct

File: lib/Db/MessageMapper.php [hunk 10]
```diff
@@ -924,25 +955,30 @@ public function findRelatedData(array $messages, string $userId): array {
...
+			$select = $qb->where(
```
Comment (kesselb) [inline lib/Db/MessageMapper.php:977]: Caution: `where` is going to overwrite a previous value. 

```
$qb->select('id')
	->from($this->getTableName())
	->where(
		$qb->expr()->eq('mailbox_id', $qb->createNamedParameter($mailbox->getId(), IQueryBuilder::PARAM_INT))
	);
```

```
SELECT `id` FROM `*PREFIX*mail_messages` WHERE `mailbox_id` = :dcValue2
```

```
$qb->setParameter('ids', $chunk, IQueryBuilder::PARAM_INT_ARRAY);
$select = $qb->where(
	$qb->expr()->gt('uid', $qb->createFunction('(' . $subSelect->getSQL() . ')'), IQueryBuilder::PARAM_INT)
);
```
```
SELECT `id` FROM `*PREFIX*mail_messages` WHERE `uid` > (SELECT MAX(`uid`) FROM `*PREFIX*mail_messages` WHERE (`mailbox_id` = :dcValue1) AND (`id` IN (:ids)))
```

The comparison for mailbox_id in the outer query is lost. I guess the subselect is always the same and could be moved outside array_flat_map. To append another expression to an existing where clause: `andWhere` / `orWhere`.

File: lib/Db/MessageMapper.php [hunk 11]
```diff
@@ -924,25 +955,30 @@ public function findRelatedData(array $messages, string $userId): array {
...
 			);
-		$select = $qb
-			->select('id')
+
+		$qb->select('id')
 			->from($this->getTableName())
 			->where(
-				$qb->expr()->eq('mailbox_id', $qb->createNamedParameter($mailbox->getId(), IQueryBuilder::PARAM_INT)),
-				$qb->expr()->gt('uid', $qb->createFunction('(' . $subSelect->getSQL() . ')'), IQueryBuilder::PARAM_INT)
+				$qb->expr()->eq('mailbox_id', $qb->createNamedParameter($mailbox->getId(), IQueryBuilder::PARAM_INT))
```
Comment (kesselb) [inline lib/Db/MessageMapper.php:972]: **Just an idea - feel free to ignore ;)**

We are using the mailbox_id in the outer query and subselect. The current code would pass three parameters to sql server: mailbox_id (outer), mailbox_id (subselect), ids

We have to ways to tell the query builder that's the same parameter: 

1. Define a placeholder `$qb->createNamedParameter($mailbox->getId(), IQueryBuilder::PARAM_INT, ':mailboxId')`
2. Define `$mailboxIdParameter = $qb->createNamedParameter($mailbox->getId(), IQueryBuilder::PARAM_INT)` and use it in both queries.

File: lib/Db/MessageMapper.php (hunk 10 above)
Comment (miaulalala) [reply lib/Db/MessageMapper.php:977]: No, the subselect can't be moved outside. The parameter `ids` is set on `$qb` inside `array_flat_map` to chunk the ids for Oracle DBs.

File: lib/Db/MessageMapper.php (hunk 11 above)
Comment (miaulalala) [reply lib/Db/MessageMapper.php:972]: Sure, but what's the benefit?

Comment (kesselb) [reply lib/Db/MessageMapper.php:972]: Cleaner code and not sending the same value twice ;)

File: lib/Db/MessageMapper.php [hunk 12]
```diff
@@ -839,17 +866,21 @@ public function findByIds(string $userId, array $ids): array {
...
 			)
 			->orderBy('sent_at', 'desc');
 
-		return $this->findRelatedData($this->findEntities($select), $userId);
+		$results = [];
+		foreach (array_chunk($ids, 1000) as $chunk) {
+			$qb->setParameter('ids', $chunk, IQueryBuilder::PARAM_INT_ARRAY);
+			$results[] = $this->findRelatedData($this->findEntities($qb), $userId);
+		}
+		return array_merge(...$results);
```
Comment (ChristophWurst) [inline lib/Db/MessageMapper.php:883]: we could also have used the flat map here

**Review by ChristophWurst — APPROVED** [review]
Looks good!

File: lib/Db/TagMapper.php [hunk 13]
```diff
@@ -134,33 +134,37 @@ public function getAllTagsForMessages(array $messages, string $userId): array {
...
-		while (($row = $queryResult->fetch()) !== false) {
-			$messageId = $row['imap_message_id'];
-			if (!isset($tags[$messageId])) {
-				$tags[$messageId] = [];
-			}
+		foreach (array_chunk($ids, 1000) as $chunk) {
+			$tagsQuery->setParameter('ids', $chunk, IQueryBuilder::PARAM_INT_ARRAY);
+			$queryResult = $tagsQuery->execute();
+
+			while (($row = $queryResult->fetch()) !== false) {
```
Comment (ChristophWurst) [inline lib/Db/TagMapper.php:151]: this done doesn't actually work. `fetch` won't return any rows but always `false`, despite `$queryResult->rowCount()` returning 1. Investigating.

**Comment by xf-** [comment]
@ChristophWurst any plans to do a release with this fix in 1.9.
Still breaks our mail at the moment and 1.10 looks more like it will be released with NC 22 and 1.9 no open PR/Backport for 1.9.6
